### ISSUE TITLE
theme: simplify stylesheet for color variants

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#107]
Creating color variants currently requires copying a lot of boilerplate styles. Let's get rid of this.

**Comment by DanielRuf** [comment]
Maybe also interesting, HSL colors are often better for creating variants. You can change the hue value or just the saturation or lighting to change one aspect of a color.

https://github.com/matcornic/hugo-theme-learn/issues/483

**Comment by McShelby** [comment]
Sounds interesting. I lack knowledge regarding CSS colors. So if you want to work on it, it may be interesting to have a second accent color for coloring the links.
