### ISSUE TITLE
notice: support custom titles

### ISSUE THREAD

**Issue by david-mkl** [McShelby/hugo-theme-relearn#124]
Hello, thanks for forking this theme!

I'm hoping this can now more easily support custom titles in notice headers (the current behavior being just a "humanized" version of the type, like "tip" -> "Tip" etc.)

It looks like you're on the way to supporting this by putting the title into a div instead of a css content attribute (as is currently the case in the original repo).

I'm thinking it would be straightforward enough to have the notice shortcode support a second argument which would be the title which could look like

```go
{{% notice note "My Custom Title" %}}
Some markup
{{% /notice %}}
```

It could easily default to the current behavior making this backwards compatible. I'm happy to take a crack at implementing this.

Thanks!

**Comment by McShelby** [comment]
Thanks for the kind words, much appreciated.

A very simple (site wide) overwrite would be to supply your own custom translation file `en.toml` (or what ever your supported languages are) and change the strings in there. The caveat is, that you need to check these files on every update of the theme and add missing new strings.

Overwriting the text via CSS `content` is not (easily) translatable. I would like to avoid such a mechanism.

But it is totally possible to change the shortcode implementation `notice.html` and provide a second title attribute that defaults to the current value if left.

The `attamchent.html` shortcode behaves much similar (with the difference of using named parameter).

So if you provide such a PR, I am more than willing to add it.
