### ISSUE TITLE
hidden pages show up in navigation when acitve

### ISSUE THREAD

**Issue by andi-blafasl** [McShelby/hugo-theme-relearn#134]
Not sure if this a Bug from the Theme or a Problem with my content structure.

I have hidden pages and, as expected, they don't show up in the navigation. They are linked manually under the "More" section. When they are shown, they appear in the navigation above the "more" section.

I hope you understand my description. You can see and test the behavior on my Site [BITS-Training.de](https://www.bits-training.de/) and the Source for Hugo is available as a Git Repository on GitHub [BITS-Hugo](https://github.com/BITS-Training/BITS-hugo)

**Comment by McShelby** [comment]
So at first: This works as designed.

Detailed explaination: If a page is hidden but resides somewhere inside your page structure, you want to see it at that certain position in the menu if the hidden page is shown. This is the same case with page-1-1-1-1-1 in the exampleSite.

A workaround would be to place your shortcut-pages in your sites root. Similar to the credits.html in the exampleSite. In this case you can remove the `hidden` frontmatter parameter.

**Comment by andi-blafasl** [comment]
Just tested your workaround and it is looking good. We will make the change in the next release

**Comment by McShelby** [comment]
For now, I'll move this to discussions and keep your remark in mind.

Improving documentation is an ongoing issue. I for myself am not happy with the current structuring. So you'll may see some improvements in the near future.
