### ISSUE TITLE
search: don't break JS in multilang setup if search is disabled

### ISSUE THREAD

**Issue by lindeMAX** [McShelby/hugo-theme-relearn#140]
Hi.
I recognized, that the language switching is not working if one disables the search bar in the config.toml.

```toml
[params]
disableSearch = true
```
If so, you will get an error trying to change the language: *Uncaught ReferenceError: baseUri is not defined*.
Beacuse of this part in the html-files:

```html
<select id="select-language" onchange="location = baseUri + this.value;">
   <option id="en" value="/" selected>English</option>
   <option id="de" value="/de/">Deutsch</option>
</select>
```

This is because of a script in *search.html* (https://github.com/McShelby/hugo-theme-relearn/blob/main/layouts/partials/search.html), that should rather be somewehere else.

```javascript
var index_url={{ "index.json" | relLangURL }};
var root_url="/";
var baseUri=root_url.replace(/\/$/, '');
```

I managed to work around this issue by putting the script in to the *cusom-footer.html* (https://github.com/McShelby/hugo-theme-relearn/blob/main/layouts/partials/custom-footer.html)

```html
<script>
   var index_url={{ "index.json" | relLangURL }};
   var root_url="/";
   var baseUri=root_url.replace(/\/$/, '');
</script>
```

**Comment by McShelby** [comment]
Thanks for reporting. This is definatly a bug. Will be fixed with the next version.
