### ISSUE TITLE
BUG's in relref shortcode:

### ISSUE THREAD

**Issue by The-going** [McShelby/hugo-theme-relearn#146]
- A permanent link to the chapter cannot be obtained for all pages. Links are handled correctly for the title pages or `_index.md ' files and if such a page does not exist, an error message or a warning appears in the log, depending on the global settings. This is the correct operation of the code.
- For the rest of the pages. If the page exists, then we have a link to this page, and not to the chapter that is on this page. If the page does not exist, then we get a link to the current page, i.e. to itself. And no messages in the log or changes in the appearance of the link. This is unacceptable behavior.

This will not be good at all if the content of a multilingual site is organized in one directory, i.e. `/_index.en.md ,_index.fr.md ,about.en.md ,about.fr.md`

There is another problem of bad links, but it relates to the short code 'mermaid'. If you do something like:
```
{{< mermaid align="left" >}}
flowchart LR;
    S("testing") --> X["Test-1"]
    style S fill:#99ccff;
    click S "{{% relref "/core/_index.md#about-testing" %}}"
    click X "{{% relref "/core/testing.md#test-1" %}}"
{{< /mermaid >}}
```
For site: `http://localhost:1313/website/`
The link will look like: `http://localhost:1313/core/testing/#test-1`
And there should be: `http://localhost:1313/website/core/testing/#test-1`
For this construction, everything is fine in the text of the page: `["Test-1"]({{% relref "/core/testing.md#test-1" %}})`

**Comment by McShelby** [comment]
So this issue is actually two.

For part I: Could you give me an example repo/zip and detailed instructions how to reproduce this

For part II: This is a hassle in the way Hugo generates sites and treat links. It already showed up serveral times in the past as with search and shortcode links. The implemented solution there is a bit tricky/hacky and can not be applied to this issue. So at the moment I don't have a solution for you.

**Comment by The-going** [comment]
OK, I've almost solved these problems. We will skip the last part about how the short code 'mermaid' handles links. I found a solution, but it only works for one content structure, i.e. a special case.

I will make an example of a test page to reproduce and a possible version of the code a little later today.

**Comment by McShelby** [comment]
As mentioned in #147:

For part I: That's a Hugo "issue" - if at least. I doubt that Hugo knows something about your headings/fragment identifiers and therefore has no chance to warn for it.
