### ISSUE TITLE
menu: bring active item in sight for large menus

### ISSUE THREAD

**Issue by Nuc1eoN** [McShelby/hugo-theme-relearn#149]
While transitioning from hugo-theme-learn to the relearn theme I have noticed a regression.

When a menu entry has a lot of contents it goes completely out of sight after clicking, e.g. this is how relearn behaves:
![image](https://user-images.githubusercontent.com/2538022/141594347-f3476bbb-c9bb-4057-b62a-0a306355fe59.png)
While this is how hugo-theme-learn behave correctly:
![image](https://user-images.githubusercontent.com/2538022/141594396-9db33d56-18ae-4eb7-9a52-0ed0ca70f38b.png)

I have tried to fix this but I couldn't figure it out. I hope it can be fixed, so that I can keep using the relearn fork.

**Comment by McShelby** [comment]
I've seen this also. This bug is related to a change in #79 and I have the feeling, that the perfect-scrollbar script and the used mechanism aren't working well together

**Comment by Nuc1eoN** [comment]
Thank you! It now works considerably better than in the "original" hugo-theme-learn! :))

**Comment by McShelby** [comment]
That was the original intention of #79. But the programmer messed up in the first try ;-)
