### ISSUE TITLE
theme: rework header UX

### ISSUE THREAD

**Issue by Nuc1eoN** [McShelby/hugo-theme-relearn#151]
The "upstream" grav learn theme has updated it's design and is now based on https://github.com/getgrav/grav-theme-learn4.

What I like about it is that the header now more cleanly sticks to the top of the page and extends to both sides.
This is fairly simple to achieve by just moving the `#top-bar` div element into the `#body` div.

However what I like even more about their updated theme is that the navigation buttons are now nicely positioned in the top right of the header. I find this to be a lot more subtle than the gigantic navigation bars (less "in your face"), but also functionally better since you do not need to move your mouse left and right as much:
![image](https://user-images.githubusercontent.com/2538022/141665385-4af47754-e954-4b02-a063-650801c5a19f.png)

I have kinda hacked it together on my part (without media queries yet), but I am also not a 100% satisfied with my code changes, so I thought I would leave this here as a feature reuqest, because @McShelby you are probably more into the code than I am at this point and maybe you will find it trivial to make this change.
I am in general more routined in using `flex`(which grave learn theme actually uses) than using floats everywhere.

If you want me to show the code let me know, or if you can implement it easily I would be very happy :)

EDIT:
In general what I did was to move `<div id="navigation">` from `footer.html` to `header.html`
Then you "just" need to adjust the css, so in my case I added this to `theme.css`:
```
#navigation {
    position: relative;
    top: 23%;
    float: right;
}
```
In `#body .nav`I removed `position:fixed`and I change `font-size` to 25px in there.
That's basically all I did and it semi-works :)

**Comment by McShelby** [comment]
Interesting change.

I haven't found a demo site for grav-theme-learn4, so I can only make assumptions from your image.

I agreee, navigation is a topic in need of improvement. There are a lot of moving parts involved and all must be taken into account in their entirety.

So it's not just the header bar and its content, but also their visuals:

- TOC
- breadcrumb nav
- GitHub edit link
- prev/next nav
- shadow on header bar while scrolling
- prev/next changes on resolution change

Making changes to this would change some iconic visuals of the theme. As a dropin replacement for the hugo-theme-learn, this is a really difficult one to decide. As I think, the hugo-theme-learn theme has become independent to its grav counterpart, we don't necessarily need to go the same lane as they did.

What I don't want is to support a "second skin" inside of the theme. Other themes tried that in the past and haven't had much love for all their supported skins.

Also, adding this to the existing CSS and hiding it behind a config parameter is also a hassle to test.

At this point, I still concentrate on bug fixes of the original theme and some smaller, easier to handle improvements. Your proposed change would be something to be considerd in the near future.

**Comment by Nuc1eoN** [comment]
> I haven't found a demo site for grav-theme-learn4, so I can only make assumptions from your image.

Sorry I forgot to put in the link, but I pretty sure they simply use it on their main documentation: https://learn.getgrav.org/17/basics/what-is-grav
In contrast, hugo-theme-lean seems to have been based on their older theme: https://github.com/getgrav/grav-theme-learn2 (look at the screenshot in the readme and you will know why^^).

> So it's not just the header bar and its content, but also their visuals:
> - TOC
> - breadcrumb nav
>- GitHub edit link
>- prev/next nav
>- shadow on header bar while scrolling
>- prev/next changes on resolution change

> TOC

Yes and no. While the TOC does not appear in their new theme (not sure if it did before, or if that was simply smth the hugo-theme-learn team decided to do), I think it is ok for it to stay where its at currently!
> breadcrumb nav

Hm I am not sure how the breadcrumb nav would be influenced by this change?
> GitHub edit link

Yes I did not take the GH Edit Link into account in my changes at all, simply because I did not have it active on my local build before. Personally, I do find the new one more visually pleasing, but I would be ok with it if it stays as it is.

> prev/next nav

This would obviously need to change :D

> shadow on header bar while scrolling

While I understand the concern, on my part it has been working flawlessly. The header modifications was one of the first things I did and I have never had issues with this particular change.

> prev/next changes on resolution change

Yeah that's probably something to take into account, and it it why I decided against implementing this whole thing myself because I do not want to break your site obviously :)

> So it's not just the header bar and its content, but also their visuals

> Making changes to this would change some iconic visuals of the theme. As a dropin replacement for the hugo-theme-learn, this is a really difficult one to decide. As I think, the hugo-theme-learn theme has become independent to its grav counterpart, we don't necessarily need to go the same lane as they did.

I understand that completely switching to everything that grav did would be nonsensical. Which is why I focused myself on just those two aspects, which seem to be an actual visual and functional improvement (at least to me), while still being quite viable to implement without rearranging the whole look.
It seems more like a tweak to me, that does a lot to its visual appearance in positive way.

I agree, and I also see hugo-theme-learn as an independent counterpart of the grav theme. However I also see your relearn theme that way :) I see you have made a lot of small usability improvements which do a whole lot for the end-user - which is why I definitely will stay with your version of the theme :)

In the same spirit I suggested this feature request right here; as a hopefully (even visually) quite non-intrusive change, but still a decent Quality of Life improvement over the existing.

Obviously you should decide for yourself what feels right to you :)

**Comment by Nuc1eoN** [comment]
Hey @McShelby I wish you a belated happy new year! :tada: 
I would like to let you know that I would be still interested in the change, since we will definitely keep this style in our gobolinux documentation.

Since the new grav learn theme uses this style, I think it is justified for hugo-relearn-theme to follow it. The hugo-learn-theme is not really maintained, so sticking to their decisions should not be the deciding factor imo.
But I'd be happy to have this even just as an option. 

Anyways if you consider this, I'm here to test this regularly and give you feedback if anything should break. Our organization is going to keep this style so we have an interest to keep it in a good shape.

Once you implement it on your side, I have a reference implementation and can even PR little improvements or bug fixes if necessary. But without a reference implementation I do not feel comfortable to make a PR about this. My code is really hacky and not mobile friendly at all. However all in all it was not that difficult of a change.
I hope that's understandable.

Either way, we will continue to use your theme  :stuck_out_tongue:

**Comment by McShelby** [comment]
I see some advantages in the grav-learn4 design and still considering how to do it best. This is not a simple change and - as mentioned above - has a lot of moving parts.

I'ld really like to change the TOC handling with this change, too, as it is not usable on a touch device at the moment. The main UX degration with grav-learn4 in comparision to relearn is, that the TOC in grav-learn4 scrolls out of view. One solution would be to let it stay at a fixed position to the left, which comes with its own set of issues (like: what happens if the TOC is longer than screen height).

There was a [PR in the hugo-theme-learn](https://github.com/matcornic/hugo-theme-learn/pull/101) which may be a good starting point.

**Comment by Nuc1eoN** [comment]
Hi @McShelby thank you for looking into this.

> The main UX degration with grav-learn4 in comparision to relearn is, that the TOC in grav-learn4 scrolls out of view.

Can you explain what you mean here? How does it scroll out of view? The header is still fixed to the top when scrolling down, so the TOC icon stays at the top left corner.

**Comment by McShelby** [comment]
I plan to get rid of the current TOC icon (and its MouseOver functionality) entirly. Instead I am thinking of implementing it as an aside as in the current grav-learn4.

**Comment by Nuc1eoN** [comment]
I agree, personally I do not like the "mouse-over" TOC either.

> (like: what happens if the TOC is longer than screen height)

How about being able to scroll the TOC in such instances?

**Comment by McShelby** [comment]
As I thought this over, it's better to keep TOC changes in a separate issue...

**Comment by Nuc1eoN** [comment]
Yes I agree, better to do one thing at a time.
And for this issue right here, the TOC design is irelevant as it works fine with both versions.

**Comment by Nuc1eoN** [comment]
@McShelby btw if you want to check out my terrible implementation of this, be free to check out https://wiki.gobolinux.org/ :)

Also you can add us to your "Showcases" page if you think we deserve it :)

**Comment by McShelby** [comment]
Definetly a starting point.

The arrows are in need for position adjustment but that shouldn't be to hard.
The edit button should be left of the arrows (as in grav-learn4) because on a mobile device the often used actions should be positioned near screen borders.

Offtopic: Nice color scheme. Did you need to hack the theme in order to achieve the "dark mode" look? I remember there was an open issue in the Learn theme for this. Just curious.

![grafik](https://user-images.githubusercontent.com/11670870/152487126-9a6df69b-9665-456f-845d-be93c42e439f.png)

**Comment by Nuc1eoN** [comment]
>The arrows are in need for position adjustment but that shouldn't be to hard.

Yes true, my arrows are misaligned (esp when resizing), and the hover animation is awful. However at that time I figured my time would be better spent on porting the actual documentation from a mix of mediawiki and md files ugh :)

>The edit button should be left of the arrows (as in grav-learn4) because on a mobile device the often used actions should be positioned near screen borders.

Absolutely. I think what what demotivated me to fix it is that the design uses floats instead of flexbox to position the elements. So I came again back to my priorities.

>Offtopic: Nice color scheme. Did you need to hack the theme in order to achieve the "dark mode" look? I remember there was an open issue in the Learn theme for this. Just curious.

Thank you. Absolutely, I just made my own `theme-gobolinux.css`. A dark/light mode button would be nice, but for now Im just sticking to the dark theme.
I will admit that I let myself being inspired by the https://darkreader.org/ extension to choose the right color balance, since it is doing a great job (in dynamic mode).

**Comment by Nuc1eoN** [comment]
@McShelby Call me blind, but I cannot figure out what triggers the animation when hovering over the nav buttons:
![image](https://user-images.githubusercontent.com/2538022/152583811-46fc2a5e-80be-45ce-a7d4-1abeb7893534.png)
Just can't find it.
