### ISSUE TITLE
menu: align long text properly

### ISSUE THREAD

**Issue by Nuc1eoN** [McShelby/hugo-theme-relearn#154]
Hi again!

I have noticed that if a menu item is "too long" and a line break occurs, the text will not be properly aligned in the next line:
![image](https://user-images.githubusercontent.com/2538022/141720471-e6f05030-a284-456d-9559-648c418c704e.png)
Looks messy :)

**Comment by McShelby** [comment]
Also, it looks weird for the visited links marker
![grafik](https://user-images.githubusercontent.com/11670870/141864830-8d065581-2418-4b0e-b23e-c04e25db818f.png)
