### ISSUE TITLE
search: make dropdown stick to search field when scrolling

### ISSUE THREAD

**Issue by Nuc1eoN** [McShelby/hugo-theme-relearn#155]
When you type something into the search field a dropdown with search results appears.
But upon scrolling the dropdown does not "stick" to the search field but floats up with the rest of the page.

**Comment by McShelby** [comment]
Funny effect ;-)

**Comment by McShelby** [comment]
Not done, yet...

**Comment by McShelby** [comment]
Maybe now..?
