### ISSUE TITLE
toc: rework UX

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#167]
The current TOC implementation isn't usable on touch devices as it's only working on MouseOver.

Reference: matcornic/hugo-theme-learn#67

The new TOC implementation should:

- be usable on touch as on pointer devices
- be accessible even if the page is scrolled down
- take the least space possible
- may have configurable behaviour (to resemble the old UX)

This was discussion started in #151 and is now keept track in its own issue.

Consider PR in matcornic/hugo-theme-learn#101.

**Comment by Nuc1eoN** [comment]
Continuing from #151 
>(like: what happens if the TOC is longer than screen height)

Check out the test page https://process-sdk-draft.doc.moovapps.com/rest/. It is not a problem when the toc exceeds screen height. MAke the browser window smaller until it covers the toc. Now the toc is scrollable.

**Comment by McShelby** [comment]
Neither FF nor Chrome shows any scrollbar for the TOC - or do I miss a thing here?

![grafik](https://user-images.githubusercontent.com/11670870/152486206-cc190749-feb8-4b22-ad5d-c08b7db6e898.png)

**Comment by Nuc1eoN** [comment]
Weird.. for me it shows up when I start to scroll the TOC with my mouse wheel!
![image](https://user-images.githubusercontent.com/2538022/152502398-ad0d5bda-fb41-45ef-9709-ea6462b9aafa.png)
Both Chrome and Firefox

**Comment by McShelby** [comment]
That's maybe the point here: I don't use a mouse but a trackpad. Therefore: no wheels attached ;-)
Scrolling should definetly work on any device.

**Comment by Nuc1eoN** [comment]
I just tried on my laptop which has a trackpad and I have no problems scrolling the TOC frankly. It behaves just the same as when using the mouse wheel.

**Comment by McShelby** [comment]
You forced me to RTFM ;-) So at least, I learned how to scroll with my touchpad, today.

Yes, it scrolls but while scrolling there *doesn't* appear a small scroll bar as in your image.

Really wild issue

**Comment by Nuc1eoN** [comment]
> You forced me to RTFM ;-) So at least, I learned how to scroll with my touchpad, today.

Hah! You have utterly amazed me by that comment! :D

> Yes, it scrolls but while scrolling there doesn't appear a small scroll bar as in your image.

Huh?! Weird. I actually noticed that it even appears on *hover*, so even if for some reason a user would not have scroll, he could still drag it.
But that it doesn't show on your side!? I don't know what's happening there :)

**Comment by Nuc1eoN** [comment]
![image](https://user-images.githubusercontent.com/2538022/152846011-5b0f997a-e200-4f46-a55e-4be1dc8c882b.png)
Somehow your page looks a lot worse than mine... Compare the breadcrumbs.

This is because on your side, the top-bar gets squeezed. On my side the top-bar has still the full width.

Not sure whats going on :eyes:

**Comment by McShelby** [comment]
The main usability concerns were addressed in #268.

This is not the big rework of this issue but at the moment I have no plans for more drastic changes.
