### ISSUE TITLE
theme: add a theme selector

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#178]
This will allow for multiple theme variants configured that can be switched by the user.

**Comment by Nuc1eoN** [comment]
You are reading my thoughts xD

**Comment by Nuc1eoN** [comment]
Implementation is soo neat! Thank you!!

Now I am considering of bringing my light theme up to date^^

**Comment by McShelby** [comment]
Btw: The official documentation always shows the latest pushed version. So for a quick view of the latest changes you don't have to update your installation (but you have probably been aware of this).
