### ISSUE TITLE
print: hide sidebar on Mac

### ISSUE THREAD

**Issue by cagix** [McShelby/hugo-theme-relearn#183]
When printing a page, the menu gets also printed and takes up a relatively large amount of space (about half a page). Is there a way to simply hide the menu when printing?

Using Firefox and Safari (macOS).

<img width="1162" alt="Screenshot 2022-02-16 at 10 55 26" src="https://user-images.githubusercontent.com/20356276/154240964-9f561790-23b1-48c3-8342-364213fe5b4c.png">

Related to https://github.com/matcornic/hugo-theme-learn/issues/413

**Comment by McShelby** [comment]
Thanks for reporting! This is fixed for Chrome and FF on Windows (at least in my environment).

I've pushed a change that may help. Problem is, I don't have access to a Mac. So feedback and help is really appreciated here.

Remark: Please, also check a page containing normal content, as it shows the sticky header which is also reformatted for print and theirfore may also be broken on Mac.

**Comment by cagix** [comment]
@McShelby wow, that seems to have helped. i can now print with both firefox and safari without the menu interfering.

thank you very much for the super quick bug fix! 

here some screenshots as "proof":
<img width="1113" alt="Screenshot 2022-02-16 at 16 55 17" src="https://user-images.githubusercontent.com/20356276/154305290-0986e380-44be-4cd9-8590-a0f74a9ec682.png">
<img width="1113" alt="Screenshot 2022-02-16 at 16 55 39" src="https://user-images.githubusercontent.com/20356276/154305333-6404f197-c8b7-4002-8659-0946a1312506.png">
<img width="1062" alt="Screenshot 2022-02-16 at 16 56 02" src="https://user-images.githubusercontent.com/20356276/154305350-978256b6-6fc9-462d-a954-cfce7be56a80.png">
<img width="1062" alt="Screenshot 2022-02-16 at 16 56 41" src="https://user-images.githubusercontent.com/20356276/154305364-144a2d91-1210-4cfb-a16f-0b7b3f9c8b4d.png">

**Comment by McShelby** [comment]
Great! Thats how it should look!
