### ISSUE TITLE
mermaid: lazy render graph if it is initially hidden

### ISSUE THREAD

**Issue by FantasyTeddy** [McShelby/hugo-theme-relearn#187]
Hi everyone,
I have two issues with the `expand` shortcode:
1. Is it correct that I need to introduce some additional shortcode in order to embed markdown **as well as** another shortcode within the `expand` shortcode?
   The additional shortcode I used contains: `{{ .Inner | markdownify }}`
2. I somehow cannot get Mermaid to work inside the `expand` shortcode.

Since those are quite specific problems, I created a repository with those problems in it: https://github.com/FantasyTeddy/relearn-shortcodes
The resulting page can be found at: https://fantasyteddy.github.io/relearn-shortcodes/

Am I doing something wrong or is this a limitation of the `expand` shortcode that is already known?

**Comment by McShelby** [comment]
You're right, usage of shortcodes inside of shortcodes is limited by Hugo's architecture.

For your specific problem you can use mermaid code fences instead of the shortcode. This works as expected. Eg:

````plaintext
```mermaid
classDiagram
    Person *-- Dog
```
````

**Comment by FantasyTeddy** [comment]
Thank you for the clarification.

Unfortunately even when using mermaid code fences instead of the shortcode, it does not work. (I added this variant to my example code.)
However I noticed that if I use the initially expanded version of the `expand` shortcode (`{{% expand "..." "true" %}}`) it renders correctly. Maybe it has something to do with the fact that it has to render in a `div` with `display: none;`?

**Comment by McShelby** [comment]
That's a real pitty. You're right, this is an issue of Mermaid. Interestingly, each Mermaid graph behaves differently but none is displayed correctly.

We may could work around this, if we set `height: 0` for a collapsed expand instead of `display: none` and giving the parent an `overflow: hidden`. But I am not sure if this would trick Mermaid in generating the graph correctly.

But that's just a trick and would probably not work well with screen readers.

**Comment by McShelby** [comment]
A more robust solution may be on the horizon by letting Hugo generate the graph gohugoio/hugo#9521

**Comment by FantasyTeddy** [comment]
I agree that implementing a workaround is probably not the best idea.
Maybe think about adding some kind of note in the documentation to make people aware of this limitation?
Otherwise feel free to close this issue, since there is most likely not much that can be done about it.

**Comment by McShelby** [comment]
Docs added. I will keep this issue open as a reference until either Hugo or Mermaid comes up with a fix.

**Comment by McShelby** [comment]
The limitiation of not displaying initially hidden Mermaid graphs is fixed with the next release.
