### ISSUE TITLE
variant: build a color variant generator

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#188]
As color variants get trickier, we should build a color variant generator to build stylesheets visually.

**Comment by McShelby** [comment]
@Nuc1eoN: A first draft for a color variant generator landed in the official docs.

Currently the page is `hidden` but you can find it by using the search for the term *generator*.

As always, feedback really appreciated.

**Comment by Nuc1eoN** [comment]
Hey @McShelby sorry I was really busy and could only just now take a look.

It is pretty INSANE! Never seen something like this, awesome.. there's really nothing left for criticism here imo Im blown away!

I do not even know how you did it. I suppose with mermaid. (never used it personally)

**Comment by McShelby** [comment]
> It is pretty INSANE! Never seen something like this, awesome.. there's really nothing left for criticism here imo Im blown away!

Thank you, @Nuc1eoN!

> I do not even know how you did it. I suppose with mermaid. (never used it personally)

Yesss, Mermaid! And with the help of Chrome devtools ;-)
