### ISSUE TITLE
theme: revert fontawsome to version 5 for IE11 compat

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#191]

**Comment by Nuc1eoN** [comment]
Ahhh dammit, I liked the new icons :cry:

**Comment by McShelby** [comment]
Sorry for that, as IE11 is still a thing for my company :-(

The icons used in the theme are okay in either Fontawesome version.

But in my company we are also using a lot of icons inside our sites (usually for menu entries) and those are imho sub par in version 6. The sizing seems a bit off in direct comparison to the version 5 icons.

Anyways, this was not the reason to switch.

But..., you can overwrite the `fontawesome.min.css` and the files of `webfonts` in your project's `static` folder. Sadly there is one reference that also needs to be changed in the CSS.

**Comment by Nuc1eoN** [comment]
Yeah not sure if it is worth the effort though. Or rather the increased maintainance burden.

I am very happy with how my documentation code has turned out, especially with relearn v3. Very straight forward, easy to maintain, easy for others to get into.
