### ISSUE TITLE
variant: fix inconsistent color variable naming 

### ISSUE THREAD

**Issue by Nuc1eoN** [McShelby/hugo-theme-relearn#200]
Hi I have noticed the following:
```
    --MENU-SECTION-ACTIVE-CATEGORY-color:
    --MENU-SECTION-ACTIVE-CATEGORY-BG-color: 
    --MENU-SECTIONS-BG-color
    --MENU-SECTIONS-ACTIVE-BG-color:
    --MENU-SECTIONS-LINK-color:
    --MENU-SECTIONS-LINK-HOVER-color: 
```
Some of those have the name `SECTION` while other are called `SECTIONS`. Is that on purpose? It seems like a typo to me.
Probably it should be called `SECTION`?

The above list might be incomplete, I did not check every variable :)

EDIT:
Also, shouldn't `--MENU-SEARCH-BOX-color` actually be called `--MENU-SEARCH-BORDER-color`? It modifies the border (that's even what it says in the comment description). I guess that would make more sense? Looks like an oversight to me.

**Comment by McShelby** [comment]
As 3.0.0 is just a day old, I decided to change the name of `--MENU-SEARCH-BOX-color` to `--MENU-SEARCH-BORDER-color`

**Comment by Nuc1eoN** [comment]
What about the SECTION(S) naming?

**Comment by McShelby** [comment]
See my explaination above. Won't change.

**Comment by Nuc1eoN** [comment]
Excuse me, but where, or what is the explanation?

**Comment by McShelby** [comment]
Oh dear. I am messed up. Seems I wrote an explaination this morning but did not hit sent?!? Usually GitHub saves the text, but as I already answered here later, the text is now gone. Okay, let's explain - again - Note to myself: Hit the big green "Comment" at the end...

At first when I started with this theme I felt the same about the SECTIONS vars. Now that I am used to it, the naming makes sense as there can be only zero or one active sections, while you can usually have many sections been displayed.

**Comment by Nuc1eoN** [comment]
No issues that happens sometimes! Ty for the explanation.
