### ISSUE TITLE
theme: adjust breadcrumb and title for empty home page titles

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#202]
Good morrow!

>I've changed the authoring in the showcase. Because it is centered on the theme's usage, I omit links to the authors (also the heading would get to crouded with links).

Yup I get the reasoning. In that case, would you be so kind and adapt it to `NEONsys.org`? It is what I am using in case hyperlinking is not possible, eg in the [license file](https://raw.githubusercontent.com/gobolinux/Documentation/master/LICENSE).

>Looks spiffy

Thank you! Would you mind helping me out with some last, still unresolved issues?

1. Redundant artifact in breadcrumb bar:
![relearn_breadcrumb](https://user-images.githubusercontent.com/2538022/155480595-444d1f41-aee3-42b3-837f-530081e60151.jpg)

Since the beginning I always having that starting `>` in my breadcrumb bar. I find it unnecessary and would like to get rid of it :) I saw that your example page does not exhibit this behaviour, so I wonder what causes it.

2. Selector in front of title, even on main page:
![relearn_selector](https://user-images.githubusercontent.com/2538022/155481340-581071a7-04a3-48ae-a579-e94d7cf4614d.jpg)
 Huh now that I think of it, maybe those two issues are related? Your exampleSite also does not show this behaviour.

_Originally posted by @Nuc1eoN in https://github.com/McShelby/hugo-theme-relearn/issues/175#issuecomment-1049585425_

**Comment by McShelby** [comment]
@Nuc1eoN: I'll take a look into this. Most likely something special with your site configuration that is not correctly handled by the theme.

**Comment by McShelby** [comment]
@Nuc1eoN: The reason for this is, that your home page (your `content/_index.md` does not have a title. I am not sure if this is a good idea in general as a lot of other functionality in the theme uses the title for various stuff.

Please note that therefore all non home pages are treated as hidden if they don't provide a title! This is a specific feature of the Relearn theme.

**Comment by McShelby** [comment]
I've made a fix to breadcrumbs and titles to fix this special case. *This will only work for the home page as all other pages without a title are treated as hidden.*

So the fix is this: If no title is set, the site`s title is used.

If the page title is equal to the site's title, only the site title will be printed without the titleSeparator.

Nevertheless I advise you to give a title to all pages. In case of the home page, just give it the same title as the `title` parameter from your `config.toml`.

In a multilang installation also the `[Languages.en] title` should have the same value.

I have fixed this for the exampleSite, so you can  look at the patch to see in which locations you may need to fix this.

**Comment by Nuc1eoN** [comment]
Ahh I never would have guessed. I have added a title now.

But you've also came up with a great fallback behaviour - kudos!
