### ISSUE TITLE
mobile: difficult to close toc

### ISSUE THREAD

**Issue by Nuc1eoN** [McShelby/hugo-theme-relearn#209]
Hi I have noticed that on my mobile phone once I open the toc:
![2022-02-25_06:22:47](https://user-images.githubusercontent.com/2538022/155659028-ac11fe87-257a-45aa-8f18-269901d52ce7.png)

It can not be closed easily by tapping somewhere else.

It is only possible to either select one of the items or reload the page to close it.

This does not happen in the browser inspector, so it has to be tested on an actual mobile device.

**Comment by McShelby** [comment]
...uh, that's a hard one. Will take a bit to get into this.
