### ISSUE TITLE
mobile: remove breadcrumb ellipsis

### ISSUE THREAD

**Issue by Nuc1eoN** [McShelby/hugo-theme-relearn#211]
Hi, apparently on mobile phones the top bar is not really wide enough to display any useful info, as such it basically _always_ looks like this on relearn:
![2022-02-25_06:21:24](https://user-images.githubusercontent.com/2538022/155659938-88f00426-93bb-4d94-a5ce-de0f1a937e26.png)

I was curious how the official grav theme handles this, and it appears at a certain threshold, they simply do not display the breadcrumb bar anymore:
![2022-02-25_06:21:46](https://user-images.githubusercontent.com/2538022/155659945-921e6cbf-0945-4b1c-8082-d17dae28c2e3.png)

You should check it out yourself. It is really not useful, and frankly a bit weird, to always just have "..." in the topbar on a mobile phone.

I think the grav solution is quite pragmatic and I agree with it. But obviously you should make up your own mind, those are only pointers.

Thanks again.

**Comment by McShelby** [comment]
You're right. I've already recognised it in the past but forgot about it. Thanks for the issue. This should be an easy one

Honestly, mobile isn't very high on my list :-(
