### ISSUE TITLE
resources: new shortcode to deprecate attachments shortcode

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#22]
Adapt how the `attachments` shortcode work by providing a new shortcode `resources`. Use Hugo's page bundles/resources instead of a custom implementation.

Reference: matcornic/hugo-theme-learn#465
Reference: matcornic/hugo-theme-learn#387
Reference: matcornic/hugo-theme-learn#100

**Comment by McShelby** [comment]
Wait till gohugoio/hugo#7437 is fixed

**Comment by flexxgaad** [comment]
> Wait till [gohugoio/hugo#7437](https://github.com/gohugoio/hugo/issues/7437) is fixed

https://github.com/gohugoio/hugo/issues/7437#issuecomment-1902718935

**Comment by McShelby** [comment]
I am following the Hugos commits, sadly, the mentioned ticket is closed but not resolved.
