### ISSUE TITLE
theme: apply user supplied content footer below content

### ISSUE THREAD

**Issue by andrucha97** [McShelby/hugo-theme-relearn#229]
Since the last updates, the custom footer is displayed on the left side of the content:

![custom-footer](https://user-images.githubusercontent.com/45176192/160806028-04e57c6f-b51d-485b-b2c2-01f478fc2915.png)

We need something for displaying git Information. Maybe we can implement something like the current TOC window or the custom-footer is as it was on the bottom of the page.

**Comment by McShelby** [comment]
Thanks for the ticket.

The `custom-header` partial historically had to functions:

- add javascript at the end of your page
- add a footer to your content

With the latest layout changes, the second use case is broken.

As `custom-header`, `custom-footer` is now meant only for the first use case to include addtional scripts and styles.

While `menu-footer` provides the possibility to add content at the end of the menu, I will introduce a new partial `content-footer`, that accomplishes the same for the content area.

**Comment by andrucha97** [comment]
@McShelby nice! Great work!
