### ISSUE TITLE
Scrollbar broken on mobile

### ISSUE THREAD

**Issue by Nuc1eoN** [McShelby/hugo-theme-relearn#243]
Hi,

So ever since v3.0 or so the scrollbar on mobile is broken.

First of all I have noticed that I cannot scroll freely on my smartphone ("swipe and let go"), meaning the content stops instantly. But maybe that is intentional? I do not find this deviation from the default very pleasant.

But there is also a more severe issue, when you drag the scrollbar on mobile, it will from that moment forth be "stuck"/always selected. So now when you try to scroll by "dragging" the content, it will malfunction, and behaves as if you are still dragging the scrollbar.

I hope the description is clear. This can also be tested using the inspector (mobile view) in the browser.

**Comment by McShelby** [comment]
Although I could not reproduce your issue, I've removed the perfect-scrollbar in #242 for now.

Would be great, if you could check this out.

For the menu, I haven't changed a thing, so this may still be buggy.
