### ISSUE TITLE
Scrollbar slider is too thin

### ISSUE THREAD

**Issue by Nuc1eoN** [McShelby/hugo-theme-relearn#244]
I have noticed that it is possible to click ~2px to the left and right of the scrollbar.
When you do that, you will not "drag" the slider, but instead the page scrolls immediately to the very bottom.

So the sliders dragable area should be made a tad wider, so that the user doesn't miss-click.

**Comment by McShelby** [comment]
Is this for the menu or the content scrollbar? In #242 I've removed the custom content scrollbar, so this may fix this issue, too.

**Comment by McShelby** [comment]
@Nuc1eoN: Please reopen, if this still happens after I removed the scrollbar for the main section in #242.
