### ISSUE TITLE
docs: clarify usage of shortcodes in included content

### ISSUE THREAD

**Issue by gary-vertica** [McShelby/hugo-theme-relearn#245]
The [documentation for the include shortcode](https://mcshelby.github.io/hugo-theme-relearn/shortcodes/include/) states: 

> You can add... other shortcodes besides include

However, this does not work. For example, adding the dropdown example:

`
{{% expand "Expand me" %}}
Yes, you did it!
{{% /expand %}}`

to `INCLUDE_ME.md` in the Relearn documentation results in the shortcode text appearing, rather than a dropdown.

I just (as I was typing this) now noticed the closed Issue #221. If this is a known issue, you should change the documentation  cited above to save others time and aggravation.

**Comment by McShelby** [comment]
I'll change the documentation for now. Hopefully at some day #221 will be fixed upstream.
