### ISSUE TITLE
i18n: fix search for non western languages

### ISSUE THREAD

**Issue by kultpro** [McShelby/hugo-theme-relearn#269]
It is not possible to configure the operation of the search module with Cyrillic. Is there such a possibility?

**Comment by McShelby** [comment]
Languages contained in the theme but currently unsupported by latest lunr:

- id
- kr
- pl

**Comment by kultpro** [comment]
Thanks for the quick solution! But there was another problem. The Cyrillic alphabet is being searched for, but the Latin alphabet is not. Before that, it was the opposite).

**Comment by McShelby** [comment]
That's correct. It only searches in the selected language.

I agree that especially for documentation you may have multiple languages contained in your content. Eg. if you document your english source code in a foreign language.

I'll try some further things...

**Comment by McShelby** [comment]
Follow up in #271

**Comment by kultpro** [comment]
Thank you for your answer and help!
