### ISSUE TITLE
tabs: fix wrapping when having many tabs

### ISSUE THREAD

**Issue by morduun** [McShelby/hugo-theme-relearn#272]
When a tab selector has more than one page-width worth of tabs and the presentation shifts to two or more rows of tabs, the location of the second and further rows of tabs changes (shifting horizontally) based on the location of the tab clicked on the row above.

It's a little messy to explain - following video shows exactly what I'm talking about much more effectively.

https://user-images.githubusercontent.com/25253654/173442371-45611b1c-afc8-4ac2-98b3-5c058efb3bd2.mp4

**Comment by McShelby** [comment]
Well sounds like a tough one... I am not sure my CSS-foo is that good, so any help appriciated.

**Comment by morduun** [comment]
Hahaha yeah my css-foo is pretty abysmal, figured I might at least lob it upstream to see if anyone knew any easy fixes before I dove in. Let me tinker for a bit and see what I can come up with, if there's anything useful I'll do a pull req and let you know. It _looks_ like some kind of `[iterator] -1` issue but it's almost never what it seems like at first.

**Comment by McShelby** [comment]
Tabs are never looking good if they got wrapped to the next line, but at least I could fix the error of the moving tab handles
