### ISSUE TITLE
a11y: remove WCAG errors where applicable

### ISSUE THREAD

**Issue by BITS-Editor** [McShelby/hugo-theme-relearn#307]
We are planning to get a Barriefreiheitserklärung (declaration of accessibility) for https://github.com/BITS-Training/BITS-hugo

The declaration will only be valid for a certain version of the hugo theme, in this case hugo-theme-relearn

We are discussing whether the declaration could be valid for all patch versions (e.g. 1.1.x), or even minor versions (1.x.0).

The problem is that hugo-relearn-theme makes great progress and leaps from one major version (x.0.0) to the next quite rapidly.

We would welcome if the versioning would strictly adhere to Semantic Versioning and the model used in the [Git-flow-Workflow](https://www.atlassian.com/de/git/tutorials/comparing-workflows/gitflow-workflow), resulting in fewer major and minor versions.

Otherwise, we would have to re-test each new version of BITS-hugo and pay for that to keep the declaration of accessibility valid.

**Comment by McShelby** [comment]
a11y (Barrierefreiheit) is something that isn't tested with the theme and which is also not an asserted feature.

So at this point it is more or less "If it works, it works". 

Therefore each new version - regardless if it's major, minor or patch - may result in a breakage. Usually I try to adhere to semver, but that's only for supported features which a11y isn't.

Supporting such a feature is time consuming and, although I would like to support it, not on my list of planned features for the foreseeable future.

So the best advise I could give is: Pick an older, settled version and stick with it (at least for a longer period of time).

Good news is, that there isn't much left on my todo list (see open issues), so I expect development (and amount of releases) to slow down significantly starting in autumn when the latest changes have settled.

Maybe it's best for you to wait another 1-2 month and start your certification process.

**Comment by BITS-Editor** [comment]
Thanks! It seems that waiting might indeed be the right way for us right now.

However, we would welcome for future versions seeing accessibilty as an important feature. As a matter of fact, all government agencies in Germany must provide the aforementioned declaration.

**Comment by McShelby** [comment]
As said, a11y is a time consuming feature I don't have expertise in. The effort for me to support this in my spare time is simply not possible.

Nevertheless I am willing to take contributions in form of PRs. So if you (or anyone else) want to work on that feature, just drop me a line.

Although I like the thought behind that German agency requirement, the way they try to push it with their bureaucracy I don't.

**Comment by BITS-Editor** [comment]
> Good news is, that there isn't much left on my todo list (see open issues), so I expect development (and amount of releases) to slow down significantly starting in autumn when the latest changes have settled.
> 
> Maybe it's best for you to wait another 1-2 month and start your certification process.

Any news on the development timeline? Do you think we could start our certification process in September or would that be too early for a more stable version in the forseeable future?

**Comment by McShelby** [comment]
As you can see from the [Release list](https://github.com/McShelby/hugo-theme-relearn/releases) there were only smaller things worked on and - as mentioned above - currently there aren't many things left in the [issue tracker](https://github.com/McShelby/hugo-theme-relearn/issues)

Whether you want to start certification I can't advise. This depends on the implication with such a certification.

As for the a11y feature itself, I don't plan to implement this myself but I am open for PRs.

**Comment by BITS-Editor** [comment]
Thanks for the fast answer! 👍

I just wanted to know whether the remaining issues might be addressed this month - or later 😉

**Comment by McShelby** [comment]
FYI: all issues in the issue tracker tagged in beige or purple are on hold for one reason or the other.

**Comment by BITS-Editor** [comment]
> FYI: all issues in the issue tracker tagged in beige or purple are on hold for one reason or the other.

Thanks for the clarification! I am really grateful for your help - and work!

**Comment by McShelby** [comment]
I am still not willing to officially support a11y as a feature.

But as you see here, I am making some changes to fix labeling of form fields and some obvious minor tweaks.

Things that will not be fixed:

- colors for buttons / notice / attachment - to achieve a11y here, colors must be dimmed drastically which looks dull.

  Professional UI tools usally come with a highcontrast theme / variant to address this. That is also the way to go in this theme. I will not implement this but am open for PRs for this.

- false positive complaining for usage of "jump menus" which is technically [not the case](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event#browser_compatibility) in latest browser implementations anymore.

- false positive complaining about the usage of `noscript`. This is not used for a11y here but for [technical reasons](https://github.com/filamentgroup/loadCSS/blob/master/README.md#how-to-use)

**Comment by BITS-Editor** [comment]
Thank you! This is really helpful😃
