### ISSUE TITLE
executing "partials/body.html" at <.page>: can't evaluate field page in type *hugolib.pageState

### ISSUE THREAD

**Issue by bmalinconico** [McShelby/hugo-theme-relearn#314]
Morning,

I just updated to 5.1.2 for the Mermaid Header fix and started receiving the following error on build. I see that there was recently an update to this file. I'm not sure what to provide to help you diagnose this issue, but please let me know

We are using Hugo 0.101.0

**Comment by McShelby** [comment]
Hard to tell without your project code and the commandline you've used for generation.

From my experience I'ld say, your theme upgrade messed up.
