### ISSUE TITLE
print: fix urls for uglyURLs=true

### ISSUE THREAD

**Issue by cagix** [McShelby/hugo-theme-relearn#322]
Enabling ["ugly URLs"](https://gohugo.io/content-management/urls/#ugly-urls) does not seem to be compatible with the new [print support feature](https://mcshelby.github.io/hugo-theme-relearn/basics/configuration/#activate-print-support): All subpages are displayed in **print mode**. 

MWE: Checkout the Hugo Relearn theme version 5.2.1 and add `uglyurls = true` to `config.toml`. The homepage is displayed normally, all subpages will be displayed only in print mode. However, the URLs point to the normal subpages, i.e. something like `...exampleSite/public/basics.html`.

<img width="400" alt="Screenshot 2022-08-23 at 07 53 06" src="https://user-images.githubusercontent.com/20356276/186080843-70194187-2774-46d1-b79b-30db145860d1.png">

<img width="400" alt="Screenshot 2022-08-23 at 07 53 16" src="https://user-images.githubusercontent.com/20356276/186080887-18545f57-7a09-4ba1-b58b-58cb9e97fa7d.png">

Once you deactivate the new print feature (remove the `"PRINT"` entries in `[outputs]`), the subpages are also displayed normally again.

Tested with Hugo 0.101.0 and Hugo Relearn theme 5.2.1.

**Comment by McShelby** [comment]
Thanks for reporting!

**Comment by cagix** [comment]
Thanks for the clarification. 

So the takeaway message is that uglyURLs and print just won't work together? Is there any way to get both options working? You wrote, that one could change the definition of `outputformats.PRINT`. Any advise how to do so?

**Comment by McShelby** [comment]
No no. You can use uglyURLs, but they will only be used for the usual HTML page. For the print-preview it falls back to "prettyURLs".

Eg. if I apply uglyURLs to the theme's `exampleSite` you would have a URL `.../basic.html` for the page of the first chapter but still `.../basic/_index.print.html` for its print preview.

The patch for this is pushed and I've released a new version specifically for this bug fix yesterday.

**Comment by cagix** [comment]
Oh, my bad. I only noticed commit [0fb76d2](https://github.com/McShelby/hugo-theme-relearn/commit/0fb76d2a37580584c6872b563cf403c19ec7229a) listed in the timeline, which seems to contain just a note/clarification (`_index.en.md`) and a new toggle in `config.toml`.

**Comment by McShelby** [comment]
Yeah, the additional option in `config.toml` is the fix. Please note, that this is the `config.toml` that comes **with the theme** (and not with the `exampleSite`). Besides updating your installation, you don't need to change anything to make it work!

**Comment by cagix** [comment]
Ah, I see :)  Thank you again very much for your work on this beautiful theme!
