### ISSUE TITLE
Problem with mathjax rendering in multiline equation an matrix

### ISSUE THREAD

**Issue by sylm21** [McShelby/hugo-theme-relearn#325]
In the issue #235 you cite this link for mathjax rendering

[https://yihui.org/en/2018/07/latex-math-markdown/](https://yihui.org/en/2018/07/latex-math-markdown/)

if I make the following example 

{{< math >}}$$\begin{vmatrix}a & b\\
c & d
\end{vmatrix}=ad-bc$${{< /math >}}

the rendering isn't correct , it's flat not with a multiline matrix. It's the same case with eqnarray, align ... latex function.

![image](https://user-images.githubusercontent.com/8123018/188813193-78308e16-81ef-4884-9e56-b7ffeabefdad.png)

**Comment by McShelby** [comment]
There is a `\` missing on your first line. Fixing this, works fine for me either with codefence or shortcode syntax.

````
{{< math >}}$$\begin{vmatrix}a & b\\
c & d
\end{vmatrix}=ad-bc$${{< /math >}}
````

**Comment by sylm21** [comment]
Ok i forgot, it's ok for me too. 

my problem was that I didn't put ```{{< math >}}$$\begin{vmatrix}``` on the same line

Thanks a lot

I have an other problem with mathjax rendering 

```{{< math >}}$\underline{\sigma}${{< /math >}}``` and ```{{< math >}}$\underline{\underline{\sigma}}${{< /math >}}```

render without underline ?

![image](https://user-images.githubusercontent.com/8123018/188884529-4e56bf92-56c5-4695-bbd2-6852b23e946f.png)
 any idea ?

**Comment by McShelby** [comment]
Your code works on the demo site in FF and GC. So maybe something with your site styles.

**Comment by sylm21** [comment]
Okay, thank you for your time in responding to me. I will look into the style of the site and try to understand the differences.

Excuse me again for these silly questions
