### ISSUE TITLE
theme: option to align images

### ISSUE THREAD

**Issue by shigita** [McShelby/hugo-theme-relearn#327]
Hello, thank you for this fancy theme!

I have a question:
Is there any way to align or float images to left side?

**Comment by McShelby** [comment]
Currently this is not possible other than to add further user styles or use HTML inside the markdown.

It could be more elegantly done by adding another option to image formatting as [explained in the docs](https://mcshelby.github.io/hugo-theme-relearn/cont/markdown/#further-image-formatting)

A PR is much appreciated.

**Comment by shigita** [comment]
Thank you for your quick response.

Since I'm a complete novice for CSS and HTML, I can't promise to contribute for implementing this feature.
But I'll do some research to find a way :)
