### ISSUE TITLE
Allow Case sensitive naming of color variants

### ISSUE THREAD

**Issue by BITS-Editor** [McShelby/hugo-theme-relearn#332]
Color variants are great. We need to name them according to the name of our website, including case sensitivity.

**Comment by McShelby** [comment]
The name of a theme is automatically cased by the given file name.

There are ways to work around this, but neither are trivial fixes. Also, compatiblity with existing installations is mandatory for this change and will introduce further complexity for this feature by almost no gain.

You may work around this in your installation by adding some more JavaScript and rename the item programatically.

**Comment by McShelby** [comment]
With the upcoming release 5.24.0, you will be able to set the displayed name of a theme variant. This is already commited to main.
