### ISSUE TITLE
Unable to build: layout/partials/header.html:121: function "break" not defined

### ISSUE THREAD

**Issue by usr-redacted** [McShelby/hugo-theme-relearn#356]
**operating system**: Ubuntu 22.04.1 LTS

**hugo version**: hugo v0.92.2+extended linux/amd64 BuildDate=2022-02-23T16:47:50Z VendorInfo=ubuntu:0.92.2-1

**command**: hugo -D

**expected behavior**: hugo builds successfully using this theme cloned into themes directory

**observed behavior**: 
```
WARN 2022/10/25 21:23:49 Module "hugo-theme-relearn" is not compatible with this Hugo version; run "hugo mod graph" for more information.
Error: add site dependencies: load resources: loading templates: "<dir>/themes/hugo-theme-relearn/layouts/partials/header.html:121:1": parse failed: template: partials/header.html:121: function "break" not defined
```

**Comment by McShelby** [comment]
You are using an unsupported Hugo version. The theme requires at least Hugo 0.95.0.

**Comment by usr-redacted** [comment]
For others that may end up here: do not rely upon `apt` repository as it is likely not sufficiently up-to-date.
