### ISSUE TITLE
theme: fix overflowing issue with anchors and tooltips

### ISSUE THREAD

**Issue by robzwolf** [McShelby/hugo-theme-relearn#364]
Hi, thanks for this fork.

On mobile, some of our pages can be scrolled to the right slightly as the anchors overflow horizontally depending on the exact width of the heading text.

If I permanently hide the anchors by adding `display: none` to the `.anchor` rule, the page can no longer be scrolled to the right. It looks to me like the anchor widens the page because it sits directly at the end of the header on the same line.

Here's a screenshot, using the Chrome emulator (although the issue is the same on actual mobile), of the anchor flowing over the edge of the page:
![image](https://user-images.githubusercontent.com/5098748/199485056-f8b1c3c6-3b9a-44f3-a3bd-b779837c1115.png)

Any ideas? :)

**Comment by McShelby** [comment]
Thanks for reporting, I'll take a look into this.

**Comment by McShelby** [comment]
I can not reproduce it with a condensed example. 

Make sure, there isn't any other element cause the overflow (like eg. long URLs) or even better: post your markdown content here.

![grafik](https://user-images.githubusercontent.com/11670870/200038015-6a41a1a3-9ec6-4e47-978d-9d4715d847d8.png)

**Comment by robzwolf** [comment]
Thanks for looking into this @McShelby. I can recreate the issue using the following markdown:

```md
---
title: "Maternity Leave and Maternity Pay"
menuTitle: "Maternity"
---

### Dictumva riu Lectusqui Nante

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet lectus ut est vulputate maximus et id ipsum. Ut augue ex, consectetur in lectus ac, facilisis molestie est. Aenean quis eros quis sem porttitor aliquam eget at leo. Duis neque metus, ultricies id elementum in, bibendum eget diam.

### Aliquam cursus massa euismod venenatis elit

Sed in diam felis. Aenean pulvinar nunc eget finibus ultricies. Nunc euismod venenatis elit, eget semper ex placerat ut. Aenean viverra felis ut dapibus bibendum. Sed viverra tempus urna et blandit. Nullam dictum enim sit amet pellentesque tincidunt. Donec ut gravida ipsum, sit amet egestas sem. Cras dignissim lobortis urna.
```

# When the Heading Wraps
However, I found that the issue does **not** appear at width `329px` (like in your screenshot). In my case, the issue is only present for widths between `396px` and `403px` (inclusive). Below `396px`, the heading `Dictumva riu Lectusqui Nante` wraps onto two lines:
![image](https://user-images.githubusercontent.com/5098748/200287981-743a441b-c4d1-43a8-823a-c6c13b81ac3f.png)

# When the Heading Wraps and the Anchor Fits Okay
...and above `403px` there is enough space for the anchor to be present without causing horizontal scrolling:
![image](https://user-images.githubusercontent.com/5098748/200288055-f596f170-9925-41d8-8a74-73c0e8645470.png)

# When the Heading Wraps and the Anchor Does Not Fit
You can see how at `403px` (`1px` narrower than in the previous screenshot) the anchor is slightly cropped to the right (and it becomes more cropped as the width narrows) and a horizontal scrollbar appears at the bottom:
![image](https://user-images.githubusercontent.com/5098748/200288478-3cad23ae-46f6-4ae8-90a1-1617db06183b.png)

Thanks for your assistance!

**Comment by McShelby** [comment]
To align the anchor icon with the rest was the easy part.

Additionally fixed with this issue is overflow scrolling when a tooltip was displayed either by the anchor icon or the copy-to-clipboard icon of inline code. For this to work, the tooltips are now attached with their right corner to the icon instead of being centered.

**Comment by robzwolf** [comment]
Thank you so much @McShelby :D
