### ISSUE TITLE
docs: clarify where to put self-defined variant stylesheets

### ISSUE THREAD

**Issue by denispeyrusaubes** [McShelby/hugo-theme-relearn#366]
Hi,

I've created and downloaded a new css style sheet using the Stylesheet generator.
Its filename is `theme-rtg-variant.css`.
In config.toml, i have modify the following entry to use this new style sheet :

```
[params]
  # Change default color scheme with a variant one.
  themeVariant = [ "rtg-variant" ]
```

But it is not used by Hugo. Where should I I put this `theme-rtg-variant.css` file ?

Thanks !

**Comment by McShelby** [comment]
The file belongs into the directory `static/css` **of your installation** (not to be confused with `themes/hugo-theme-relearn/static/css` where all the build in variants reside).

I will clarify the documentation.
