### ISSUE TITLE
tags: fix non-latin tag display on pages

### ISSUE THREAD

**Issue by kultpro** [McShelby/hugo-theme-relearn#378]
Cyrillic tags are not displayed on the page

It started a few updates ago

**Comment by McShelby** [comment]
Could you print your page's content here?

**Comment by kultpro** [comment]
config.toml

`baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "hugo-theme-relearn"

[outputs]
home = [ "HTML", "RSS", "SEARCH"]`

**Comment by McShelby** [comment]
Fixed. Thanks for reporting.
