### ISSUE TITLE
variant: minor color adjustments

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#402]
Some minor style adjustments

- we can now control values for h1
- fix some IE fallbacks
- fix search box subtleties
- adjust home link colors

**Comment by m0ddixx** [comment]
What's the intention behind this?

https://github.com/McShelby/hugo-theme-relearn/blob/8569a64c2b15164a08717b9ea1d6af05f69cdbbb/static/css/theme.css#L115-L119

Are there any issues with changing it to the `--MENU-SEARCH-color` variable? Therefore if you have a white background, you can adapt to the text colors used for the rest of the search box.

For example, the icons and placeholder wont change according to `--MENU-SEARCH-color` nor `--MENU-SEARCH-border-color`
![grafik](https://user-images.githubusercontent.com/6460402/214029785-8dc421e3-facb-4ea5-9c30-7849e039a98c.png)

**Comment by McShelby** [comment]
You are right. This was not as intended as the documentation clearly states that `--MENU-SEARCH-color` is used for icons and text color.

I've made a new issue #437
