### ISSUE TITLE
theme: fix alias for home page if defaultContentLanguageInSubdir=true

### ISSUE THREAD

**Issue by hugograf** [McShelby/hugo-theme-relearn#414]
After the command `hugo server` the following happens for my bilingual website:
```
Watching for changes in C:\SoftwareProjekte\Hugos\gt-user-manual\{archetypes,content,data,layouts,static,themes}
Watching for config changes in C:\SoftwareProjekte\Hugos\gt-user-manual\config.toml, C:\SoftwareProjekte\Hugos\gt-user-manual\themes\hugo-theme-relearn\config.toml
Environment: "development"
Serving pages from memory
Web Server is available at http://localhost:1313/gt-user-manual/ (bind address 127.0.0.1)
```
If the URL "http://localhost:1313/gt-user-manual/ " is taken over into the webbrowser, the result depends on the release of the template:
- Before release 5.6.4 it gets redirected to `http://localhost:1313/gt-user-manual/de/`
- Since release 5.6.4 it gets redirected to: `http://localhost:1313/de/index.html` -> `404 page not found`.

**Comment by McShelby** [comment]
Do you have a public repo?

Otherwise I need your `config.toml`, the command you use for starting your project + the current working directory and the file structure of your Hugo project.

**Comment by hugograf** [comment]
Hello

 

Yes, it is https://github.com/grafioschtrader/gt-user-manual

 

Best regards

 

Von: Sören Weber ***@***.***> 
Gesendet: Freitag, 9. Dezember 2022 10:02
An: McShelby/hugo-theme-relearn ***@***.***>
Cc: Hugo Graf ***@***.***>; Author ***@***.***>
Betreff: Re: [McShelby/hugo-theme-relearn] Since Release 5.6.4 the redirection for the base site may not work as expected (Issue #414)

 

Do you have a public repo?

Otherwise I need your config.toml, the command you use for starting your project + the current working directory and the file structure of your Hugo project.

**Comment by McShelby** [comment]
That was a tricky one.

The reason we overwrite the default `alias.html` is to support the `file://` protocol. This only works with relative links that are not natively provided by Hugo in this case.
