### ISSUE TITLE
theme: open external links in separate tab

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#419]

**Comment by McShelby** [comment]
Based on PR #418

**Comment by ripienaar** [comment]
Is this a feature that can be disabled? It’s quite an annoying change to have on by default

**Comment by McShelby** [comment]
It now is -> #426

**Comment by ripienaar** [comment]
Thanks so much @McShelby love that this theme is maintained again

**Comment by McShelby** [comment]
Thanks for the kind words. If you want to support the theme, I am happy if you "star" it :-)
