### ISSUE TITLE
attachments: fix incorrect links for defaultContentLanguageInSubdir=true

### ISSUE THREAD

**Issue by ajeans** [McShelby/hugo-theme-relearn#425]
Hello,

I configured my site with an exotic option :-)

```
  "defaultContentLanguageInSubdir": true,
```

All my URLs are prepended with a `/en/` language code.

This usually works fine, but the `attachments` shortcode creates links that do not contain the language code and simply reply with "Page Not Found'.
One such generated link is `http://localhost:1313/sdks/backend/java/security.en.files/application.yml`, whereas the attached file is available at `http://localhost:1313/en/sdks/backend/java/security.en.files/application.yml`.

I found out that I could fix this for my use case with the following change. Would it make sense to have this change in the theme?

```
--- themes/hugo-theme-relearn/layouts/partials/shortcodes/attachments.html	2022-12-22 19:34:22.252790204 +0100
+++ themes/quicksign/layouts/partials/shortcodes/attachments.html	2022-12-22 19:32:16.047510461 +0100
@@ -42,7 +42,7 @@
         {{- $unit = "Megabyte-symbol" }}
       {{- end }}
       {{- $unitsymbol := $unit | T }}
-    <li><a href="{{ (printf "%s%s/%s" $fileLink $filesName .Name) | relURL }}">{{.Name}}</a> ({{$size}} {{$unitsymbol}})</li>
+    <li><a href="{{ (printf "%s%s/%s" $fileLink $filesName .Name) | relLangURL }}">{{.Name}}</a> ({{$size}} {{$unitsymbol}})</li>
     {{- end }}
   {{- end }}
   </ul>
```

Best,
Arnaud

**Comment by McShelby** [comment]
The non-standard conformant way the attachments shortcode was implemented (see #22 for plans to fix this) leads to some quirks.

Eg. Hugo stores the attachments only for leaf bundles in their corresponding language subdirectory (plus also storing them in the subdirectory of the default language). All other page types store the attachments only in the subdirectory of the default language.

So our generated links always have to point into the subdirectory of the default language.
