### ISSUE TITLE
search: apply dependency scripts for Hindi and Japanese

### ISSUE THREAD

**Issue by deffence1776** [McShelby/hugo-theme-relearn#427]
## problem
Hi. When I set language as 'ja',  I met a  error below.

```
Uncaught TypeError: e.TinySegmenter is not a constructor
    at lunr.ja.min.js?1671879192:1:673
    at lunr.ja.min.js?1671879192:1:111
    at lunr.ja.min.js?1671879192:1:120
```

lunr.ja.js seems to require tinyseg.js.

 https://github.com/MihaiValentin/lunr-languages

## solution
On the local machine.

I added tinyseg.js
```
static/js/tinyseg.js
```

 and changed search.html
```search.html
        {{- range $contentlangs }}
            {{ if eq . "ja"}}
        <script src="{{"js/tinyseg.js" | relURL}}{{ if $assetBusting }}?{{ now.Unix }}{{ end }}" defer></script>
            {{end }}
          {{- $file := (printf "js/lunr.%s.min.js" .) }}
        <script src="{{ $file | relURL}}{{ if $assetBusting }}?{{ now.Unix }}{{ end }}" defer></script>
        {{- end }}
```

It works.

**Comment by McShelby** [comment]
You are correct.

I haven't tested the above mentioned languages but thought, it's enough to copy all *.min files from the release over into the theme.

Sadly, `tinyseg.js` (required for ja) and `wordcut.js` (required for hi and th) are missing from this folder. I actually don't understand why that is. While the requirement of `tinyseg.js` is hidden deep inside the source files, the requirement for `wordcut.js` isn't mentioned at all and can only be seen in the test files.

I would recommend to file an issue in the [lunr-languages](https://github.com/MihaiValentin/lunr-languages) repository.

For now, copy the missing files over to your themes `static/js` folder and add them into your `layouts/partials/custom-header.html`.
