### ISSUE TITLE
print: fix image links with relative path

### ISSUE THREAD

**Issue by FabianSuter** [McShelby/hugo-theme-relearn#444]
Thanks alot for your theme, it helps us alot.

We use relative links in our project and put our pictures in subfolders of each folder. This way it is easier to link each picture. Unfortunately it breaks these pictures when we click the "print"-button on the top right corner.

Are we doing something wrong or is this a bug?

https://pamasol.github.io/en/index.print.html
![image](https://user-images.githubusercontent.com/78728112/214644099-8f361b40-de79-473e-a900-3b834fd1da34.png)

![image](https://user-images.githubusercontent.com/78728112/214644127-1b259589-339a-4b0e-8153-e2d95d8809f6.png)

**Comment by McShelby** [comment]
This is a bug and got broken in 5.6.0 #385.
