### ISSUE TITLE
edit: remove double slash on root page link

### ISSUE THREAD

**Issue by ecesarini** [McShelby/hugo-theme-relearn#450]
Hi,
I'm running **Relearn** theme and i really like it.
My _config.toml_ configuration is pretty similar to the example of the _Relearn_ doc.
I'm linking any _edit_ to my gitlab repo web IDE, but there's a little problem when someone try to click the _edit_ button from the home page.
Setting `editURL=<my-repo-web-ide>/content/` the redirect link will append an `/_index.md` slug to the URL (e.g. `<my-repo-web-IDE>/content//_index.md`).
So in the web IDE, you'll find a new nameless folder containing an empty  `_index.md` file and any commit will fail if you don't manually delete this folder.
The same beahaviour happens if you try to edit [Relearn home page](https://mcshelby.github.io/hugo-theme-relearn/index.html) by _edit button_ https://github.com/McShelby/hugo-theme-relearn/edit/main/exampleSite/content//_index.en.md.

Is there a way to avoid this or hide edit button in the main page?

Thank you very much

**Comment by McShelby** [comment]
I may not get the point with this, yet. Pressing the edit button on the Relearn home page works as well as pressing the edit link in your issue description - although it's using a double `/`. Tested with FF and Chrome on Windows 11.

Could you provide a public link to your page?

**Comment by McShelby** [comment]
I've fixed the double slashes for the root page link. Not sure if this helps you.

If there will still be problems with this, please open a new issue.
