### ISSUE TITLE
next/previous controls are not working with customized `single.html`

### ISSUE THREAD

**Issue by Ravenwater** [McShelby/hugo-theme-relearn#461]
I have a multi page site that I would like to navigate with the next/previous controls in the page. For unknown reasons, it only works from the chapter to the first page, subsequent pages do not connect to the controls:

![image](https://user-images.githubusercontent.com/466641/216102960-cad126f2-3238-4f4a-96b5-933db422d156.png)

What am I doing wrong?

P.S. one can observe the behavior here: https://stillwater-sc.github.io/domain-flow/introduction/

**Comment by McShelby** [comment]
For now, the best way is, to change your `layouts/_default/single.html` to:

````
{{- partialCached "page-meta.hugo" . .RelPermalink }}
{{- $outputFormat := partial "output-format.hugo" . }}
{{- partial "output-partial.hugo" (dict "base" "header" "page" . "parameter" . "outputFormat" $outputFormat) }}
{{- if not .File }}
  {{- partial "output-partial.hugo" (dict "base" "body" "page" . "parameter" (dict "page" . "content" (partial "output-partial.hugo" (dict "base" "initial" "page" . "parameter" . "outputFormat" $outputFormat))) "outputFormat" $outputFormat) }}
{{- else }}
    {{ if .Params.WebGLRenderTarget }}
        {{ if .Params.SpacetimeVisualization }}
            {{ partial "spacetime.html" . }}
        {{ end }}
        {{ if .Params.IndexSpaceVisualization }}
            {{ partial "indexspace.html" . }}
        {{ end }}
        {{ if .Params.FreeScheduleVisualization }}
            {{ partial "freeschedule.html" . }}
        {{ end }}
        {{ if .Params.LinearScheduleVisualization }}
            {{ partial "linearschedule.html" . }}
        {{ end }}
        {{ if .Params.WebGLAnimation }}
            {{ partial "webgl.html" . }}
        {{ end }}
    {{ end }}
  {{- partial "output-partial.hugo" (dict "base" "body" "page" . "parameter" (dict "page" . "content" (partial "output-partial.hugo" (dict "base" "content" "page" . "parameter" . "outputFormat" $outputFormat))) "outputFormat" $outputFormat) }}
{{- end }}
{{- partial "output-partial.hugo" (dict "base" "footer" "page" . "parameter" . "outputFormat" $outputFormat) }}
````

**Comment by Ravenwater** [comment]
@McShelby that worked:

![image](https://user-images.githubusercontent.com/466641/216343290-a44166a0-54d2-47c1-afd6-96fad44d1c20.png)

But it also highlights the fact that I don't understand how the layout/partials anymore. Is layouts/partials/content.html now the default single page layout spec?

**Comment by McShelby** [comment]
For the theme's documentation there is definetly room for improvement on how to customize certain partials.

In your specific case a call to `page-meta.hugo` at the beginning of your `single.html` was missing. This is done internally for the shipped partials. Using `content.html` in your case frees you from that burden and also asserts that you can use the integrated "print chapter" feature, as this collects the content of several pages and puts it into one document.

**Comment by Ravenwater** [comment]
thank you for thinking ahead on the "print chapter" feature, definitely want that!

Thank you for your insights, this theme is magnificent!
