### ISSUE TITLE
theme: explore optimization for huge screen sizes

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#466]
On huge screens (width > 1500px (dpr-adjusted)), the layout gets difficult to capture and read. We can do better by leveraging the additional space.

https://css-tricks.com/optimizing-large-scale-displays/

**Comment by McShelby** [comment]
For now, we made sizing proportional to the initial font size. 

By just giving a new font-size to the `html´ element, the whole site will adapet.

````css
html{
  font-size: 24px;
}
````

**Comment by tdavetech** [comment]
> For now, we made sizing proportional to the initial font size.
> 
> By just giving a new font-size to the `html´ element, the whole site will adapet.
> 
> ```css
> html{
>   font-size: 24px;
> }
> ```

Hello! Where can I add this?

**Comment by McShelby** [comment]
https://mcshelby.github.io/hugo-theme-relearn/configuration/customization/extending/index.html#adding-javascript-or-stylesheets-to-all-pages
