### ISSUE TITLE
Theme is not completely responsive on mobile device. 

### ISSUE THREAD

**Issue by Prakash4844** [McShelby/hugo-theme-relearn#474]
The theme is responsive when I view pages, but when i open side menu, it become unresponsive. Please see screenshot to better understand. 

My device Have Display Resolution 
2400 x 1080, device is Poco X3 Pro, and I am on Kiwi Browser. 

![Screenshot_2023-02-11-08-21-32-209_com kiwibrowser browser](https://user-images.githubusercontent.com/81550376/218235397-1dedd827-62a9-46de-af6e-512f57bed70e.jpg)
![Screenshot_2023-02-11-08-21-25-002_com kiwibrowser browser](https://user-images.githubusercontent.com/81550376/218235399-94837c5f-7736-41d8-a933-b743dfa3fd5a.jpg)
![Screenshot_2023-02-11-08-21-20-106_com kiwibrowser browser](https://user-images.githubusercontent.com/81550376/218235402-7d17c284-0a29-4471-b577-39bcbabd9527.jpg)
![Screenshot_2023-02-11-08-21-17-786_com kiwibrowser browser](https://user-images.githubusercontent.com/81550376/218235404-5cdd65ae-0109-4eca-b41b-516d68d3e964.jpg)
![Screenshot_2023-02-11-08-21-14-747_com kiwibrowser browser](https://user-images.githubusercontent.com/81550376/218235405-86a93fe9-714b-445e-b266-43f7cd15cc7c.jpg)
![Screenshot_2023-02-11-08-21-12-264_com kiwibrowser browser](https://user-images.githubusercontent.com/81550376/218235406-2a9f893d-c786-414f-91b8-f730209f32e5.jpg)

**Comment by McShelby** [comment]
I can not reproduce this issue on a Nokia 7.2 with Android 11. Neither with Chrome 110.0.5481.63 nor Firefox 109.2.0.

Also a iPhone 8 with iOS 16.1.2 and Chrome or Safari has no problems.

This must be specific to your Kiwi browser. Please test with a different browser.

**Comment by Prakash4844** [comment]
Thanks, Checked on Firefox Nightly, No issue there, it is specific to kiwi browser.
