### ISSUE TITLE
responsive: click not recognized on iPhone XS

### ISSUE THREAD

**Issue by icifra** [McShelby/hugo-theme-relearn#478]
When using your documentation site on a mobile device, I noticed that landing pages from the sidebar didn't click through the first time.

Those. when you open the sidebar, when you open the menu and click on a certain page - it does not open immediately (there is no response), when you click again - there is already a transition.

I wonder if this is fixed?
... or these are the features of Hugo himself (I have already met this on other topics).

**Comment by icifra** [comment]
I am seeing this issue on Iphone XS with all the latest updates. It is worth noting that this problem was also on one other theme of Hugo.

Users give feedback on this possible issue, please

**Comment by McShelby** [comment]
Would be interesting to hear which other theme also showed this behavior.

Anyway without a physical device it may be near impossible to find out the reason and fix it.

**Comment by hvddrift** [comment]
I have also found this issue. You need to as described above click twice on any menu to open a page on IPhone Mini, IPad M2, IPhone 11 etc. The common culprit is safari. When I tested it on Chrome on my iPad I found that it works as intended.

**Comment by McShelby** [comment]
Does the `expand` shortcode behave the same?

**Comment by hvddrift** [comment]
Just tested and no, they expand and collapse with first touch/click

**Comment by McShelby** [comment]
@hvddrift What iOS and browser version are you using?

**Comment by hvddrift** [comment]
17.0.2

**Comment by McShelby** [comment]
And the Safari version?

**Comment by hvddrift** [comment]
I have looked and looked, but it they say its the same as the IOS version, so 17

**Comment by McShelby** [comment]
Ok. Thanks

**Comment by McShelby** [comment]
@hvddrift Is this still the case with the latest theme update?

**Comment by hvddrift** [comment]
Trying to get the update to work. Will test when as soon as I get it going.
