### ISSUE TITLE
mermaid: zoom is broken

### ISSUE THREAD

**Issue by airsiena** [McShelby/hugo-theme-relearn#479]
To be on the safe side, I reread Relearn's [instructions](https://mcshelby.github.io/hugo-theme-relearn/shortcodes/mermaid/index.html) on how to use Mermaid and rechecked my configuration, but it seems to me that zoom no longer works in the latest version of the theme.

**Comment by McShelby** [comment]
This was turned off by default in [5.11.0](https://mcshelby.github.io/hugo-theme-relearn/basics/migration/index.html) but you can turn it back on.
