### ISSUE TITLE
anchor: fix link in FF when served from filesystem

### ISSUE THREAD

**Issue by mnissl** [McShelby/hugo-theme-relearn#482]
In `static\js\theme.js`, function `initAnchorClipboard()` creates the link for a heading that can be copied into clipboard.

In line 264, `document.location.origin` and `document.location.pathname` are concatenated to build the URL. Alas, `origin` is null in Firefox which represents a ten year old [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=878297).

But there's an easy workaround available: `document.location.href` is the result when concatenating the two other properties. So line 264 could simply consist of this:

`var url = encodeURI(document.location.href);`

**Comment by McShelby** [comment]
I will take a look into it. Sadly it may be not that easy as `document.location.href` may also contain the fragment specifier which we explicitly don't want to have here.

**Comment by McShelby** [comment]
Thanks for reporting. This is now fixed
