### ISSUE TITLE
menu: allow toc as subentries of active item

### ISSUE THREAD

**Issue by micw** [McShelby/hugo-theme-relearn#491]
Hello,

I have large content pages where I'd like to have the h1 captions as menu items (with link to anchor). To implement this with minimal impact to the theme, I thought about adding the logic to a partial that is within any menu item that is "active".

I'd change menu.html like tat:

```
          <li data-nav-id="{{.RelPermalink}}" title="{{.Title}}" class="dd-item{{if $isActive }} active{{end}}"><a href="{{.RelPermalink}}">
              {{- partial "menu-pre.html" . }}{{ or .Params.menuTitle .LinkTitle .Title }}{{ partial "menu-post.html" . }}
              {{- if $showvisitedlinks }}<i class="fas fa-check read-icon"></i>{{ end }}</a>
              {{if $isActive }}
                {{ partial "menu-active-extra.html" . }}
              {{end}}
          </li>
```

If you like the idea, I'd add a pull request to add the feature plus an example in the documentation.

**Comment by McShelby** [comment]
That's an interesting use case. There is another issue #148 that names a quite different scenario related to generation of the menu.

Your topic is also related to the toc generation (discussed in #167), which currently is quite inflexible (levels of headings to display in the toc, where to display the toc, etc.)

I am also willing to add official support for this feature but currently have no timeline for this.

At the moment (coming with 5.12.0) I am rewriting the menu generation in terms of the collapsible menu feature. This also will make it easier to add future features related to the menu. So let's finish this first and see how we can improve on this.

**Comment by micw** [comment]
Alright, thank you for the feedback. I have pushed my intermediate solution to https://github.com/brick4u/hugo-theme-relearn/tree/b4u-custom for those who might need it. The content of my menu-active-extra.html is:

```
<ul>
{{ range (findRESubmatch `(?s)<h2 id="(.*?)">(.*?)</h2>` .Content) }}
    <li class="dd-item"><a href="#{{ index . 1 }}">{{ index . 2 }}</a></li>
{{ end }}
</ul>
```

This makes all h2 of the current page visible as submenu items. One open point is to highlight the current one. Our frontend/css people will have certainly a look on that (maybe it's as easy as described in https://www.tutorialspoint.com/Style-to-highlight-active-HTML-anchor-with-CSS).

**Comment by McShelby** [comment]
How would you expect the menu to look like if the page has sub pages and a toc?

**Comment by micw** [comment]
A very good questions. I'd say it is mutually exclusive.

**Comment by McShelby** [comment]
Hm, not quite intuitive. Probably another item for configuration.

**Comment by McShelby** [comment]
@micw: changes to the menus html and css structure are now pushed to main

**Comment by McShelby** [comment]
While sounding like a nice feature in the beginning, I decided against it. Reasons:

- besides showing a toc I can not think of other valueable use cases
- if used for the toc, this should be baked into the theme, making a hook partial obsolete
- if other use cases are possible, one hook may not be enough causing the code to be littered by a lot of additional hooks, this comes with a complexity cost for documentation
- displaying the toc for section pages will mix up with subsections requiring a distinguishable way to differ both types of subitems
- to display the expander for non-active pages is too expensive while not displaying it results in non deterministic behavior for the user

That said, the toc should not be mixed with menu entries but should be displayed somewhere else. While currently there is only the toc overlay accesible from the topbar, this may be extended in future releases.
