### ISSUE TITLE
mermaid: update to 10.2.0

### ISSUE THREAD

**Issue by meredrica** [McShelby/hugo-theme-relearn#499]
Hello!

Mermaid is still on version `9.2.2`, latest is `10.0.2`. Is it possible to upgrade it easily?
An easy fix is to include 
```html
<script type="module">
import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10.0.2/+esm'
</script>
```
in the footer partial but that's using a CDN and i don't know what it will break inside the theme.

**Comment by McShelby** [comment]
Mermaid >= 10 only supprts ESM. As long as the theme still supports Internet Explorer 11, this would break.

So we are currently locked to Mermaid < 10.

**Comment by McShelby** [comment]
Well, just today, Mermaid 10.2.0 was released, reintroducing [UMD support](https://github.com/mermaid-js/mermaid/pull/4281) which makes `mermaid.min.js` available again.

So it is just need to check for the initialization before we can bump.
