### ISSUE TITLE
image formatting: how to use relative width/height?

### ISSUE THREAD

**Issue by cagix** [McShelby/hugo-theme-relearn#500]
According to https://mcshelby.github.io/hugo-theme-relearn/cont/markdown/#resizing, the query parameters `width` and/or `height` can be appended to the image URL. 

Coming from Markdown -> LaTeX, I'd like to use a relative width like `width=20%`. Testing with `![](images/wuppie.png?width=20%)` results in no resizing. What am I missing?

**Comment by McShelby** [comment]
Because it's an URL, you have to URL-encode the percentage sign like

````markdown
![Minion](https://octodex.github.com/images/minion.png?width=20%25&classes=bg-white)
````

I would recommend to better use `vw` as this is easier to write.

**Comment by cagix** [comment]
> 
> I would recommend to better use `vw` as this is easier to write although resulting in slightly different behavior.

ps: "vw" isn't a real option for me: i have some pandoc-markdown documents, which are transformed via pandoc and latex to pdf. that's the reason all sizes are relative to the page size. the same documents are preprocessed w/ pandoc (to markdown) and used w/ hugo and the relearn-theme to produce a learning website. using % is easier for me as i'd have to recalculate % to vw somehow otherwise...

wanted to say thank you for your amazing work!

**Comment by McShelby** [comment]
> i knew i was missing something

Honestly, I ran intothe same issue when I tested it ;-)
