### ISSUE TITLE
expand: not properly exanded when used in bullet point list

### ISSUE THREAD

**Issue by cagix** [McShelby/hugo-theme-relearn#508]
When I use the `expand` shortcode in an itemize environment, it does not resolve correctly:

```markdown
-   Mit welchen Methoden/Iteratoren kann man alle Elemente eines
    Arrays sammeln, die bestimmten Bedingungen (nicht) genügen?

    {{% expand "Show Me" %}}
    `find_all`, `reject`
    {{% /expand %}}

Mit welchen Methoden/Iteratoren kann man alle Elemente eines
Arrays sammeln, die bestimmten Bedingungen (nicht) genügen?

{{% expand "Show Me" %}}
`find_all`, `reject`
{{% /expand %}}
```

This will be translated to HTML shown in the following screenshot: 

1. closed: <img width="922" alt="Screenshot 2023-03-28 at 14 27 58" src="https://user-images.githubusercontent.com/20356276/228236047-372e197c-8010-46d4-97da-1092932652d8.png">
2. opened: <img width="922" alt="Screenshot 2023-03-28 at 14 28 11" src="https://user-images.githubusercontent.com/20356276/228236085-a5edc37f-35cd-4e7b-be86-fb33db343e16.png">

As long as the shortcode is in the normal text (paragraph), everything works just fine. As soon as I want to have an expandable element within an enumeration environment, the content of the shortcode gets interpreted as code block?

**Comment by McShelby** [comment]
I am sure, I can do something about this ;-)

**Comment by McShelby** [comment]
Thanks @cagix. You're my "gold user" ;-)

**Comment by cagix** [comment]
@McShelby Thanks for the super fast fix! Also, thanks a lot for your great work on this nice theme!

I don't think the fix works fully yet. The closed shortcode is displayed correctly now, but the content is still interpreted as a code block when using the shortcode in an enumeration. (see screenshot)

<img width="922" alt="Screenshot 2023-03-28 at 20 26 23" src="https://user-images.githubusercontent.com/20356276/228333149-5a782c94-f135-4976-b83a-2ca3b8a95e6c.png">

This was my markdown source:

```markdown
**Länge einer Liste**

-   Wie kann man die Länge einer Liste berechnen?

    {{% expand "Show Me" %}}

    ``` prolog
    len([], 0).
    len([_|L], N) :- len(L,X), N is X + 1.
    ```

    {{% /expand %}}
    {{% expand "Show Me" %}}

    ``` prolog
    len([], A, N)    :- N = A.
    len([_|L], A, N) :- A2 is A + 1, len(L,A2,N).
    ```

    {{% /expand %}}

-   Erklären Sie den Unterschied der beiden Vorschläge!
```

**Comment by McShelby** [comment]
Shortcodes have their limitations as they are not "first-class Markdown citizens".

The Markdown parsing will start without any context of its surroundings for the expand content. Meaning: It does know nothing about its indention. Therefore, if you indent the code inside the expand by at least four spaces, it is treated as a indented code block.

To avoid that just remove the indention for the expand content. It looks ugly in the Markdown source but generates the desired result.

````
**Länge einer Liste**

-   Wie kann man die Länge einer Liste berechnen?

    {{% expand "Show Me" %}}
```prolog
len([], 0).
len([_|L], N) :- len(L,X), N is X + 1.
```
    {{% /expand %}}
    {{% expand "Show Me" %}}
```prolog
len([], A, N)    :- N = A.
len([_|L], A, N) :- A2 is A + 1, len(L,A2,N).
```
    {{% /expand %}}

-   Erklären Sie den Unterschied der beiden Vorschläge!
````

**Comment by cagix** [comment]
ah, i see, it's a hugo limitation. 

that's unfortunate because i'm using pandoc markdown and transpile it into a hugo compatible format (and also latex), and as of now i do not have quite an idea how to not indent the shortcode's content. hmmm, something to meditate on :) 

thanks again for your quick response and for this beautiful theme!
