### ISSUE TITLE
disableToc: true not working anymore in the page header

### ISSUE THREAD

**Issue by nroduit** [McShelby/hugo-theme-relearn#510]
It seems to be related [with #434 ](https://github.com/McShelby/hugo-theme-relearn/discussions/434)

It works for me when reverting  Pages by Sections in https://github.com/McShelby/hugo-theme-relearn/commit/0c10cc8af341bd6f6ce7da96c835c0b154162155#diff-b639e7e0de3fcdc004d7792650bfd77517fb49b45dfe1c1d626b63bb1c55b59d

**Comment by McShelby** [comment]
I've tried to reproduce your issue report to no avail.

I tried all combinations of setting `disableToc` to `true`, `false` or remove it completley form either the `config.toml` or in the frontmatter of a branch bundle, leaf bundle or simple page.

Every test worked as expected. I've used Hugo 0.110.0 with the latest release of the theme 5.12.5.

Could you give a link to an example source file?

**Comment by nroduit** [comment]
Thanks for your prompt answer. Here is the menu issue:

![image](https://user-images.githubusercontent.com/993975/230285074-44aa6088-ba4f-44aa-bd30-691d8b20665c.png)
Should be
![image](https://user-images.githubusercontent.com/993975/230285108-5183a8a4-094f-4e9a-9132-8e9a70d2d269.png)

I finally managed to fix the problem to hide the menu on some pages. In fact, I was using the wrong instruction to hide the menus. By replacing it with "hidden: true" it works correctly.

But I think there is a side effect with this change mentioned above because before all the root pages were hidden on the menu. You can still see it on my [site](https://nroduit.github.io/) which I haven't updated yet.

**Comment by McShelby** [comment]
Now I understand. This is not the TOC but the menu. And yes, `hidden=true` removes the links from the main menu section.

On the exampleSite of this theme, this is achieved differently with a Hugo technique called [headless bundle](https://gohugo.io/content-management/page-bundles/#headless-bundle) for the "Credits" and the "Showcases" page. Take a look into `exampleSite/content/more`.
