### ISSUE TITLE
theme: fix resource URLs for 404 page on subdirectories

### ISSUE THREAD

**Issue by tlindsay42** [McShelby/hugo-theme-relearn#515]
Just noticed that the pathing to the stylesheets and scripts doesn't work on the 404 page if hit from a subdirectory. Example: <https://mcshelby.github.io/hugo-theme-relearn/tags/bad-tag/index.html>

![image](https://user-images.githubusercontent.com/11078689/234876039-0fc5205b-f81b-44d6-b513-3e2a3ed04d84.png)

![image](https://user-images.githubusercontent.com/11078689/234876227-f012bb2a-6f01-43d6-8468-fded0de85af2.png)

**Comment by McShelby** [comment]
Thanks for reporting. This may take a while to fix - not because it is complicated but of my time constraints.

**Comment by tlindsay42** [comment]
Just upgraded & tested and everything looks good. Thanks @McShelby!
