### ISSUE TITLE
print: enable print for pages with _build options

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#522]
### Discussed in https://github.com/McShelby/hugo-theme-relearn/discussions/511

<div type='discussions-op-text'>

<sup>Originally posted by **cagix** April 18, 2023</sup>
I have some pages that should not be displayed in the menu because they are linked directly via the "More" section.

In order for them not to appear in the menu, even when I open these pages, I use the snippet
```
hidden: true
_build:
  render: always
  list: never
  publishResources: true
```
in the YAML header of these hidden pages (see also https://github.com/McShelby/hugo-theme-relearn/discussions/138).

When I click on the print icon in the open page, only an empty preview is displayed. How can I print these "hidden" pages nevertheless?

Edit: I've activated print support as shown in https://mcshelby.github.io/hugo-theme-relearn/basics/configuration/index.html#activate-print-support.</div>

**Comment by McShelby** [comment]
@cagix That was an interesting one.

It's now fixed but I want to share my insights:

To work as intended the _headless bundle_ **must** be a _branch bundle_ (meaning `_index.html`). No _page bundle_ (`index.html`) or simple page (`mypage.html`).

I've changed the `exampleSite` to show two different variants:

1. `more/credits/_index.html` The file itself is not a headless bundle but its parent `more/_index.html` is. This causes the credits to not appear in the menu but its **content is contained in the sitemap**.
2. `showcase/_index.html` This file itself is a headless bundle. This also causes the showcase to not appear in the menu but also **removes its content from the sitemap**.

As a note: For this behavior setting `hidden=true` in the frontmatter is **not necessary** (but you may have had other reasons to do that in the first place, I am not aware of).

**Comment by cagix** [comment]
@McShelby Thanks for looking into this! 

The `hidden=true` was an earlier attempt to hide pages from the menu and somehow I failed to remove that afterwards.

I do have an `_index.md` in all folders, but the actual pages are "simple pages", to make the structure easier to navigate in GitHub as well. So I have to see if I can turn the "simple pages" back into "branch bundles" in the build process.

**Comment by McShelby** [comment]
I will update the release notes for 5.9.0 were #434 now causes this change in behavior.

**Comment by cagix** [comment]
@McShelby I've only now been able to test your modifications in my setup - it now works perfectly! Thank you for your work and this great theme! ❤️
