### ISSUE TITLE
i18n: add translation for default taxonomies

### ISSUE THREAD

**Issue by postb99** [McShelby/hugo-theme-relearn#528]
Hello,

In addition to tags taxonomy, I configured categories taxonomy in my website, and copied layout/partials/tags.html to layout/partials/categories.html, replacing "tags" by "categories" and "tag" by "category".
Then I noticed than in French, we don't use the same word for "category" as in English, unlike "tag" where we also use "tag".

My question is about the pages that lists all pages of a given tag/category: the layout/partials/_taxonomy.html template is used. I would like to get the "tag"/"category" word present in title in my display language, so changed line 7 to the following, adding "i18n":

    {{- $title = printf "%s %s " (i18n .Data.Singular | humanize) (default "::" .Site.Params.titleSeparator) }}

Then in every .toml language file (I guess really in each...) I would need to declare a new term else there is no word displayed:

```
[category]
other = "catégorie"
[tag]
other = "tag"
```

Is this the right way to achieve what I'd like to do?

Thanks

**Comment by McShelby** [comment]
A few minutes ago, I also recognized this. Thanks for reporting.

I'll make the appropriate changes to the theme.

**Comment by postb99** [comment]
For the new feature to look nice, my life and coding partner @xarkam added the following to layout/partials/content-footer.html. This looks fine and allows a content item to belong to more than one category.

```
{{- $page := . }}
{{- if .Params.categories }}
<i class='fas fa-list'></i>
{{- range sort .Params.categories }}
  {{- $category := . }}
  {{- with $page.Site.GetPage (printf "%s%s" ("/categories/" | relURL ) ( $category | anchorize ) ) }}
    {{- $to := . }}
  <a class="tag-link" href="{{ partial "relLangPrettyUglyURL.hugo" (dict "to" $to) }}">{{ $category }}</a>
  {{- end }}
{{- end }}
{{- end }}
```

This visually gives this for my work-in-progress website:

![image](https://github.com/McShelby/hugo-theme-relearn/assets/173565/8766590c-d685-4885-8ce6-443f278b980d)

Just be careful about font awesome 5 vs 6 we use.

**Comment by McShelby** [comment]
The fix has landed in master, but I want to fix some stuff first before the next official release.

In the meanwhile you could check out the translation. I hope Google Translate and DeepL did their job well.

**Comment by postb99** [comment]
I just added a comment to the commit, great work with a small wording fix please for fr language.
