### ISSUE TITLE
How to adjust the width of sidebar？

### ISSUE THREAD

**Issue by worldawa** [McShelby/hugo-theme-relearn#539]
I found that my sidebar is too wide. If available, I hope add a button to hide and expand sidebar like view on the phone, or dynamically adjust sidebar.

**Comment by McShelby** [comment]
The width of the side bar is not adjustable but feel free to submit a proposal or PR

**Comment by worldawa** [comment]
I would like to request the addition of a parameter in the config.toml file that allows for customizing the width of the sidebar. Additionally, it would be great if an option could be added to display a button that allows users to expand and shrink the sidebar. Thank you for considering these enhancements.

**Comment by McShelby** [comment]
Making an adjustable sidebar is a lot of work and personally I don't see a positive value compared to the required work.

Making the hide/show switch of the mobile display available for deskop is not that much work but I don't see a use case either. On desktops you usually have a big screen an much available space. Hiding the menu is just not necessary here and requires additional controls overloading the content header.
