### ISSUE TITLE
attachments: fix build error since Hugo 0.112

### ISSUE THREAD

**Issue by raum51** [McShelby/hugo-theme-relearn#540]
Hi,
today I updated the theme and Hugo and got the followoing error message:

`
Error: error building site: "C:\Users\h35\_git\dokumentation\content\de\intern\produktion\schnittstellen\cloudapi\lely.md:85:3": failed to render shortcode "attachments": failed to process shortcode: execute of template failed: template: shortcodes/attachments.html:2:4: executing "shortcodes/attachments.html" at <partial "shortcodes/attachments.html" (dict "context" .Page "color" (.Get "color") "content" .Inner "icon" (.Get "icon") "pattern" (.Get "pattern") "style" (.Get "style") "sort" (.Get "sort") "title" (.Get "title"))>: error calling partial: "C:\Users\h35\_git\dokumentation\themes\hugo-theme-relearn\layouts\partials\shortcodes\attachments.html:35:44": execute of template failed: template: partials/shortcodes/attachments.html:35:44: executing "partials/shortcodes/attachments.html" at <.Language.ContentDir>: can't evaluate field ContentDir in type *langs.Language
`

I've tested this Hugo versions:
0.112.2 (latest version) ==> ERROR
0.112.0 ==> ERROR
0.111.3 ==> everything OK

Maybe it has to do something with the "Improved language config handling"
https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
https://github.com/gohugoio/hugo/releases/tag/v0.112.0
https://github.com/gohugoio/hugo/issues/10620)

**Comment by McShelby** [comment]
We see, what happens. https://discourse.gohugo.io/t/after-upgrade-to-0-112-page-language-contentdir-undefined/44528/3

Till then, the theme is only compatible up to Hugo < 0.112.0
