### ISSUE TITLE
taxonomy: add support for category default taxonomy

### ISSUE THREAD

**Issue by postb99** [McShelby/hugo-theme-relearn#541]
Hi there 🌞

Reading again this documentation page: https://mcshelby.github.io/hugo-theme-relearn/cont/tags/

Just thinking over, since Hugo supports tags and categories built-in taxonomies, and the theme nicely allows to display them as listings, and lately you improved the translations, why not thinking again of my proposal, listing an article's category in content footer.

Original discussion: https://github.com/McShelby/hugo-theme-relearn/issues/528#issuecomment-1553219859

My addition to content-footer.html partial layout:

```
{{- $page := . }}
{{- if .Params.categories }}
<i class='fas fa-list'></i>
{{- range sort .Params.categories }}
  {{- $category := . }}
  {{- with $page.Site.GetPage (printf "%s%s" ("/categories/" | relURL ) ( $category | anchorize ) ) }}
    {{- $to := . }}
  <a class="tag-link" href="{{ partial "relLangPrettyUglyURL.hugo" (dict "to" $to) }}">{{ $category }}</a>
  {{- end }}
{{- end }}
{{- end }}
```

Here with a single category listed after the font awesome icon:

![image](https://github.com/McShelby/hugo-theme-relearn/assets/173565/a9ea9592-f468-46d4-8a2c-a46b3e9155ba)

In hugo.toml something like this can be added:

```
        [[Languages.en.menu.shortcuts]]
            name = "<i class='fas fa-fw fa-list'></i> Categories"
            url = "/en/categories/"
            weight = 50
```

**Comment by McShelby** [comment]
You've convinced me. Categories are now officially supported.

I've polished the visuals by adding a separator between two categories in the list

Now in `main` coming officially in the next release.

**Comment by postb99** [comment]
![image](https://github.com/McShelby/hugo-theme-relearn/assets/173565/5135c109-835c-4dff-a38d-3043f4779880)
I really like how this looks with the separator, thank you very much
