### ISSUE TITLE
theme: update color values to rgba

### ISSUE THREAD

**Issue by Xarkam** [McShelby/hugo-theme-relearn#544]
Good morning,

I am currently having a problem with the internal css colors. I saw that some are in rgba and the other in hex.

My concern is that I want to change the style of the tags and I can't apply transparency on the default color because it's set to hex.

Currently the css4 standard is still in draft state. This means that it is not yet possible to use the hex to rgba transformation in browsers.

It would be interesting to have a uniformity of the variables in variant-internal.css in rgba rather than hexa as well as in the variants of the themes.

The idea is not to have to override hex variables in rgba.

<img width="1010" alt="image" src="https://github.com/McShelby/hugo-theme-relearn/assets/331816/13a8408c-d24f-4ece-b0ce-788e81c08f0d">

**Comment by McShelby** [comment]
I am open to PRs for it if you want to provide this but will not work on this for myself.

A better way would probably be, to add a new color variable for the tags and defaulting it to the secondary color.

By that you could create your own variant without changing the color by CSS rules. CSS rules may break at any time as the DOM is not ensured to be stable between releases.

**Comment by Xarkam** [comment]
I opened a PR but I've not make change in Neon theme. I make later the conversion.

**Comment by McShelby** [comment]
I've made further conversions to fix whitespacing and the neon variant.
