### ISSUE TITLE
The utteranc comments component is not displayed completely

### ISSUE THREAD

**Issue by zrcoder** [McShelby/hugo-theme-relearn#548]
I add a file `custome_comments.html` in layout/partials directory in my project, with the content below:

```html
<script 
    type="text/javascript"
    src="https://utteranc.es/client.js"
    repo="zrcoder/leetcode"
    issue-term="pathname"
    theme="github-light"
    crossorigin="anonymous"
    async>
</script>
```

the utteranc comments component shows on my pages, but not completely displayed when the content exceeds the screen.

reference: [utteranc](https://utteranc.es/)

**Comment by zrcoder** [comment]
May be utteranc's bug, I use [giscus](https://giscus.app/zh-CN) instead and it works well.
so I will close this issue.

**Comment by DavidVargasxyz** [comment]
> May be utteranc's bug, I use [giscus](https://giscus.app/zh-CN) instead and it works well. so I will close this issue.

Can you share your process for Giscus? I can't seem to get it to work.

**Comment by zrcoder** [comment]
> > May be utteranc's bug, I use [giscus](https://giscus.app/zh-CN) instead and it works well. so I will close this issue.
> 
> Can you share your process for Giscus? I can't seem to get it to work.

I used relearn theme 1.5 years ago in this project: https://github.com/zrcoder/leetcode, now I use another theme and forget the detail of discus using of relearn,  the commit diff maybe helpful (see layouts/partials/custom-comments.html): https://github.com/zrcoder/leetcode/commit/a594d0917d31fbffeab5172761ee1e22ca75af75#diff-5210641576dd8db535d63aed8df25ffefe22b7cdd19e30a5e913f47c0d39a9c9
