### ISSUE TITLE
icon: fix ouput "raw HTML omitted" with goldmark config unsafe=false

### ISSUE THREAD

**Issue by postb99** [McShelby/hugo-theme-relearn#555]
Hi,

I updated my copy of theme to latest main and we noticed that at least since June 1 the icon shortcode is stripped. Can you explain what's wrong?

![image](https://github.com/McShelby/hugo-theme-relearn/assets/173565/6aa320df-4d54-4184-a6eb-79df89b33b7d)

My article's code:

```
+++
title = "Photographie"
weight = 2
+++
[Photos et vidéos entre ciel et terre {{% icon icon="fa-brands fa-facebook" %}}](https://www.facebook.com/groups/216710605160181)
```

I tried variants such as putting icon shortcode after link, or even using html code such as <i class="fas fa-heart"></i>

Thanks for a clue

**Comment by McShelby** [comment]
Luckily this isn't contained in an official release yet but only available in the main branch.

I am not sure if this can be fixed easily or if I revert the causing changes in #547.

For a quick fix on your side, you could add this to your config/hugo.toml:

````toml
[markup]
  [markup.goldmark.renderer]
    unsafe = true
````

**Comment by McShelby** [comment]
I've reverted most of the changes
