### ISSUE TITLE
docs: improve structure and examples

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#567]
The structure has far outgrown its features. 

Usually you are searching for a specific thing to achieve like in a "How to" while the docs are more a sequential arbitrary sorted list of references.

By visually deconstructing the UI into smaller parts and providing more screenshots for the different config options, it should be easier for a user to discover information of interest

https://www.youtube.com/watch?v=qC1OYK5oqDo

**Comment by postb99** [comment]
Somthing that may currently be useful and not that long to implement: move paragraphs of Customization to children pages so that they can be easily browsed. https://mcshelby.github.io/hugo-theme-relearn/basics/customization/index.html

Does milestone 6.0.0 have any probable date set?

**Comment by McShelby** [comment]
Soon™

But with reduced features. The docs rework was dropped to speed things up. Anyways this is not off the table.

**Comment by McShelby** [comment]
While adding documentation for 7.0.0, it got evident that this issue need to be done now. Stay tuned.
