### ISSUE TITLE
DEPRECATED parameter 'name' for shortcode 'tab' found, use 'title' issue

### ISSUE THREAD

**Issue by rcastley** [McShelby/hugo-theme-relearn#568]
Evening,

Not a major issue, but seeing a lot of WARNINGS:

```
DEPRECATED parameter 'name' for shortcode 'tab' found, use 'title'
```

Search of the markdown for `name=` yields nothing (see attached screenshot)
<img width="1723" alt="image" src="https://github.com/McShelby/hugo-theme-relearn/assets/2493008/b82d64c7-2332-4ab8-b96a-1d413a8d4f7e">

Running `hugo v0.113.0` with the latest theme `hugo mod get -u`

Many thanks :-) (love this theme!!!)

**Comment by McShelby** [comment]
This does not happen with the exampleSite using similar code.

Could you share your code?

**Comment by rcastley** [comment]
@McShelby Sure - https://github.com/splunk/observability-workshop

Thank you for taking a look!

**Comment by McShelby** [comment]
Your Japanese translation is full of `tab name=`, easily discoverable by a search in your favorite text editor

**Comment by rcastley** [comment]
@McShelby Thank you and sorry!
