### ISSUE TITLE
siteparam: support nested parameters and text formatting

### ISSUE THREAD

**Issue by ChristopherBarrington** [McShelby/hugo-theme-relearn#590]
The shortcode currently looks for an index in `.Site.Params` but if the index is a map it cannot return a value from the map. If the user passes `name="group.key"` it should return the key value from the group map.

The following worked for me:

```html
{{ $context := .context }}
{{ $paramNames := split .name "." }}
{{ with $context }}
	{{ $params := .Site.Params }}
	{{ range $paramName := $paramNames }}
		{{ $params = index $params $paramName }}
	{{ end }}
	{{ markdownify $params }}
{{ end }}
```

worked for me. Though I had to use `markdownify` to get the text formatted as I wanted (my params has nested maps with markdown at the end) and the `{{<>}}` variant of the shortcode. It would be good to see the proper way to do what i surely butchered!

https://github.com/McShelby/hugo-theme-relearn/blob/main/layouts/partials/shortcodes/siteparam.html

**Comment by McShelby** [comment]
Thanks for submission.

Funnily enough I played with the thought to remove this shortcode entirely as I couldn't imagine a use case.

You've convinced me to keep it and make your proposed changes (while changing the implementation slightly).
