### ISSUE TITLE
mermaid: variant generator diagram does not respond to events

### ISSUE THREAD

**Issue by Sylphe88** [McShelby/hugo-theme-relearn#607]
I found the (fantastic on paper) generator tool does not work on any of my web browsers (Firefox, Chrome, Edge). Example - Firefox 116.0.2.
I've tried disabling browser security features but it's not that.

The Mermaid diagram is correctly rendered but no interaction are allowed. I still can edit the CSS on my own but that's terribly frustrating to miss that feature.

Cheers

**Comment by McShelby** [comment]
Thanks for the find.

This pesky bug was introduced in the Mermaid update to 10.3.0 in #603 #601. The latest released version of the theme (5.18.0) does not suffer from this bug. So until waiting for a bug fix, you could use this version instead.

**Comment by McShelby** [comment]
This one's fixed. Although I found another regression #608
