### ISSUE TITLE
disableNextPrev has no effect

### ISSUE THREAD

**Issue by Sylphe88** [McShelby/hugo-theme-relearn#619]
The disableNextPrev parameter in hugo.toml has no effect in this theme. The navigation buttons invariably stay in the header. 
It looks like the navigation was "simply" moved from the[ footer.html in the learn theme](https://github.com/matcornic/hugo-theme-learn/blob/e817f53d690d35f181c896e0e320cb40f797e88c/layouts/partials/footer.html#L8) to the header.

Is there a way to have the two navigation features work independently? I would either have the large navigation buttons in the content or both (in the content + header), but the header alone will not be enough (people won't see the buttons).

**Comment by McShelby** [comment]
I just checked the Relearn theme with the latest version and `disableNextPrev=true` works like a charm. This is something with your environment but without a look at your code, I can not help.

The Relearn theme evolved from the Learn theme. The location of the navigation buttons has been changed by intent in #151. The Learn behaviour is not available anymore.

**Comment by Sylphe88** [comment]
I see, then I guess the [option documentation](https://mcshelby.github.io/hugo-theme-relearn/basics/configuration/index.html) should be slightly changed for clarification (as the navigation arrows are not in full size next to the body):
![image](https://github.com/McShelby/hugo-theme-relearn/assets/10143177/fe0c8445-b5a6-4cff-8242-0d59aba06ed1)
