### ISSUE TITLE
theme: add support for AsciiDoc syntax highlightning

### ISSUE THREAD

**Issue by stratacast** [McShelby/hugo-theme-relearn#622]
I am in the process of moving some of my own docs to using Relearn. All my files are in asciidoc, and they all seem to render correctly except for admonitions (common with Hugo) and code syntax highlighting. In Asciidoc, you would have something like below to do syntax highlighting

```asciidoc
:source-highlighter: rouge
:rouge-style: molokai
```

This has worked with me for the themes I tried, but with relearn I get only white text. I'm guessing there's something I have to disable in relearn to make it cooperate with my external syntax highlighter?

**Comment by stratacast** [comment]
This took some Hugo wizardry to work out by adding this to `layouts/partials/custom-header.html`

with contents

```html
{{ range .Site.Params.custom_css -}}
    <link rel="stylesheet" href="{{ . | absURL }}">
{{- end }}
```

And in `[params]` add 

```toml
  custom_css = ["css/molokai.css"]
```

molokai.css is made by running ` rougify style molokai > static/css/molokai.css`

I'm not sure if there's some magic that can be done within the theme itself, but I got it working anyway

**Comment by McShelby** [comment]
I am not experienced with Asciidoc but your solution is a futureproof way to achieve this (in terms of this theme).

**Comment by stratacast** [comment]
Glad to hear. I appreciate the theme. I assume the couple themes I tried work because they come packaged with highlightjs and so when AsciiDoc gets converted to HTML, hightlightjs picks it up. But whatever Hugo is doing in the background doesn't work unless I include my own CSS. Hugo lets you use AsciiDoctor's built-in rouge support and passes the (sorry I'm not a CSS guy at all) CSS variables to the HTML tags, but since the CSS isn't there...and thus, I have to do what I did above.

I'm glad you make it easy for me to add my own partial layouts here. Thanks again for the cool theme that is easy to work with!

**Comment by McShelby** [comment]
Interesting read. Can you post a link to a page where those internals are explained? I took a quick look in Hugos forum but could not come up with something helpful.

Historically, in the past a lot of themes used highlightjs internally (I can only make assumptions why that was). Nowadays Hugo comes with its own syntaxhighlighter Chroma. Sadly, the Hugo docs don't mention any restrictions regarding AsciiDoc. So before your post I was in the impression Chroma would work regardless of the input format. Hm.

One of the first things I was changing when I forked this theme from Learn was to replace highlightjs with Hugos build-in Chroma highlighter in #32. Would be a pitty if this was an illformed decission.

**Comment by McShelby** [comment]
I have also done my fair part of research now (although I still don't understand the details).

Chroma was once (in 2017) meant to be a compatible replacement to pygments. So if you set `:source-highlighter: pygments` this maybe generates Chroma compatible styles? Just a wild hopeful guess.

Interestingly, @hybras - the replier of your mentioned post in the Hugo forum - ran into similar issues but [abandoned his approach](https://github.com/hybras/Asciidoctor-Hugo-Chroma). Sadly no reason was given on the experienced issues or a feasible workaround.

**Comment by hybras** [comment]
I suppose I can explain myself here. Hugo's syntax highlighting is called from the [`highlight`](https://gohugo.io/content-management/syntax-highlighting/) shortcode and from normal markdown code blocks. The latter is possible because hugo's markdown support has hooks to extend some syntax (I've seen people add caption support to videos, unfortunately can't find examples).

I thought I'd go with the first approach, and write an asciidoctor extension that replaced asciidoc code blocks with hugo's shortcode. This didn't work because hugo processes shortcodes before passing source files to their converter.

**Comment by McShelby** [comment]
Thanks @hybras for shedding a light on it. Maybe there is no extension required.

According to [this article](https://stiobhart.net/2020-04-18-hugo-asciidoctor/) it may be enough to wrap the resulting shortcode outcome into `++++`. If this works in an initial test, the theme may add a setting to the theme options to turn this fix `on` or `off`.

If someone with a working Asciidoc pipeline could prove this, I could proceed from this.

Note, that the theme overwrites Hugo`s `highlight` shortcode. If you want to test the above workaround with Hugo's syntaxhighlightning, the theme's `highlight` shortcode is the place to start your journey.

**Comment by hybras** [comment]
stiobhart's blog posts and comments on the hugo forum were [helpful to me](https://discourse.gohugo.io/t/asciidoc-hugo-performance/10637/14). However, he misdiagnosed the problem you pointed out (and thus the solution). It is enough to change the shortcode delimiter from `%` to `<`/`>`.
 
https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown.
https://gohugo.io/content-management/shortcodes/#shortcodes-without-markdown

**Comment by McShelby** [comment]
It would be a pitty if this theme doesn't work out of the box for AsciiDoc.

My hope is, once the theme bumps its Hugo min version up to 0.117 and switching to `[RenderShortcodes](https://gohugo.io/variables/page/#rendershortcodes)`, this might work. That's the reason for reopening this issue.

If this will not work, this issue will be closed again without any changes to the theme.

The reason for not bumping the minimum required Hugo version right now is, that my org still needs to support Hugo for 32bit systems which get us stuck with 0.95

Just as a note for me: Making this change must successfully render the page with `markup.goldmark.renderer.unsafe=false` for compatiblity with existing installations. An ill attempt was done in #547 but later was in need to be in #555.

If done, this may also fix #221

**Comment by hybras** [comment]
Looks promising.

**Comment by McShelby** [comment]
I guess the right approach for syntaxhighlightning might be to write a [custom syntax highlighter adapter](https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/custom/) for AsciiDoc utilizing [Chroma's CLI](https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/custom/). But it's just an uneducated guess.

**Comment by hybras** [comment]
That could definitely be done (and is the approach I took but with hugo's shortcodes instead of the cli). I'm not interested in that, as it yet another dependency and doesn't help my goal of getting hugo and asciidoctor to play nicer together.

**Comment by McShelby** [comment]
As of now, I have currently no plans to work on this. 

This is also due to the fact, that I don't have a need for it *and* no testing environment nor experience with AsciiDoc.

Also, I have the feeling, that support on Hugos side may get better in the future. At least some unclosed issues on Hugos issue tracker are promising.

If demand is higher, I may make another attempt.

Anyways, thanks for all your input, This may be valuable in the future, if I try another attempt.
