### ISSUE TITLE
Print does not print local image in local md file

### ISSUE THREAD

**Issue by shaozi** [McShelby/hugo-theme-relearn#624]
When I enable `PRINT` in output, then click the print button, the page does not display all images. More specifically, it does not display images referred in the same folder for any md file that is not _index.md.

Example:

Folder structure is this:

```text
content
  |-- _index.md
  |-- test.md
  |-- test.png
```

`test.md`:

```markdown
---
title: Test
menuTitle: Test
weight: 10
---

Image: ![image](test.png)
```

Then click the printer view, the image will have the wrong url: `test.html/test.png` and does not display.

**Comment by shaozi** [comment]
If the same code is in `_index.md`, then the image displays in the print view

**Comment by McShelby** [comment]
You can not link from a page to a resource reliably in Hugo. This is a Hugo limitation. You'll need a branch- or page-bundle. (See Hugos documentation for this).

Regardless, there is work in progress to lift Hugos limitation with this theme. See #587 #406
