### ISSUE TITLE
How to hide "chapter 60" on my page when the archetype: chapter and weight 60?

### ISSUE THREAD

**Issue by lvthillo** [McShelby/hugo-theme-relearn#632]
Is there a way to hide the chapter and its number on a page? I read this. https://mcshelby.github.io/hugo-theme-relearn/cont/archetypes/index.html but couldn't find an option. I'm facing this since fixing: DEPRECATED usage of old 'chapter' archetype found, remove 'chapter=true' and add 'archetype="chapter"' to your frontmatter and remove the leading h3 and h1 headings; see https://mcshelby.github.io/hugo-theme-relearn/basics/migration/#500

**Comment by cagix** [comment]
This is hard coded in the chapter template. You can override it with your own "chapter" template:

1.  Copy the original [`<relearn>/layouts/partials/archetypes/chapter/article.html`](https://github.com/McShelby/hugo-theme-relearn/blob/main/layouts/partials/archetypes/chapter/article.html) to a separate folder with the same folder structure, e.g. something like `wuppie/layouts/partials/archetypes/chapter/article.html`. 
2.  add this new "theme" `wuppie` to your config
    ```
    theme:
      - "wuppie"
      - "hugo-theme-relearn"
    ```
3.  Edit `wuppie/layouts/partials/archetypes/chapter/article.html` to your liking, e.g. remove the part `<div class="article-subheading">{{ T "Chapter" .Params.Weight }}</div>`.

**Comment by lvthillo** [comment]
@cagix Thanks! Solved my issue
