### ISSUE TITLE
breadcrumb: don't ignore spaces for separator

### ISSUE THREAD

**Issue by partigabor** [McShelby/hugo-theme-relearn#636]
The config setting `breadcrumbSeparator = " | "` works nicely when the site is hosted locally (hugo server), but the online site (GitHub pages) version ignores spaces. See image attached. Not sure if I didn't notice something or this is a bug. Thanks for all your efforts!
![scr](https://github.com/McShelby/hugo-theme-relearn/assets/58829179/5ab46979-82c2-41f7-a4d2-068f5a032462)

**Comment by McShelby** [comment]
This is a problem if using minification as in `hugo --minify`. This is pushed to main and contained in the next release.
