### ISSUE TITLE
config: check that various theme options are specified

### ISSUE THREAD

**Issue by jehoshua7** [McShelby/hugo-theme-relearn#66]
Trying to find out today how to either remove the "MORE" on the menu or change the wording.I can see the generated code in a number of .HTML files as `<h3>More</h3>`, which is obviously sourced from /i18n/en.toml , and the code for that is in /layouts/partial/menu.html , as `<h3>{{ if not $disableShortcutsTitle}}{{ T "Shortcuts-Title"}}{{ end }}</h3>`

I would expect this to be specified in the config.toml , yet it wasn't found.

A quick search of other 'disable' options used within the theme resulted in finding these:
* disableToc
* disableAssetsBusting
* disablesearch

meaning, these are used in the theme (plus disableShortcutsTitle) and not specified in config.toml

The search I did was quick and not thorough though, so there may be more. So, is a good idea to check that all the 'disable' options used in the theme are specified in the configuration ?  Or possibly it goes a little bit deeper, wherein there may exist a need to check that all optional components are setup in the configuration ??

**Comment by McShelby** [comment]
The `config.toml` is _not_ meant to be a documentation for all available config options. If you are looking for this the [Configuration](http://localhost:1313/basics/configuration/) topic provides the necessary information.

Even more documentation for the `disableShortcutsTitle` is provided by the [Menu extra shortcuts](http://localhost:1313/cont/menushortcuts/) topic.
