### ISSUE TITLE
Remove accents from generated taxonomy pages url

### ISSUE THREAD

**Issue by postb99** [McShelby/hugo-theme-relearn#664]
Hello,

On my live site, I found out that urls with accents don't work.

Look at http://poesieland.free.fr/categories/ then follow the first link of the page.

Locally it work fine.

Is this a server issue? Maybe the taxonomy pages could use normalized version of category/tag name when being generated?

**Comment by McShelby** [comment]
This seems to be a server issue as I could not reproduce it neither with your used version of the theme nor the current head in main.

As far as I know file name normalization is not done by Hugo and is not configurable.

You could probably add a custom [term page](https://gohugo.io/content-management/taxonomies/) and adding `slug` to it - but that's just a wild guess. Also, this would be a hassle as you have to add such a page for every term that contains accents.

The best way seems to be, changing the server configuration.

**Comment by postb99** [comment]
Since I don't have control over server configuration, and anyways didn't find what could be relevant, I took a second look at Hugo's feature and the aforementioned configuration option works, is still supported and handles "é" and "è", so here is the magic option: https://gohugo.io/getting-started/configuration/#removepathaccents

Hovewer this may not work for all characters: https://discourse.gohugo.io/t/remove-competely-accents-from-url/35416
