### ISSUE TITLE
taxonomy: display terms in pages if `removePathAccents=true`

### ISSUE THREAD

**Issue by postb99** [McShelby/hugo-theme-relearn#669]
Hello,

After solving #664 : now that basic Eastern Europe diacritics are removed from taxonomy's terms when generating the urls, I notice disppearance of the term in post footer, any clue why?

![image](https://github.com/McShelby/hugo-theme-relearn/assets/173565/607f4d48-f40d-41a6-8e0f-0633d634e00a)

The "Eté" word is missing as first category of this text.

Live post: http://poesieland.free.fr/seasons/11_onzieme_saison/souffle_d_ete/index.html

Same missing tag in post' header tags, for another live post.

I just updated to theme latest version but Hugo still displays version 0.115.

**Comment by McShelby** [comment]
Thanks for reporting. Fixed.

**Comment by McShelby** [comment]
After rethinking it, the problem is much more complicated for all cases. 

While the patch will work for you, overwritting term pages, setting custom URLs for a taxonomy or term and terms with spaces will fail for different scenarios.

Back to the drawing board.

**Comment by McShelby** [comment]
I gave up on this. Either I do not understand Hugos data structures or there might be a gap in its design. For now as no one complains it's good as it is.

@postb99 Anyways you might find #671 interesting which was a fallout of my tests.
