### ISSUE TITLE
taxonomy: modularize term list generation

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#671]

**Comment by postb99** [comment]
@McShelby It looks very nice rewritten this way, thanks for pointing this work out to me. However I noticed a small typo:
https://github.com/McShelby/hugo-theme-relearn/blob/main/layouts/partials/term-list.html#L27
You wrote taxono**n**my-

**Comment by McShelby** [comment]
Thanks for pointing this out!

**Comment by postb99** [comment]
Nice, I also prefer "layer-group" icon to "cubes". It looks very professional.

**Comment by McShelby** [comment]
@postb99 You are finding all of my typos ;-)
