### ISSUE TITLE
Mermaid enabled on live site: JS issue

### ISSUE THREAD

**Issue by postb99** [McShelby/hugo-theme-relearn#673]
Hello,

I noticed that my live site was broken for the following: 
- no more hamburger menu on very small screen
- no vertical scrollbar on my long unfolded menu.

I found out this JS line crashing on an undefined variable:
https://github.com/McShelby/hugo-theme-relearn/blob/main/static/js/theme.js#L1476

This may be due to my host not being able to do something because I don't see the issue on local in-memory site?

Best was to disable both mermaid and mathJax in hugo.toml because I don't use them on my site and they seem enabled by default.

Using green theme on my website.

**Comment by McShelby** [comment]
What's a bit strange is, that this line of code is only executed _if_ you have a Mermaid graph on your page. Do you have an URL I can see this?

**Comment by postb99** [comment]
When I had the issue I had this hugo.toml config:

```
# If set to false, load the Mermaid module on every page regardless if a Mermaid shortcode or Mermaid codefence is present
disableMermaid = false
```

So Mermaid was enabled even without ever using it. But now the code on my live site works... I put a breakpoint line 1480 of theme.js...

![image](https://github.com/McShelby/hugo-theme-relearn/assets/173565/5cbdab43-549f-4dd6-8931-d446a46d1814)

and execute the following code in console, and the result is the same on live and in-memory site, the variable is defined, no possible error. Closing the issue then. My guess is that I may have performed a partial upload after a theme update, my bad.

![image](https://github.com/McShelby/hugo-theme-relearn/assets/173565/08029851-47bc-4204-8e2c-df5986b61ad2)
