### ISSUE TITLE
Responsive design question

### ISSUE THREAD

**Issue by postb99** [McShelby/hugo-theme-relearn#674]
Hello,

On my site, I use a notice that contains inclusion of a page, thus the code:

```
{{% notice title="Derniers poèmes ajoutés" style="note" color="" icon="" %}}
{{% include "last_poems.md" true %}}
{{% /notice %}}
```

The included page contains hyperlinks with long labels but they can be word-wrapped.

Is something wrong with this way, because the notice looks weird on very small screen like a smartphone:

![image](https://github.com/McShelby/hugo-theme-relearn/assets/173565/c77d7e8f-103f-418b-bf0e-9dee92c6c8fc)

Thanks for guidance.

**Comment by McShelby** [comment]
I haven't taken a closer look yet but it comes from your styles in `custom.css`. If you delete all of them, everything works as expected (at least on my test site)
