### ISSUE TITLE
menu: make width configurable

### ISSUE THREAD

**Issue by postb99** [McShelby/hugo-theme-relearn#677]
Hello,

I need left menu to be wider because my items have long wording, first level item is "Saisons" and second level item is "Quinzième Saison : De place en place". I really would like second level item text to fit a single line.

![image](https://github.com/McShelby/hugo-theme-relearn/assets/173565/c6a8fce2-d901-4f4a-bcf8-e8aaf9757b61)

How to do this right way? For now I did some experimentations in custom css but this broke some other things 😎 #674 

My attempt was to replace 18.75rem by 20rem in these styles, but I guess some other numbers need an adjustment?

https://github.com/McShelby/hugo-theme-relearn/blob/main/static/css/theme.css#L152
https://github.com/McShelby/hugo-theme-relearn/blob/main/static/css/theme.css#L329
https://github.com/McShelby/hugo-theme-relearn/blob/main/static/css/theme.css#L424
https://github.com/McShelby/hugo-theme-relearn/blob/main/static/css/theme.css#L435

**Comment by postb99** [comment]
@McShelby may you improve the doc with screen width values for which the M configuration is used, ans same for the L. I know it's standard but this helps tests. Si that it's also clear what a small screen width is. Thanks 🙂 and amazing delay for implementing my request, wonderful.

**Comment by McShelby** [comment]
Done
