### ISSUE TITLE
theme: simplify additional JS dependencies

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#682]
The theme uses additional JS libraries for some of its shortcodes (like `mermaid` and `math`).

The theme implements a mechanism to load those libraries only if they are required by the resulting HTML file.

Each dependency must be handled in various file locations of the theme (see #680).

This is okay if those dependencies are shipped with the theme but makes it rather impossible for users to add their own additional dependencies (eg. if they want to add further shortcodes backed by additional JS libraries).

Let's make this easily extendable for user.

**Comment by postb99** [comment]
https://mcshelby.github.io/hugo-theme-relearn/basics/customization/index.html#own-shortcodes-with-javascript-dependencies

**Comment by postb99** [comment]
Hello, I added some comments to your commit. Maybe there are typos, so I prefer asking.

https://github.com/McShelby/hugo-theme-relearn/commit/1250bf30a8c2e3c1bfac285489bc63f2c395b641#diff-1e544a26a7f4578841c7de3996d149f145adaea4cffb6826fd8a805183f63ce6R174
