### ISSUE TITLE
menu: add additional sort options

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#684]
Bring this in line with Hugo and the children shortcode

**Comment by postb99** [comment]
I tested this today but noticed that sorting by date always sorts by descending date. Did no one ask for ability to sort by ascending date? Not a problem though.

**Comment by McShelby** [comment]
I left the sort direction out of the equation, yet. This would make it necessary to introduce a further option into the sites config, the front matter and the `children` shortcode.

As I am lazy and focused mainly on #685 (#684 was actually a preparation step before tackling #685) I'll postpone it until someone asks.
