### ISSUE TITLE
theme: reduce build time

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#685]
The theme has O(n²) built time behavior because of the _hidden pages_ feature. Improve it.

**Comment by gunponteet** [comment]
Does this address [this issue](https://github.com/McShelby/hugo-theme-relearn/discussions/686)?

**Comment by McShelby** [comment]
No.

**Comment by gunponteet** [comment]
Okay. I faced the same issue and was confused until I did a search in issues and discussions.
