### ISSUE TITLE
Do not use site.BaseURL in your templates

### ISSUE THREAD

**Issue by calalloo** [McShelby/hugo-theme-relearn#687]
> There is never a great reason to call .Site.BaseURL from a template. Hopefully we will deprecate that method at some point. Use the absURL and absLangURL functions instead.

https://discourse.gohugo.io/t/site-baseurl-appears-in-a-js-template-literal/46692/4

**Comment by McShelby** [comment]
As long as it works an is supported, there is no need to change it.

**Comment by calalloo** [comment]
Your call...
