### ISSUE TITLE
docs: mark non released main branch release notes as such

### ISSUE THREAD

**Issue by FidelusAleksander** [McShelby/hugo-theme-relearn#689]
Hi 

I'd like to start using opengraph features which as per documentation are added in 5.23.0 

![image](https://github.com/McShelby/hugo-theme-relearn/assets/63016446/b3ad8a68-ca89-4868-ae0a-e028ef4f2a6b)

However that tag/release is not present in the repository

Am I missing something @McShelby ?

**Comment by McShelby** [comment]
Sorry for the confusion.

I've to get accustomed to myself to invalidate the date in the release notes as long as the release is not finished. This is the case here.

So, the release is still in development and not available as a tag, yet. See https://github.com/McShelby/hugo-theme-relearn/milestone/130.

Once the release is published, the date will be changed to the official release day automatically by the build-script.

**Comment by FidelusAleksander** [comment]
Thanks! I understand now

I will use the main branch
