### ISSUE TITLE
After updating params.author.name in toml menu items unavailabe

### ISSUE THREAD

**Issue by scan-dev** [McShelby/hugo-theme-relearn#694]
Bottom menu items "Theme selection" and "Clear history: are not available/visible anymore after recommended toml config change.

Current TOML config
`[params]
  images = ["images/hero.png"]
  editURL = "HTTP_URL"
  description = "Documentation for Relearn"
  Author = "Author Name"
`

When build hugo you get WARN message after latest update

`
WARN  "cont/taxonomy.en.md": DEPRECATED usage of 'params.author' config parameter found, replace it with "params.author.name" in your config.toml; see https://mcshelby.github.io/hugo-theme-relearn/basics/migration/#5230
`

after changing  toml config as indicated the bottom menu items "Theme selector" and "Clear history: are not available/visible anymore

Updated TOML config :
`[params]
  [Author] 
    name = "Author_ Name"
`

After reverting back to old/current [params]  settings the menu items are availabe/visible again

**Comment by McShelby** [comment]
Please post your complete `config.toml` that did not work.

**Comment by McShelby** [comment]
I've changed the docs to position independend parameters, making it easier to change existing configurations without hassling with toml quirks.

**Comment by scan-dev** [comment]
my toml config which the disabled the bottom menu options

> baseURL = "https://example.com/"
> 
> canonifyURLs = true # true -> all relative URLs would instead be canonicalized using baseURL
> relativeURLs = true # true -> rewrite all relative URLs to be relative to the current content
> uglyURLs = false     # true -> basic/index.html -> basic.html
> 
> themesdir = "themes"
> theme = "hugo-theme-relearn"
> 
> # the main language of this site; also an automatic pirrrate translation is
> # available in this showcase
> languageCode = "en"
> defaultContentLanguage = "en"
> # if you want to get rrrid o' ourrr pirrrates nonsense uncomment th' next line
> #disableLanguages = ['pir']
> 
> # the site's title of this showcase; you should change this ;-)
> title = "SITE_TITLE"
> 
> [outputs]
>   home = ["HTML", "RSS", "PRINT", "SEARCH", "SEARCHPAGE"]
>   section = ["HTML", "RSS", "PRINT"]
>   page = ["HTML", "RSS", "PRINT"]
> 
> [markup]
>   [markup.highlight]
>     # line numbers in a table layout will shift if code is wrapping, so better
>     # not use it; visually both layouts have the same look and behavior
>     lineNumbersInTable = false
> 
>     # if `guessSyntax = true`, there will be no unstyled code even if no language
>     # was given BUT Mermaid and Math codefences will not work anymore! So this is a
>     # mandatory setting for your site if you want to use Mermaid or Math codefences
>     guessSyntax = false
> 
>     # the shipped variants come with their own modified chroma syntax highlightning
>     # style which is imported in theme-relearn-light.css, theme-relearn-dark.css, etc.;
>     # if you want to use a predefined style instead:
>     # - remove `noClasses` or set `noClasses = true`
>     # - set `style` to a predefined style name
>     noClasses = false
>     # style = "tango"
> 
>   [markup.goldmark.renderer]
>     # activated for this showcase to use HTML and JavaScript; decide on your own needs;
>     # if in doubt, remove this line
>     # unsafe = true
> 
> # showcase of the menu shortcuts; you can use relative URLs linking
> # to your content or use fully-quallified URLs to link outside of
> # your project
> [languages]
>   [languages.en]
>     title = "SITE TITLE"
>     weight = 1
>     languageName = "English"
>     # Language dependend settings:
>     # Use case https://gohugo.io/content-management/multilingual/#translation-by-content-directory
>     #contentDir = "content/en"
>     [languages.en.params]
>       landingPageName = "<i class='fas fa-home'></i> Home"
> 
>   [[Languages.en.menu.shortcuts]]
>   name = "<i class='fab fa-gitlab'></i> GitLab Project"
>   identifier = "ds"
>   url = "https://github.com/McShelby/hugo-theme-relearn"
>   weight = 11
> 
>   [[Languages.en.menu.shortcuts]]
>   name = "<i class='fas fa-fw fa-pen'></i> Content Creation"
>   url = "https://mcshelby.github.io/hugo-theme-relearn/cont"
>   weight = 12
> 
>   [[Languages.en.menu.shortcuts]]
>   name = "<i class='fas fa-fw fa-code'></i> Shortcodes"
>   url = "https://mcshelby.github.io/hugo-theme-relearn/shortcodes"
>   weight = 13
> 
>   [[Languages.en.menu.shortcuts]]
>   name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
>   identifier = "hugodoc"
>   url = "https://gohugo.io/"
>   weight = 20
> 
> # mounts are only needed in this showcase to access the publicly available screenshots;
> # remove this section if you don't need further mounts
> [module]
>   [[module.mounts]]
>     source = 'archetypes'
>     target = 'archetypes'
>   [[module.mounts]]
>     source = 'assets'
>     target = 'assets'
> 
>   # Language dependend settings:
>   # Use case https://gohugo.io/content-management/multilingual/#translation-by-filename
>   [[module.mounts]]
>     source = 'content'
>     target = 'content'
> 
>   # Use case https://gohugo.io/content-management/multilingual/#translation-by-content-directory
>   #[[module.mounts]]
>   #  lang = 'en'
>   #  source = 'content/en'
>   #  target = 'content'
>   #[[module.mounts]]
>   #  lang = 'pir'
>   #  source = 'content/pir'
>   #  target = 'content'
> 
>   [[module.mounts]]
>     source = 'data'
>     target = 'data'
>   [[module.mounts]]
>     source = 'i18n'
>     target = 'i18n'
>   [[module.mounts]]
>     source = 'images'
>     target = 'static/images'
>   [[module.mounts]]
>     source = 'static/images'
>     target = 'static/images'
>   [[module.mounts]]
>     source = 'layouts'
>     target = 'layouts'
>   [[module.mounts]]
>     source = 'static'
>     target = 'static'
> 
> # settings specific to this theme's features; choose to your likings and
> # consult this documentation for explaination
> [params]
>   images = ["images/hero.png"]
>   editURL = "https://github.com/McShelby/hugo-theme-relearn"
>   description = "Documentation for SITE"
>   [Author]
>     name = "AUTHOR_NAME"
>   showVisitedLinks = true
>   collapsibleMenu = true
>   disableBreadcrumb = false
>   disableRootBreadcrumb = true
>   disableInlineCopyToClipBoard = true
>   disableNextPrev = false
>   disableLandingPageButton = true

  breadcrumbSeparator = ">"
  titleSeparator = "::"
  themeVariant = [ "auto", "relearn-bright", "relearn-light", "relearn-dark", "zen-light", "zen-dark", "neon", "learn", "blue", "green", "red" ]
  themeVariantAuto = [ "relearn-light", "relearn-dark" ]
  disableSeoHiddenPages = true
  mermaidInitialize = "{ \"securityLevel\": \"loose\" }"
  mermaidZoom = true
  [params.siteparam.test]
    text = "A **nested** parameter <b>with</b> formatting"
  [params.imageEffects]
    bg-white = true # extension, not supported by the theme
    border = true

**Comment by McShelby** [comment]
Follow the link of the error message: https://mcshelby.github.io/hugo-theme-relearn/basics/migration/#5230
