### ISSUE TITLE
theme: warnings when linking to pages

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#695]
Well, I personally need to see later why I get a bunch of warnings about my absolute links (not fully absolute because the default language prefix is implicit) when I build my site after upgrading the theme which supports portable links now.

WARN  "_index.md": no page was found for link '/en/original_texts/'
WARN  "_index.md": no page was found for link '/seasons/18_dix_huitieme_saison/la_maison_de_famille/'

However the links work on site (http://poesieland.free.fr/index.html).

`<a href="/seasons/18_dix_huitieme_saison/la_maison_de_famille/" class="highlight">La maison de famille, écrit le 24.10.2023</a>`

_Originally posted by @postb99 in https://github.com/McShelby/hugo-theme-relearn/issues/587#issuecomment-1780105757_

**Comment by McShelby** [comment]
This is related to changes in #377.

@postb99 Can you post not the resulting HTML anchor but the origniating Markdown?

**Comment by postb99** [comment]
In `content\fr\last_poems.md`:

`[La maison de famille, écrit le 24.10.2023](/seasons/18_dix_huitieme_saison/la_maison_de_famille/)`

Linked page is located at `content\fr\seasons\18_dix_huitieme_saison\la_maison_de_famille.md`

So I would rather link to relative path `seasons/18_dix_huitieme_saison/la_maison_de_famille/`.

This solves the issue but for cross-language links the relative link such as 
`Head to the [French poems](../fr/seasons)`
in `content/en/_index.md` gives a 404 error.
So I have to keep `Head to the [French poems](/seasons)`

**Comment by McShelby** [comment]
A few things by testing:

- there was a regression in handling multilang links, please update the theme in your installation
- a link starting with a `/` or with a letter is always treated as absolute
- an absolute link starting with a language prefix will link to according translated page
- a link starting with a `.` is treated relative to the current page
- relative links can not link to other translations
- I've updated the [migraiton documentation](https://mcshelby.github.io/hugo-theme-relearn/basics/migration/index.html#5230) for the above four points
- `content\fr\last_poems.md` seems to have no title, this causes the menu to only show a white bar without any text if I browse to this page. Was this intended?

Please test again with the updated theme and let me know the outcome. To make it clear: `seasons/18_dix_huitieme_saison/la_maison_de_famille/` should have worked, as it is absolute to your language root.

**Comment by postb99** [comment]
Sorry for the initial confusion, I should have rather given `_index.md` as sample page, but you got it, `last_poems.md` is indeed an included page. And the warning is repeated for main and included page.

Thank you for the nice documentation and theme update, now I've updated my same language links to proper relative urls `'./some/path'` and kept the absolute links `'/en/some/path'` for one language to another one links. The warnings in this last case are still present but this is normal and documented. Maybe add a last note in aforementioned documentation about such warnings being unavoidable?

`WARN  "\\_index.md": no page was found for link '/en/original_texts/'`

I also confirm that from `_index.md`, whatever `'/seasons'` or `'./seasons'` urls work, of course 😉

**Comment by McShelby** [comment]
>  absolute links `'/en/some/path'` for one language to another one links. The warnings in this last case are still present but this is normal and documented.

This should not throw warnings if the path is valid. Maybe it's time to share your repo again ;-)

**Comment by McShelby** [comment]
Thanks for reporting this. It was insightful. As an outcome of this, the warning messages now print the full source file path (#699) as it was at first difficult to find out which Markdown file was emitting the warings (there were multiple).

I've added the fix to #377.  Basically the theme wasn't prepared for the fact that files may only exist for one translation.

After you've updated the theme you should only see one link warning. This is expected as you try to link from the english home page to the french `seasons` section without giving the language prefix.

As a side note: If you also add `archetype = "home"` to the english home page, the last warning will vanish.

I hope you don't get too annoyed stumbling over all of my bugs. Your feedback is much appreciated.

**Comment by postb99** [comment]
I really appreciate mutual help, me finding special cases bugs and you my miswritings!
