### ISSUE TITLE
link: extra space before link text

### ISSUE THREAD

**Issue by adrien1212** [McShelby/hugo-theme-relearn#700]
Hi,

**When**
You want add a cross reference like `([Software Architecture]({{% ref "/softwareArchitecture.md" %}}))`  an extra space is added

**Actual output**
`text before ( Software Architecture) text after` -> extra space after the `(`

**Expected output**
`text before (Software Architecture) text after` -> no space after the `(`

**Comment by McShelby** [comment]
Thanks for reporting. This is now fixed.
