### ISSUE TITLE
taxonomy: allow for content on term pages

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#701]
This allows you to have a taxonomy [term page](https://gohugo.io/content-management/taxonomies/#add-custom-metadata-to-a-taxonomy-or-term) with content written between `h1` and the list.

@postb99: New for you!

**Comment by postb99** [comment]
Did you document this on https://mcshelby.github.io/hugo-theme-relearn/cont/taxonomy/#customization or on another page?

By the way I just noticed a typo in Readme, should be "adapted" rather than "adepted": 

_with the aim of fixing long outstanding bugs and ad**e**pting to latest Hugo features_

**Comment by McShelby** [comment]
> Did you document this

Well... "documented" is such a tough word for a little mention ;-)

See https://mcshelby.github.io/hugo-theme-relearn/basics/migration/index.html

> New: Taxonomy term pages are now allowed to contain content. This is added inbetween the title and the page list.

This is the standard mechanism of Hugo, so theirfore I spared out further documentation.

You can find an example in `exampleSite/content/tags/hidden/_index.*.html and the [resulting page](https://mcshelby.github.io/hugo-theme-relearn/tags/hidden/index.html)
