### ISSUE TITLE
taxonomy: add h2 subheadings on term page

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#705]

**Comment by McShelby** [comment]
@postb99: Making your huge terms pages a bit more friendly for the eyes.

**Comment by postb99** [comment]
Wow, I really love your addition of breadcrumb, this looks perfect in my taxonomy! This looks so polished now.

![image](https://github.com/McShelby/hugo-theme-relearn/assets/173565/32afa0fd-7019-43b5-a3d0-ddae628f8e23)

**Comment by McShelby** [comment]
Looks really spiffy! My `exampleSite` lacks valuable tags and categories, so there is just some test data which doesn't look that impressive.

**Comment by postb99** [comment]
You're welcome to use my poetry site as a manual tests validation site for things like taxonomy 😉
