### ISSUE TITLE
links: ignore local markdown links linking to files with extension

### ISSUE THREAD

**Issue by cagix** [McShelby/hugo-theme-relearn#707]
It seems that parsing local links is a bit too greedy: A link `[Grammar: VarDef](src/VarDef.g4)` in the Markdown sources to an existing file `VarDef.g4` in the local subfolder `src/` is mistakenly(?) treated as link to a Markdown file and on rendering it gives an error because there's no suitable template for it.

(theme: 5.23.0, hugo: 0.120.0)

<img width="961" alt="Screenshot 2023-10-30 at 16 14 05" src="https://github.com/McShelby/hugo-theme-relearn/assets/20356276/7f4a6c92-777a-45d2-9ff4-75001123c464">

That said, I'm incredibly grateful for the portable linking implementation (c83696239c732cf814714ef1f4af50f5d0c165e9) and the improved warnings (8b0214e9a5202656307fd55f0c39a01fb6b8e2c0)! This has already helped me to find quite a lot of hidden bugs :)

**Comment by McShelby** [comment]
This is the line with the `warnf` statement. It's explicitly just a warning to avoid build errors. Did you reconfigure Hugo's error handling in your `config.toml`.

I will relax the condition to ignore links if they are local and contain any suffix

**Comment by cagix** [comment]
You are right, I have configured Hugo to consider warnings as errors. 

On the other hand, the warning is coming from the Relearn theme because no matching template could be found for the linked file. I think the file (an ANTLR grammar) was incorrectly considered and treated as a local Markdown file?

**Comment by McShelby** [comment]
That's a correct observation. Thus

> I will relax the condition to ignore links if they are local and contain any suffix.

**Comment by McShelby** [comment]
I made a new relese with this bug fixrd.
