### ISSUE TITLE
Are custom single.html or list.html layouts possible with this Theme?

### ISSUE THREAD

**Issue by FidelusAleksander** [McShelby/hugo-theme-relearn#711]
Is it possible to have custom layouts for certain types of content when using this theme?

This is how my [content](https://github.com/FidelusAleksander/githubcertified/tree/master/content) structure looks like. Practice tests display content from /content/questions

![image](https://github.com/McShelby/hugo-theme-relearn/assets/63016446/47590642-21d7-4783-8c7b-a6091486de05)

Now I wanted to create a custom layout `/layouts/questions/single.html` but then it shows 404 Page Not Found.

So are custom layouts possible whilst keeping the side navbar and other components and just changing the inner content display?

**Comment by cagix** [comment]
not sure, if this is true also for `single.html`. to define a custom layout, you need to populate the `archetype` metadata variable in each document like `archetype: question` (YAML header). additionally your custom template should be in a folder `<customtheme>/layouts/partials/archetypes/question/`, and you would need to specify this "custom theme" in your Hugo config like

```
theme:
  - "customtheme"
  - "hugo-theme-relearn"
```

**Comment by McShelby** [comment]
At the moment I must confess it's overcomplicated and too difficult to do such modifications.

So before ripping everything apart, what kind of modification do you want to achieve?

1. Leaving the menu and only customize the content area of a post?
2. Completly change the whole page including menu, topbar, search, etc.?

**Comment by FidelusAleksander** [comment]
I wanted to modify the content (or "article") part and @cagix lead me to the archetypes which worked fine for me [here](https://github.com/FidelusAleksander/githubcertified/blob/3297896f091096514f7a5056509147a6d45ca58f/layouts/partials/archetypes/questions/article.html)

I am quite new to Hugo and I guess it was confusing to me that "archetype" was somehow connected to what layout will be picked. 
I thought of archetypes as predefined content pages but what layout would be picked is not based on the frontmatter but the section in which the content page resides. So in my case I thought I would need to create` /layouts/questions/single.html` 

This can be closed
