### ISSUE TITLE
themeVariant Doesn't Work For Custom Values

### ISSUE THREAD

**Issue by hgtuttle** [McShelby/hugo-theme-relearn#717]
Are the custom theme and file steps  on the [generator page](https://mcshelby.github.io/hugo-theme-relearn/basics/generator/index.html) still correct?
>  Once you are satisfied, you can download the new variants file and copy it into your site’s static/css directory. Afterwards you have to adjust the themeVariant parameter in your config.toml to your chosen file name.

I ran into an issue trying to get any sort of custom theme via the [stylesheet generator](https://mcshelby.github.io/hugo-theme-relearn/basics/generator/index.html) to work with the `themeVariant` parameter. All elements would go to a grey and white theme when changing the value to match my css file name (no .css in the parameter value). I get the same result when putting in a garbage value
like `themeVariant = "hippopotamus"`. 

After no luck with the generator I decided to go with the option shown in [the docs](https://mcshelby.github.io/hugo-theme-relearn/basics/customization/index.html#roll-your-own) on copying from one of the provided options. Chances are I'm missing something (very new to Hugo) but my understanding is that the process below _should_ work.

1. Created new hugo site via the standard [quick start](https://gohugo.io/getting-started/quick-start/)
2. Ran `git submodule add https://github.com/McShelby/hugo-theme-relearn.git themes/relearn`
3. Modified hugo.toml file in the root of the directory to `theme = 'relearn'` 
4. Copied the [Global site parameters](https://mcshelby.github.io/hugo-theme-relearn/basics/configuration/index.html#global-site-parameters) into the bottom of the default hugo.toml in the root of the site directory
5. Set the themeVariant value to "red" and verified the red theme worked via `hugo server -D` and the theme was red
    - Toggled to blue, live change to blue
 6. Copied theme-red.css from /themes/relearn/static/css to /static/css and renamed the file to `customized.css`
 7. Set /hugo.toml, `themeVariant = "customized"` and the live reload triggers, but displays the same grey theme
 8. Setting the themeVariant value back to red reloads with the red theme.

**Comment by McShelby** [comment]
I haven't had the time to test your steps, yet. Basically everthing sounds correct. The only thing that could be necessary is a restart of Hugo between your step 6 and 7. Sometimes the Hugo server does not react to changes of those referenced files.

**Comment by hgtuttle** [comment]
Appreciate the follow up.  A fresh hugo startup with all files already set to their desired values results in the same grey outcome. Stopping > modifying to a pre-built value (blue) > starting again works. Stopping > modifying to desired filename > starting results in the same grey elements.

As a workaround I've gone ahead and converted the project files from a sub-module and modified one of the built-in themes as needed which is working like a charm.

**Comment by McShelby** [comment]
I now tested it and it worked without a restart of the Hugo server. 

**In your step 6, the file needs to be named `theme-customized.css`**

From the [docs](https://mcshelby.github.io/hugo-theme-relearn/basics/generator/index.html):

> Eg. if your new variants file is named theme-my-custom-variant.css, you have to set themeVariant='my-custom-variant' to use it.

**Comment by hgtuttle** [comment]
That did the trick! Thank you so much for clarifying that. Can you verify what I'm taking away from this?

1. The custom CSS file can't be named with a single word, e.g. "customized.css". 
2. The file name must have "theme-" at the beginning.
3. It is called by entering the text between "theme-" and ".css" in the filename for the themeVariant value.

**Comment by McShelby** [comment]
That's a 100% 💯
