### ISSUE TITLE
Search-Index and Sitemap not generated after Theme update

### ISSUE THREAD

**Issue by andi-blafasl** [McShelby/hugo-theme-relearn#743]
Hey Folks,

just updating the theme on our project ["BITS Training"](https://github.com/BITS-Training/BITS-hugo/tree/theme-update) form version 5.3 to 5.23. Fixed all error, warning and deprecation messages during hugo build but can't get search to work. It was working perfect with the old "JSON" Based search before.

I checked the index.search.js and it is quite empty. It seams only the more section content is indexed. These are the sites that where moved due to the changes in Theme version 5.9

The same thing is happening with the sitemap.xml. It was working with Theme 5.3 and now only the more section content is listed in the sitemap.xml 🤷‍♂️ 

Maybe someone can check out the repo and give me a hint what's going wrong with our content?

Many thanks 😊

**Comment by McShelby** [comment]
I'll take a look into it... stay tuned

**Comment by McShelby** [comment]
This seems to be race condition. If I run `hugo server` initially the index is broken. If I change the index template and cause a regeneration, the index is fine. 

Interestingly, my own page never behaved this way...

...still thinking how to avoid this...

**Comment by McShelby** [comment]
Ok, got it. Although I still don't know why this race condition happens.

The main reason is, that pages with empty `title` are treated as hidden. This was always the case but over the theme's version history an additional check got added where it was missing.

In your case your `content/_index.de.md` does have an empty title and therefore the page itself **and** all descendends are treated as hidden.

To solve it, exchange your title to this:

````
title: " "
````

**Comment by andi-blafasl** [comment]
Wow! Thank you so much for this quick find. The empty Title in the top most _index.de.md was changed during the update because of the new archtype=home Template that is used. We have a H1 with a parameter in the content and this was the easiest way to get the same look. Think this was a bit too quick and dirty 😉 Will try to find a better solution with a real title, but your idea with a space is a nice workaround and kept in mind.

But it's interesting why this accidental hiding of the pages doesn't affect the menu generation?

**Comment by McShelby** [comment]
> But it's interesting why this accidental hiding of the pages doesn't affect the menu generation?

He he, Full roundtrip here: https://github.com/McShelby/hugo-theme-relearn/issues/134#issuecomment-959834008

If you visit a hidden page, it is always revealed in your menu. Because the `hidden` option is **not** inherited by its descendends, they will all be shown as well.

**Comment by andi-blafasl** [comment]
🙄 lol 🤣

**Comment by McShelby** [comment]
I soon have a more elegant solution: #744
