### ISSUE TITLE
Grab icons from SimpleIcons too?

### ISSUE THREAD

**Issue by mmlb** [McShelby/hugo-theme-relearn#750]
I'd love to be able to grab icons from simpleicons along with font-awesome. Would you be open to that?

**Comment by McShelby** [comment]
No, because of unclear licensing. From their docs:

> Simple Icons is released under CC0 - though that doesn't mean to imply that all icons within the project are also CC0. Please see individual licenses where available.

Additionally I see not much gain in having a huge set of brand icons that will only sparsly been used but complicating the icon implementation.

**Comment by mmlb** [comment]
Makes sense, thanks for the response. Is there a way I can supply the icon via `icon=` if I save it locally?

**Comment by McShelby** [comment]
Not at the moment. The implementation currently generates the HTML strucutre specific to Font Awesome's requirements.
