### ISSUE TITLE
dependencies: fix wrong docs

### ISSUE THREAD

**Issue by TobiasBaeumlin** [McShelby/hugo-theme-relearn#751]
Hello

I'm trying to add a shortcode that needs some additional css to the relearn theme.
For this I tried to follow the instructions here: 

https://mcshelby.github.io/hugo-theme-relearn/basics/customization/index.html#own-shortcodes-with-javascript-dependencies

Assuming this should work also for including an extra css file:

`layouts/shortcodes/features.html`
```
<div class="feature">
    {{ .Inner }}
</div>
{{- .Store.Set "hasFeatures" true }}
```
`layouts/dependencies/features.html`

```
<link rel="stylesheet" href="static/css/features.css">
```

In `hugo.toml`:

```
[params.relearn.dependencies]
  [params.relearn.dependencies.features]
    name = "Features"
    location = "header"
```

Unfortunately this gets me an error when starting the hugo server:

```
Error: error building site: failed to render shortcode: "/home/tobias/Hugo/helppages.gymneufeld.ch/content/_index.md:21:1": failed to render shortcode "features": failed to process shortcode: "/home/tobias/Hugo/helppages.gymneufeld.ch/layouts/shortcodes/features.html:4:10": execute of template failed: template: shortcodes/features.html:4:10: executing "shortcodes/features.html" at <.Store.Set>: can't evaluate field Store in type *hugolib.ShortcodeWithPage
```

What am I getting wrong?

Regards
Tobias

**Comment by McShelby** [comment]
I haven't double checked it yet, but I suppose there is a documentation error in the docs. Try to replace the last line of your shortcode file `layouts/shortcodes/features.html` with

````
{{- .Page.Store.Set "hasFeatures" true }}
````

**Comment by TobiasBaeumlin** [comment]
Thanks for the swift reply, greatly appreciated.

That was in fact it, it works now as expected.
