### ISSUE TITLE
theme: fix blurry text on Windows 11 with ClearType

### ISSUE THREAD

**Issue by bitroniq** [McShelby/hugo-theme-relearn#758]
# Problem statement

On Windows 11 with ClearType with 100% scaling the main font doesn't look crips and sharp.

## Details

1. I see the fractional px sizes for font and line
2. "Work Sans" font is not good for ClearType

![image](https://github.com/McShelby/hugo-theme-relearn/assets/1032724/74a01d33-6657-4bee-a9a1-98733c511436)

## Remarks

Changing size to integer 16 px and font to Calibri (best Microsoft font for LCD screens with ClearType subpixel aliasing) makes huge difference:

![image](https://github.com/McShelby/hugo-theme-relearn/assets/1032724/8c51618d-862f-44a6-a6b7-6c2b4e186e4e)

**Comment by McShelby** [comment]
This is not a Windows-only project so changing the font to Calibri is off the table for the shipped installation.

I may revise font sizing at some point to make it integer values again.

If you're unhappy with the choosen font, you can overwrite it with your used theme variant.

See
- https://mcshelby.github.io/hugo-theme-relearn/basics/branding/index.html#modify-shipped-variants
- `MAIN-font` parameter https://mcshelby.github.io/hugo-theme-relearn/basics/generator/index.html

**Comment by McShelby** [comment]
I've spend some time to further investigate this.

The used font is displayed as expected on my screen. I can not observe any blurriness. At most there may be a lack in contrast - but this is a subjective topic.

Having a fractional font-size is not an issue with modern browsers as they have to deal with fractional results for internal rendering anyways.

As already said: If you dislike the used font, you can reconfigure it.

If you still feel, this is an issue, please provide some images showing your actual problem. Having two screenshots using different fonts, is not helpful for comparison.

Please also note, that the font-color recently changed to improve contrast in #722 and will be rolled out with the upcoming release.

Also: Like the used font, the font colors are adjustable.

**Comment by bitroniq** [comment]
@McShelby thank you so much for taking care of this issue during the weekend and focusing on that font subject.

Indeed, we changed the font definition. Now on the generated page in `custom.css` we have:

```css
/* Font customization */
@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap');

body{
    font-family: 'Roboto', sans-serif!important;
}
...
/* Color setting */
/* color setting end */
:root{
    --INTERNAL-MAIN-font: var(--MAIN-font, 'Roboto', sans-serif)!important;  
```

and besides that, we did not change anything else.

That helped a lot - now the font is sharp and crisp on every monitor, OS, mobile, at every scale.

BTW. I think the problem itself is caused by the font "Work Sans". It is not well made for Microsoft's ClearType font aliasing.
I also did some more checks looking at the results on light-theme, dark-theme, on iPhone 14, macOS, Windows, using different scaling. 
The issue is always on Windows, 100% scaling, light-theme. On DarkTheme it is ok.

Changing the font color to pure black solves the problem partially.

But we decided to simply use the recommended Roboto font, which works just great for us.

Thank you!

**Comment by McShelby** [comment]
Thanks for the feedback. 

Just out of curiosity: Do you observe the same blurry behavior with the [original Learn theme](http://learn.netlify.app)?

**Comment by bitroniq** [comment]
@McShelby 

> Just out of curiosity: Do you observe the same blurry behavior with the [original Learn theme](http://learn.netlify.app/)?

yes

**Comment by McShelby** [comment]
Thanks. So at least my butchery since the fork wasn't the cause.
