### ISSUE TITLE
When used in GitHub Pages: "baseUriFull is not defined"

### ISSUE THREAD

**Issue by hugograf** [McShelby/hugo-theme-relearn#763]
If I start locally with `hugo server`, everything works as desired. The same built by a GitHub action does not work as expected. The search function does not work. When I activate the console I see `baseUriFull is not defined`. Unfortunately I can't tell since which version I have this error.

- GitHub Repository: [GT-User-Manual](https://github.com/grafioschtrader/gt-user-manual)
- Website: [GT](https://grafioschtrader.github.io/gt-user-manual/de/intro/index.html) used as GitHub Pages
 
Is it a bug in hugo-theme-relearn or do I have any missing settings?

**Comment by McShelby** [comment]
You are missing an essential [Hugo setting](https://gohugo.io/hosting-and-deployment/hosting-on-gitlab/#baseurl)

**Comment by hugograf** [comment]
I checked the `baseURL` in [config.toml](https://github.com/grafioschtrader/gt-user-manual/blob/master/config.toml) first. This is set.

**Comment by McShelby** [comment]
This was already fixed in #724. While it's not officially released, you can either wait or use the HEAD of the main branch of this repo.
