### ISSUE TITLE
Typo in editButton?

### ISSUE THREAD

**Issue by cagix** [McShelby/hugo-theme-relearn#765]
Is there a typo in 
https://github.com/McShelby/hugo-theme-relearn/blob/eaabbfd6ef202ac4c55ee6bd228082c27b290b53/layouts/partials/topbar/button/edit.html#L16

Shouldn't this read `editURL`?

**Comment by McShelby** [comment]
Hi @cagix, thanks for paying attention to my butchery.

This time it was by intention:

> When using the isset function you must reference the key using lower case. See the previous example.

See https://gohugo.io/functions/collections/isset/

**Comment by cagix** [comment]
ah, i see! sorry for the noise!

**Comment by McShelby** [comment]
Better this way instead of introducing a bug.
