### ISSUE TITLE
tables pushing entire left-handside menu down

### ISSUE THREAD

**Issue by holene** [McShelby/hugo-theme-relearn#766]
I'm adding a few tables which are being populated from a `json` through a shortcode and a couple of partials I've made. The setup is really simple, but it does something really weird with the left hand side menu bar. Consider the Gif illustrating the problem and a [MWE repo](https://github.com/holene/hugo-relearn-table-error) with the associated code. 

Is there something major I'm missing with the shortcode? 

![relearn-tables](https://github.com/McShelby/hugo-theme-relearn/assets/4199918/5ca5d0c9-b9cc-4374-bd29-8abf66301194)

**Comment by McShelby** [comment]
Your HTML is invalid. Check it with https://validator.w3.org/
