### ISSUE TITLE
links to h4 headings not working

### ISSUE THREAD

**Issue by skureal** [McShelby/hugo-theme-relearn#769]
Hi team!

First of all I would like to thank you for the great work on `hugo-theme-relearn` theme! It worked out of the box for me on my very first `hugo` project.

However, I still have 2 small issues left and would like to address them separately. For the first one I'm not sure, if it is a `hugo-theme-relearn` or `hugo` limitation.

I don't get links to h4 heading working. 
In my `_index.md` I got links like:

`[msTimeStamp](#msTimeStamp)` which links to `#### msTimeStamp` in same document
`[Summary Table](#summary-table)` which links to `### Summary Table` in same document

Links up to h3 are working in the browser viewing the `public` folder content. Level h4 are not going anywhere.
The browser shows the link for h4 as:
`http://localhost:1313/srt/srt-statistics/#msTimeStamp` but clicking on it doesn't get my anywhere. Tested multiple browsers.

`http://localhost:1313/srt/srt-statistics/#summary-table` jumps to `### Summary Table` in browser window on same page.

Anyone has an idea, where this limitation comes from? Or how to solve it? Any input is appreciated.

Many thanks and best regards!

**Comment by McShelby** [comment]
>  It worked out of the box for me on my very first hugo project.

Congratulations! Not everyone masters this in the first attempt.

> [msTimeStamp](#msTimeStamp) which links to #### msTimeStamp in same document

That's wrong, as the id is case sensitive. Hugo generates `#mstimestamp`.

You can see what Hugo generates either by looking into the source code using your browsers dev tools or by just clicking the anchor icon next to the heading. This will copy the full link into your clipboard.

**Comment by skureal** [comment]
Thanks so much @McShelby ! 
You are absolutely right! It was just by chance, that the h3 headings in the markdown already had `[LowerCase](#lowercase)`  links, while the h4 headings were imported and used mixed lower & capital letters in the link. 
Time for me to dig into regular expressions and script those links to correct format before feeding hugo.
Time for you to close this ticket with the satisfaction of being of help to someone.

**Comment by skureal** [comment]
If anybody else will run into this in future, please find the bash script, which solved the issue below.

It is converting `[lowerUpper](#lowerUpper)` type of links within a markdown file to all lowercase in the `(#link)` part: `[lowerUpper](#lowerupper)`

**Warning:** don't use it in production environments, unless you checked the script and understand what it does or even improve it. If you are unsure, press `n` when asked to not overwrite your original file. A new file is written instead.

Call the script with a filename as input: `./lower-case-link-converter.sh filename.md`

Content of `lower-case-link-converter.sh` : 

```bash
#!/bin/bash

# Check if filename is provided as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 filename.md"
    exit 1
fi

filename="$1"
new_filename="${filename%.md}_new.md"

# Check if the file exists
if [ ! -f "$filename" ]; then
    echo "File not found: $filename"
    exit 1
fi

# Function to convert internal links
convert_internal_links() {
    sed -E 's/\[([^]]+)\]\(#([^)]+)\)/[\1](#\L\2)/g' "$1"
}

# Replace internal links in the file
convert_internal_links "$filename" > "$new_filename"

# Ask user whether to save the new file with corrected links
read -p "Do you want to save the new file with corrected links? This overwrites the original file. Press (n) to save to a different filename. : (y/n): " choice

case "$choice" in
    y|Y)
        mv "$new_filename" "$filename"
        echo "File saved as $filename"
        ;;
    n|N)
        echo "New file saved as $new_filename"
        ;;
    *)
        echo "Invalid choice, new file saved as $new_filename"
        ;;
esac

```

Make the file executable  `chmod +x lower-case-link-converter.sh` and go for it!
