### ISSUE TITLE
5.24.0: _default/list.html throws error

### ISSUE THREAD

**Issue by cagix** [McShelby/hugo-theme-relearn#773]
After updating from 5.23.2 to 5.24.0, `_default/list.html` stopped working:

```
ERROR render of "section" failed: "/usr/local/share/pandoc/hugo/hugo-theme-relearn/layouts/_default/list.html:1:4": execute of template failed: template: _default/list.html:1:4: executing "_default/list.html" at <partial "_main.hugo" .>: error calling partial: "/usr/local/share/pandoc/hugo/hugo-theme-relearn/layouts/partials/_main.hugo:3:4": execute of template failed: template: partials/_main.hugo:3:4: executing "partials/_main.hugo" at <partial "output-partial.hugo" (dict "base" "header" "page" . "parameter" . "outputFormat" $outputFormat)>: error calling partial: "/usr/local/share/pandoc/hugo/hugo-theme-relearn/layouts/partials/output-partial.hugo:13:8": execute of template failed: template: partials/output-partial.hugo:13:8: executing "partials/output-partial.hugo" at <partial (printf "%!s(MISSING).%!s(MISSING)" $base $suffix) $parameter>: error calling partial: "/usr/local/share/pandoc/hugo/hugo-theme-relearn/layouts/partials/header.html:33:10": execute of template failed: template: partials/header.html:33:10: executing "partials/header.html" at <warnf "%!q(MISSING): DEPRECATED frontmatter 'menutitle' found, use 'linktitle' instead" $page.File.Filename>: error calling warnf: "/pandoc/temp/subdir/leaf/_index.md": DEPRECATED frontmatter 'menutitle' found, use 'linktitle' instead
```

(Hugo v0.122.0, Hugo-Relearn-Theme 5.24.0)

**Comment by cagix** [comment]
After a short investigation: My script was using the option `--panicOnWarning`, after relaxing this everything goes back to normal. It seems to be about deprecating `menutitle`. (Strangely, other warnings about missing links did not lead to an error when using `--panicOnWarning`.)

However, the documentation (https://mcshelby.github.io/hugo-theme-relearn/cont/frontmatter/index.html#using-a-custom-title-for-menu-entries) seems to recommend still `menuTitle`? Also in the release notes there is no mention of deprecting `menuTitle`?

**Comment by McShelby** [comment]
The menuTitle frontmatter will be removed in #714. The warning is already there to inform the user early as the alternative `LinkTitle` is already supported.

But you are correct, the docs still mention this, which is a bit inconsistent. I am still thinking about, which way to go, either remove the warning or rewrite the docs...

**Comment by cagix** [comment]
I'd prefer the deprecation warning, but this should be reflected somehow in the docs :)

**Comment by McShelby** [comment]
I've updated the docs but will not make a new release for it.

Anyways, thanks for reporting. 5.24.0 was far to long in development hell, so I got a bit lost.

**Comment by cagix** [comment]
@McShelby Thanks for your amazing work! Very much appreciated :)
