### ISSUE TITLE
Multiple documentation, how to get the menu based on the guide I have chosen

### ISSUE THREAD

**Issue by bitlab-code** [McShelby/hugo-theme-relearn#776]
I have a folder structure as shown in the picture, where inside the "guide" folder I have multiple subfolders, each containing a guide. I would like the menu on the left to display only the tree structure of the guide I am navigating through.

Can someone provide support for this?
Thanks.
![issue](https://github.com/McShelby/hugo-theme-relearn/assets/19858243/408b57f2-bb44-4b9f-8f4e-449a4cb63243)

**Comment by McShelby** [comment]
As I understand you, you want to get rid of the top level structure in the menu?

Currently, this isn't possilbe. The theme generates the menu for the whole file tree starting at your `content/` directory.

Although, I have some vague future plans in my head, to make all menus configurable and even allow arbitrary number of menus.

**Comment by bitlab-code** [comment]
ok, thank you for quickly response
