### ISSUE TITLE
Feature request: Support for music notation and math notation

### ISSUE THREAD

**Issue by ScrumpyJack** [McShelby/hugo-theme-relearn#780]
Loving this theme, and the mermaid integration.

Would love to see abc notation and math notation renderers suppoted too, which mermaid doesn't do.

For abc notation https://github.com/paulrosen/abcjs
For LaTeX, MathML, etc https://github.com/mathjax/MathJax-src

I realise this is a big ask. Is this on any roadmap?

This would enable me to publish my hedgedoc documents properly

Edit: I see MathJax is already supported. Yay!

**Comment by McShelby** [comment]
Thanks for the input. As you already found out, Math is already supported.

Note notation is such a niche, that I will not include it in the theme.

But taking the Math, Mermaid and OpenAPI as a starting point, it should be [fairly easy to integrate](https://mcshelby.github.io/hugo-theme-relearn/basics/customization/index.html#own-shortcodes-with-javascript-dependencies) it on your own.
