### ISSUE TITLE
link: fix build error for multilang environments

### ISSUE THREAD

**Issue by dogweather** [McShelby/hugo-theme-relearn#789]
I get this error with main or the previous release.

```partials/shortcodes/link.html:44:25: executing "partials/shortcodes/link.html" at <.Resources.Get>: can't evaluate field Resources in type page.Site```

**Comment by McShelby** [comment]
That*s a bit odd. Can you please create an example that reproduces?

**Comment by McShelby** [comment]
I couldn't reproduce it yet but found a bug that (apprently) slipped thru tests.

Please update to the repos HEAD to check if this fixed it for you.
