### ISSUE TITLE
Errors trying to run exampleSite

### ISSUE THREAD

**Issue by satyagrahi** [McShelby/hugo-theme-relearn#801]
Hi,
Created a new site and downloaded the zip from github to /theme
Copied hugo.toml from theme to head.
Then copied content to /content.

Many errors preventing Hugo from running:
"piratify" errors (deleted all _index.pir.md files)
"button" template not found (deleted line)
"multiconfig" shortcode not found ...

Please advise.
Thanks

**Comment by McShelby** [comment]
[Use the docs](https://mcshelby.github.io/hugo-theme-relearn/basics/installation/index.html) how to properly install the theme and create your first content.

**Comment by satyagrahi** [comment]
Thanks, i am still getting errors:

`$ hugo new basics/first-content.md        
Error: process: readAndProcessContent: "/home/relearn2/content/basics/_index.md:4:10": unmarshal failed: toml: incomplete number`

`hugo new basics/second-content/_index.md
Error: process: readAndProcessContent: "/home/relearn2/content/basics/_index.md:4:10": unmarshal failed: toml: incomplete number`

The files were still created and i edited them. Then:

`» hugo serve
Watching for changes in /home/relearn2/{archetypes,assets,content,data,i18n,layouts,static,themes}
Watching for config changes in /home/relearn2/hugo.toml, /home/relearn2/themes/hugo-theme-relearn/hugo.toml
Start building sites … 
hugo v0.123.7-312735366b20d64bd61bff8627f593749f86c964+extended darwin/amd64 BuildDate=2024-03-01T16:16:06Z VendorInfo=brew

Built in 902 ms
Error: error building site: process: readAndProcessContent: "/home/relearn2/content/basics/_index.md:4:10": unmarshal failed: toml: incomplete number
`

**Comment by McShelby** [comment]
Error messages are your friend.

**Comment by satyagrahi** [comment]
Yes they are, but its at the end of a long day.

**Comment by satyagrahi** [comment]
In the basics/_index.md that is created by following the documentation, replace the X "weight = X" with a number

**Comment by McShelby** [comment]
I've revamped the installation instructions and the archetype templates generate a functional page without the need of editing any files (besides `hugo.toml`). Give it a try.

**Comment by satyagrahi** [comment]
Thank you. It flowed so much faster today. All setup and ready to upload the content.

**Comment by McShelby** [comment]
Thanks for trying it out! Much appreciated.
