### ISSUE TITLE
build: update all available actions to nodejs 20

### ISSUE THREAD

**Issue by McShelby** [McShelby/hugo-theme-relearn#802]
Painful. GitHub deprecates actions stuff constantly, so it's always necessary to adjust.

Probably a good future step is, to consolidate action usage by relying on well maintained ones.

**Comment by McShelby** [comment]
Hm, I always thought,  this is only used  for file  dependencies.

Here  (see my changeset above), it would need to change code in source files. Are you sure this is doable with dependabot? Do you have an example repo (not necessarily yours) where I can take a look?

Anyways this does not help with non-maintained actions.

**Comment by cagix** [comment]
well, it handles the workflow/action versions quite well... it even supports [docker, gradle, npm, ...](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)

have a look at my dungeon project, where we use it for workflows/actions and gradle: https://github.com/Dungeon-CampusMinden/Dungeon/blob/master/.github/dependabot.yml

here is how to configure your repo (you'll need a config file plus some settings in your repo): https://docs.github.com/en/code-security/dependabot/working-with-dependabot  here another example of updating just the gh-actions in my workflows: https://github.com/Compiler-CampusMinden/CB-Vorlesung-Bachelor/blob/master/.github/dependabot.yml

it will add a pull-request for each detected update, and in this pull-request it gives you many options: you could accept/merge, you could tell dependabot to ignore this specific dependency, ...

**Comment by cagix** [comment]
here an example pull-request, where i declined the suggested update: https://github.com/Programmiermethoden-CampusMinden/student-support-code-template/pull/1

**Comment by McShelby** [comment]
@cagix Thanks for the hints. I'll take a look into it.

**Comment by cagix** [comment]
you can fork https://github.com/dependabot/demo to try your config :)
