### ISSUE TITLE
scrollbar: scroll bar in side menu gets stuck in dragged state on mobile

### ISSUE THREAD

**Issue by Nuc1eoN** [McShelby/hugo-theme-relearn#808]
Hi :)

If you go to e.g. https://mcshelby.github.io/hugo-theme-relearn/basics/index.html on the mobile phone (chrome) and scroll the left side menu by dragging its contents it works fine.

However upon dragging the _scrollbar_ it will forever remain in the "dragged scrollbar" state until a page reload happens. Scrolling the menu the "normal" way is no longer possible and the scrolling direction is effectively reversed.

This has been an issue since at least #243. You've had it successfully fixed for the main page, but it never got fixed for the sidemenu scroll bar (on my side at least). Just never came around to report it.. my fault:)

Are you able to reproduce @McShelby ?

**Comment by McShelby** [comment]
Hi @Nuc1eoN, thanks for reporting.
I can reproduce it but I can not promise to fix this - we'll see on further investigation.

> You've had it successfully fixed for the main page

I wouldn't say that I fixed it, as I completly removed the scrollbar implementation for the main page ;-)

This is not an option with the menu and the toc, as I hate some of the browsers native implementation and it is also non themeable in some cases.

**Comment by McShelby** [comment]
I've pushed a change. LGTM but wanted to wait with the next release until I have your feedback.

**Comment by Nuc1eoN** [comment]
Oh that's great, well done! Probably hasn't been a lot fun fixing this ;)

For me it works very well now, definitely acceptable!

There is a small "Schönheitsfehler" when dragscrolling in a fast motion and basically letting go during the move; it would behave a little erratic or even move to the other side. Probably because the drag move and is not so well compatible (or interfereing) with the "intertia" of android smartphone scrolling (the feature that makes it continue to scroll after letting go). Maybe that could be "turned off" for drag scrolling?
I wonder if that happens on your side, too?

Anyways to me that is just a nit pick! The overall thing works now and is much more usable than before. So if it's a pain (or impossible) to fix I won't insist :)

So other than that LGTM :+1:

**Comment by McShelby** [comment]
@Nuc1eoN  Thanks for the feedback.

I've tested this in the Chrome devtools on desktop and with a Google Pixel 6a.

Even for long menus scrolling was good and I couldn't reproduce. As I couldn't reproduce any jumping behavior it still felt a bit different to the scrolling of the main content. But that was totally acceptable.

I also briefly checked the [issue list](https://github.com/mdbootstrap/perfect-scrollbar/issues) for some hints but wasn't successful as it is really crowded there.

The codebase of the perfect-scrollbar is a tough one to butcher, that's for sure.

**Comment by Nuc1eoN** [comment]
Uh oh yeah indeed pretty crowded. I think I might have found the bugreport for the initial issue: https://github.com/mdbootstrap/perfect-scrollbar/issues/20
But your fix is probably better.

Yeah so for me this is totally acceptable, I'm ok with releasing! :)

**Comment by McShelby** [comment]
As I can't reproduce your second issue  (even on an Iphone), we now have the following choices:

- you add a clip here, so I can see how bad it really looks and decide afterwards how to proceed                                                                                                                                                      
- leave it as is (relying on your evaluation)

**Comment by McShelby** [comment]
Okay, even the Chrome mobile simulation behaves like this.

This only happens, if the handle is used. Touch scrolling in the container behaves as expected.

**Comment by McShelby** [comment]
I've removed parts of my butchery - now that I understand the code better. Seems, the scrollbar's options are the better way to deal with our issues.

Not so spiffy as before when scrolling but now reliable in the way the bar behaves.

Check it out!

**Comment by McShelby** [comment]
@Nuc1eoN Could you check out the latest fix?

**Comment by Nuc1eoN** [comment]
Hi @McShelby that looks good to me, well done! :smile: 

I have indeed noticed that is is not as 'spiffy' as before while drag scrolling the content and I think it is a worthwhile compromise.
