### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by perfectdarkmode1** [McShelby/hugo-theme-relearn#818]
Is there away to change the background color? I only saw away to toggle light/dark theme but not change the actual color of the main background.

**Comment by McShelby** [comment]
https://mcshelby.github.io/hugo-theme-relearn/basics/generator/index.html

**Comment by perfectdarkmode1** [comment]
Thanks. One more question. The font on mobile is different than the font on desktop. I can't find a setting to fix this.

**Comment by McShelby** [comment]
No. The theme uses the same font regardless of your device.

**Comment by perfectdarkmode1** [comment]
For some reason, my site is using a different font on mobile. Must be a bug? Do you know if this would be a problem with Hugo itself or with the relearn theme? You can see at perfectdarkmode.com. I have never had this issue before lol

**Comment by McShelby** [comment]
This is a problem on your side with your CSS. You've changed the font in your `git` variant to `Open Sans` but did not link to those fonts. Therfore the browser uses default system fonts which seems to be different between desktop and mobile.

**Comment by perfectdarkmode1** [comment]
Is that font built into the relearn theme? Or should I pick one that relearn uses since I don't have any custom fonts installed?

**Comment by McShelby** [comment]
No, the `Open Sans` font is not built into the Relearn theme. But you should know best, as the `git` variant you are using is not part of the official theme release.

**Comment by perfectdarkmode1** [comment]
So would I just download an open sans font and put it in a specific folder?

**Comment by perfectdarkmode1** [comment]
I actually just commented out the font and it fixed it and just went to the default font. Works for me. Thanks!
