### ISSUE TITLE
Resources migration seems not to work with a custom path in the baseURL

### ISSUE THREAD

**Issue by kreutziger** [McShelby/hugo-theme-relearn#826]
Hello,

really like the theme and work with it for quite some time hosted on GitHub Pages. I upgraded lately from 5.24.0 to 5.27.0. In 5.25.0 the attachments to resources migration did not work with GitHub Pages. I have the baseURL setting in-use and the `RelPermalink` is not working[0]. If I set this to `Permalink` I can download the documents again.

RelPermaLink: <host>/<baseURL|Path>/<path>
PermaLink: <host>/<path>

Hope this explains my issue.

Regards,

[0] https://github.com/McShelby/hugo-theme-relearn/blob/main/layouts/partials/shortcodes/resources.html#L54

**Comment by McShelby** [comment]
It works for me with GitHub Pages and a `baseURL` set to a subdirectory (https://mcshelby.github.io/hugo-theme-relearn/shortcodes/resources/index.html).

So there must be some thing going on with your issue. Could you provide a link to your repo?

**Comment by kreutziger** [comment]
So, I tested it again and the combination of the `baseURL` and `canonifyURLs = true` settings brings up the error. As the hugo documentation mentions the canonifyURLs[0, 1] setting to be deprecated, I will see how to deactivate it.

[0] https://gohugo.io/content-management/urls/#canonical-urls
[1] https://github.com/gohugoio/hugo/issues/4733

**Comment by McShelby** [comment]
I'ld also recommend to deactivate it. Hugo wants to deprecate this setting in the future and I also removed it from the docs configuration. 

Usually, this should not be an issue for your installation.

**Comment by McShelby** [comment]
So just to make it clear: `canonifyURLs=true` is deprecated, and not working with this theme.

The theme already functions correctly without this setting.
