### ISSUE TITLE
math: allow to work with Hugo's passthrough configuration

### ISSUE THREAD

**Issue by Kevinanny** [McShelby/hugo-theme-relearn#832]
When I was using a '\\' to break line in array environment using mathjax, it can't break line properly. The reason is the last \ was escaping. As i know, hugo didn't support escaping configuration for now. Some people say Katex can solve this issue. Some say that is bug from the render. But i know less to figure it out. I guess the author may could solve this from the theme side. By the way, would this theme will consider support Katex in the future?

**Comment by McShelby** [comment]
I am not a MathJax nerd either. Please provide your formula in source code and expected output (as gif).

The theme will not support Katex. One math library is enough but you could write a `katex` shortcode yourself.

**Comment by Kevinanny** [comment]
Thank you for the reply very much! Here is my issue.

To keep consistence between markdown and latex, my mathjax configure is :

```
<script>
  MathJax = {
    tex: {
      packages: ['base', 'ams'],        // extensions to use
      inlineMath: [['$','$'], ['\\(','\\)']], // allow using $ $ to input inline equation
      displayMath: [['$$','$$'], ['\[','\]']], //allow using $$ $$ to display equation
      processEscapes: true,      // use \$ to produce a literal dollar sign
    }
  };
  </script>

<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-svg.js">
</script>
```


My formula source code is :
```
$$\left|
\begin{array}{cc}
a & b \\
c & d
\end{array}\right|$$
```
The display should be:
![expected](https://github.com/McShelby/hugo-theme-relearn/assets/59832468/570292ca-ab4a-4e16-a891-1e36e3814248)

While it seems there is a '\\' escaping, that means '\\\\' won't break line, so the actual display is 
![infact](https://github.com/McShelby/hugo-theme-relearn/assets/59832468/814dcec3-1c9e-476d-a5d2-b707c08a17cf)

Some people implied that '\\\\\\\\' could breakline, it did work. However, it will break the consistence between markdown and latex. Change formula one by one is very annoyed.

**Comment by McShelby** [comment]
Thanks for providing. I'll take a look into it.

**Comment by McShelby** [comment]
With this fix, your example should work without a shortcode or codefence if adhering to the [passthrough configuration](https://mcshelby.github.io/hugo-theme-relearn/shortcodes/math/index.html#passthrough-configuration).

I've reused your example on the above linked docs page.
