### ISSUE TITLE
Footnote fragment IDs in notices collide with those in the main content

### ISSUE THREAD

**Issue by alan-strohm** [McShelby/hugo-theme-relearn#836]
Footnotes inside notices generate fragments which collide with the fragments generated by footnotes outside the notice:

```
Text outside notice[^f1]
[^f1]: Footnote outside notice

{{% notice style="info" %}}
Text inside notice[^f2]
[^f2]: Footnote inside notice
{{% /notice %}}
```

Clicking on the link after "Text outside notice" takes you to "Footnote inside notice".  It should take you to "Footnote outside notice". Clicking on the return link from "Footnote inside notice" takes you to "Text outside notice".    It should take you to "Text inside notice."

**Comment by McShelby** [comment]
There was an attempt to fix this in #547 which had to be reverted in #555 because it did not work for all users.

I don't know of a solution that will work in both caes with and without `renderer.unsafe=true`
