### ISSUE TITLE
docs: fix oddities in the installation tutorial

### ISSUE THREAD

**Issue by stevenroose** [McShelby/hugo-theme-relearn#840]
I'm following the [installation tutorial](https://mcshelby.github.io/hugo-theme-relearn/basics/installation/index.html) which instructs to make a first chapter and two pages, but it doesn't work as the page says it should.

Only the chapter's menu item is created, but the pages menu items are not and there is no collapsable menu. Checked in Firefox and Chromium.

I'm using the `5.27.0` tag, not master.

**Comment by McShelby** [comment]
Please remove `draft = true` from the newly created pages.

**Comment by McShelby** [comment]
This is because Hugo nowadays overrides the default archetype.

**Comment by McShelby** [comment]
I've revamped to installation tutorial for a smoother experience.

Check it out: https://mcshelby.github.io/hugo-theme-relearn/basics/installation/index.html
