### ISSUE TITLE
frontmatter: move frontmatter config for exampleSite out of root

### ISSUE THREAD

**Issue by darren-oxford** [McShelby/hugo-theme-relearn#843]
Please don't include frontmatter.json in the theme, it results in front matter being incorrectly configured.

It creates a front matter configuration that has an example site and paths to windows executable that of course does not work on Linux or Mac.

**Comment by McShelby** [comment]
Thanks for the input.

Would it work for you, if the `frontmatter.json` is moved inside the `exampleSite` directory?

**Comment by darren-oxford** [comment]
Thanks for the quick reply, I have done a quick test and yes, moving the `frontmatter.json` file to the `exampleSite` directory prevented VSCode from picking it up when including the theme. I was then able to open the FrontMatter dashboard and initialize the project as expected.

You may also want to add the `.frontmatter` directory to your `.gitignore`.

Thanks for the great theme.

**Comment by McShelby** [comment]
Done. Thanks for the input.
