### ISSUE TITLE
alias: index.html has displays error in content

### ISSUE THREAD

**Issue by rcastley** [McShelby/hugo-theme-relearn#851]
TBH, I don't know if this is a `hugo` or `relearn` theme issue

Running `hugo v0.125.5+extended darwin/arm64 BuildDate=2024-05-01T15:22:11Z` with latest `relearn` theme `require github.com/McShelby/hugo-theme-relearn v0.0.0-20240430200804-ab4cd9b6a78a // indirect`.

When you run locally, or publish on GitHub pages. The root `index.html` contains some random text that flashes up before the redirect.

The contents of `index.html` both locally and remotely currently contain:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex">
    <meta http-equiv="refresh" content="0; url=./en/index.html">
    <title>/en/index.html</title>

    <link href="./en/index.html" rel="canonical">%!(EXTRA string=/en/index.html)
  </head>
</html>
```

The string `%!(EXTRA string=/en/index.html)` is somehow being added.

Is anyone else seeing this and apologies if this is not a `relearn` issue.

Many thanks,
- Robert
-

**Comment by McShelby** [comment]
Thanks for the find. This broke in #841. Happily, the functionality isn't affected.
