### ISSUE TITLE
theme: fix showVisitedLinks in case Hugo is configured to modify relative URLs

### ISSUE THREAD

**Issue by philippbruhin** [McShelby/hugo-theme-relearn#86]
First of all thank you @McShelby for sharing this theme with the world without asking for something in return. I am new to Hugo and I am not quit sure if it is a bug or a misconfiguration on my part.

As I saw the [Hugo Learn](https://learn.netlify.app/en/cont/archetypes/) theme does provide "showVisitedLinks" as follows:

![09-09-_2021_12-59-31](https://user-images.githubusercontent.com/7021907/132674506-005cf0d7-3349-4856-9dbd-400a935343c7.png)

This behavior seems not to be the case on [Hugo Relearn](https://relearn.netlify.app/cont/archetypes/):

![09-09-_2021_13-00-15](https://user-images.githubusercontent.com/7021907/132674494-96404963-b2f7-497a-89c9-da43ad4b57a9.png)

If I understand the setup correct, then the code of the theme above is as follows:

```
[params]
  showVisitedLinks = true
```
See also https://github.com/McShelby/hugo-theme-relearn/blob/main/exampleSite/config.toml

Am I on the wrong track or should the tick appear when I have `showVisitedLinks = true`?

**Comment by McShelby** [comment]
You're right, it should appear if you set `showVisitedLinks = true`. So  you've found a bug. ;-)

**Comment by McShelby** [comment]
This happens at least if you set `relativeURLs=true` in your `config.toml` (but probably also in this case matcornic/hugo-theme-learn#468) . This is the case here with the theme's exampleSite.

**Comment by philippbruhin** [comment]
Thank you for fixing this quickly. Now it works like a charm :checkered_flag: Very appreciated :pray:
