### ISSUE TITLE
"raw HTML omitted" again

### ISSUE THREAD

**Issue by postb99** [McShelby/hugo-theme-relearn#865]
Hello,

Juste updated the theme, there are not so many commits on main branch so I was surprised my included pages did not work and I saw "raw HTML omitted" in html output. Well, my last follow of theme changes goes back to May 1st, a month ago, LOL.

Fortunately this was solved again by enabling this again in hugo.toml:

```
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```

My website's _index.md page includes other pages with relative path:

```
{{% include "./includes/last_thought.md" true %}}

{{% include "./includes/last_poems.md" true %}}
```

In /includes/_index.md I have put only this because this folder contains all the hidden pages of the site so thet I have one place for often changing content:

```
+++
title = "Inclusions"
hidden = true
+++
```

In the two aforementioned included .md pages there is a very simple header:

```
+++
title = "Derniers ajouts"
+++
```

Then some text with some other include or links to other pages. No html.

What do you think of this behavior? I also noticed that I still used Hugo 0.124 so upgraded to latest 0.126.2.

![image](https://github.com/McShelby/hugo-theme-relearn/assets/173565/e9697376-3b88-4dcc-ad5c-bd493ffe1943)

**Comment by McShelby** [comment]
Hi Barbara, thanks for reporting.

This time "raw HTML omitted" comes from your usage of the `include` shortcode, which wasn't the cause in your older issue.

Sadly `include` currently behaves this way and to make it work for you right now is to use `unsafe=true'

As they say in the Hugo forum:

> It is not unsafe if _you_ are in control of your content.
