### ISSUE TITLE
CSS: From static to assets

### ISSUE THREAD

**Issue by escou64** [McShelby/hugo-theme-relearn#868]
Hello,

I updated the theme and saw that I now had to move the css files from _static/css_ to _assets/css_. This works normally for my theme-color.css file, but it's now impossible to add a _custom.css_ file: it is never taken into account. So I tried adding my styles directly to my _theme-color.css_ and it works.

Here are the changes I made without success:

- A new file _layouts/partials/custom-header.html_:
```
<link rel="stylesheet" href="/css/custom.css">
```
- A new file _assets/css/custom.css_:
```
/* Style example */
h1 {
  font-size: 200px;
}
```

This perfectly worked in the old version. How to add a _custom.css_ file with the new one ? I have not seen any paragraph on this topic in the documentation. Are there any new specific modifications to be made ?

**Comment by McShelby** [comment]
You only have to move your _color variant stylesheets_ over to `assets`. Everything else can reside in `static`.

So the correct way for you would be, to move your `custom.css` back to `static`.

**Comment by escou64** [comment]
Thanks for your answer: it seems to correctly work right now.
I was convinced that I had tested this case ... sorry for the inconvenience!
