### ISSUE TITLE
Is there a way to change default images directory?

### ISSUE THREAD

**Issue by perfectdarkmode1** [McShelby/hugo-theme-relearn#869]
I would like to change my default images directory to content/images/ I tried adding imagesDir = "content/images" under [params] in config.toml which didn't work. 

So I was wondering if this is possible in relearn?

Thanks!

**Comment by McShelby** [comment]
The theme does not provide such a mechanism and I haven't seen any other theme providing this.

Seems more like a general Hugo question and you might find an answer in the official [Hugo forum](https://discourse.gohugo.io/).

**Comment by perfectdarkmode1** [comment]
Thank you!
