### ISSUE TITLE
Can't get the logo to bring me to homepage.

### ISSUE THREAD

**Issue by perfectdarkmode1** [McShelby/hugo-theme-relearn#871]
Hello, I disabled my home button by setting disableLandingPageButton to true. I would like to set my logo to bring me home. Currently, pressing on the logo does nothing. Site is at davidvargas.xyz repo is at https://github.com/perfectdarkmode1/davidvargasxyz.github.io

**Comment by McShelby** [comment]
Take a look into the [logo partial](https://github.com/McShelby/hugo-theme-relearn/blob/6f24d34f44426f365419ae125eb94f12ff0510c7/layouts/partials/logo.html#L44) of the example page how it can be achieved.

**Comment by perfectdarkmode1** [comment]
Thanks!
