### ISSUE TITLE
variant: auto variant references potentially wrong chroma style

### ISSUE THREAD

**Issue by mroszkobt** [McShelby/hugo-theme-relearn#873]
There are no chroma-zen-light.css and chroma-zen-dark.css assets.

Yet when `auto` is used with `zen-light` and `zen-dark`, chroma-auto.css will be generated with @import states pointing to the non-existent files

**Comment by McShelby** [comment]
Thanks for reporting. Just to make debugging easier, could you include your config.toml?

**Comment by mroszkobt** [comment]
https://gitlab.com/kicad/services/kicad-dev-docs/-/blob/master/config.toml?ref_type=heads
