### ISSUE TITLE
Search function generates invalid urls for both file and server mode?

### ISSUE THREAD

**Issue by JohannOberdorfer** [McShelby/hugo-theme-relearn#874]
I just migrated my documentation service to the latest relearn-theme version 6.0.0.
Hugo version is on 0.121.0 extended.

All looks good except for the search function:

Here the generated links are invalid as they contain the **'undefined'** string somewhere in the url.
Such an url e.g. might look like:
```
http://localhost:1313/01-catia/d-catia-macros/d-drw/undefined/01-catia/d-catia-macros/d-drw/
```
Manually removing the **'undefined/'** string fragment works.

I als discovered that I needed to add the new parameter to the site configuration such as:
**disableExplicitIndexURLs = true**
Without this parameter, the generated urls are very long (including redundant path information) plus including the **'undefined'** string.

Output configuration settings:
```
[outputs]
  home = ["html", "rss", "print", "search", "searchpage"]
  page = ["html", "rss", "print", "embed"]
  section = ["html", "rss", "print"]
```

For the moment, the search function does not work.
Maybe I am missing another parameter setting to fix this issue or is this a general problem introduced in the recent version ?

**Comment by McShelby** [comment]
Hi Johann. Without a sample repository it is impossible to say, what's wrong here.

`disableExplicitIndexURLs` isn't new to the theme and not necessary to have a working page. It's only for cases where you want to use the generated pages serverless (via the file system).

**Comment by JohannOberdorfer** [comment]
Hi Sören,
thank you for your quick reply.

I could fix the problem on my side!
It used a customized stylesheet.html which was out of date and this caused my problem.
Arr - shame on me, it was purely my fault.

Looks good so far, I think you can close this issue!
Best regards
Johann

**Comment by McShelby** [comment]
Awesome. Good to hear.

Anyways, instead of providing your own `stylesheet.html` partial (and copying over theme internals that may break in an upcoming update) you may be better advised to overwrite the `custom-header.html` partial.

The theme provides an empty partial so you add anything you want which will be put in each page's `<head>`.
