### ISSUE TITLE
theme: remove warning for usage of .Site.IsMultiLingual

### ISSUE THREAD

**Issue by cagix** [McShelby/hugo-theme-relearn#877]
@McShelby Just to let you know: Hugo wants to replace `.Site.IsMultiLingual` with `hugo.IsMultilingual`.

Upgraded to Hugo v0.130.0 and got some warning regarding the use of `.Site.IsMultiLingual` in Relearn:

<img width="1085" alt="Screenshot 2024-07-29 at 16 42 15" src="https://github.com/user-attachments/assets/79bab42c-ad94-4d42-8e09-5258e9a6eebd">

Edit: replaced the copy&paste from GitHub workflow w/ a screenshot highlighting the areas in question

**Comment by McShelby** [comment]
Thanks for the heads-up. There's alread a PR for this - and a comment why it's not merged yet ;-)

https://github.com/McShelby/hugo-theme-relearn/pull/817#issuecomment-2018864953

**Comment by McShelby** [comment]
Merged in branch 7.0.0 (not public)
