### ISSUE TITLE
link: link resolving stopped working in certain configurations

### ISSUE THREAD

**Issue by cagix** [McShelby/hugo-theme-relearn#882]
Just upgraded to Relearn v6.1.0 and noticed Hugo's link resolution stopped working:

- Input: Link in Markdown source file: `[Record-Klassen]({{% relref "records" %}})`
- Output (expected): Relearn 6.0.0 and prior: `<a href="<baseURL>/modern-java/records.html">Record-Klassen</a>`
- Output (broken): Relearn 6.1.0: `<a href="records">Record-Klassen</a>`

Using Hugo v0.131.0 and `uglyurls: true`.

**Comment by McShelby** [comment]
Hi Cagix is this going away if you use 

````
useDefaultRelref = true
````

in your `hugo.toml`?

**Comment by cagix** [comment]
hmmm, tried it in combination with `uglyurls: true` and without `uglyurls` - the result is unchanged. hugo does not resolve the link given via `relref` shortcode anymore.

**Comment by McShelby** [comment]
Just to be more precise: You have to put the option into your params section like so:

````
[params]
useDefaultRelref = true
````

**Comment by cagix** [comment]
oh my 🙈 

can confirm, putting that `useDefaultRelref` in the params section does help. it seems to be working again :) 

thx! 🙏

**Comment by cagix** [comment]
hmmm, i've checked the notes before upgrading and didn't find any breaking changes, at least not regarding my use case. perhaps this is just a side effect?

**Comment by McShelby** [comment]
I didn't assume that it will break an installation :-(

Happily I added this escape hatch.

**Comment by McShelby** [comment]
I've inverted the name of the variable and the default link resolution without setting an option now behaves like before.

Thanks for reporting!

**Comment by cagix** [comment]
@McShelby thx 🙏👌
