### ISSUE TITLE
Cannot get rid of index.html from links

### ISSUE THREAD

**Issue by babar-raza** [McShelby/hugo-theme-relearn#894]
I am using the theme with its default settings. Despite extensive searching, I have been unable to remove index.html from internal links and, consequently, from the URLs. I have tried setting 'uglyURLs = false' and 'disableExplicitIndexURLs = true', but these settings do not seem to take effect.

**Comment by McShelby** [comment]
https://mcshelby.github.io/hugo-theme-relearn/basics/customization/index.html?search-by=disableExplicitIndexURLs

**Comment by McShelby** [comment]
`disableExplicitIndexURLs = true` works fine.

If you need further help, please provide a link to your repo.
