### ISSUE TITLE
mermaid: classDiagram breaks when using <<interface>>

### ISSUE THREAD

**Issue by koenyskout** [McShelby/hugo-theme-relearn#895]
When I create a mermaid diagram as follows (which works fine in mermaid's live editor), mermaid shows a "Syntax error in text" error on my hugo site.

````
```mermaid
classDiagram

class Foo {
  +a: int
}
<<interface>> Foo
```
````

The `<<interface>>` line is the culprit. I assume this is due to some HTML sanitization issue, where `<interface>` might be misinterpreted as a HTML tag.

**Comment by McShelby** [comment]
Thanks for submitting. I fixed it pushed it. Check it out.

**Comment by koenyskout** [comment]
Works perfectly, thanks!
