### ISSUE TITLE
docs: rename english pirate translation to avoid crash on rendering

### ISSUE THREAD

**Issue by jehoshua7** [McShelby/hugo-theme-relearn#90]
Yesterday I did a fresh install of the theme,

`git submodule add https://github.com/McShelby/hugo-theme-relearn.git themes/hugo-theme-relearn`

then used the commands I have previously used

`:~/Hugo$ cd mysite/themes/hugo-theme-relearn
:~/Hugo/mysite/themes/hugo-theme-relearn$ hugo server --source=exampleSite --themesDir=../..`

> Start building sites … 
hugo v0.88.1-5BC54738 linux/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
Error: Error building site: render of "sitemap" failed: execute of template failed: template: _default/sitemap.xml:2:4: executing "_default/sitemap.xml" at <partial "page-meta.go" .>: error calling partial: "/home/********/Hugo/mysite/themes/hugo-theme-relearn/layouts/partials/page-meta.go:8:50": execute of template failed: template: partials/page-meta.go:8:50: executing "relearn-structure" at <.node.RelPermalink>: error calling RelPermalink: runtime error: invalid memory address or nil pointer dereference
Built in 628 ms

renamed page-meta.go to page-meta.html

`$ hugo server --source=exampleSite --themesDir=../..`

> Start building sites … 
hugo v0.88.1-5BC54738 linux/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
Error: Error building site: render of "sitemap" failed: "/home/********/Hugo/mysite/themes/hugo-theme-relearn/layouts/_default/sitemap.xml:2:4": execute of template failed: template: _default/sitemap.xml:2:4: executing "_default/sitemap.xml" at <partial "page-meta.go" .>: error calling partial: partial "page-meta.go" not found
Built in 34 ms

Then modified sitemap.xml

`from {{- partial "page-meta.go" . }} to {{- partial "page-meta.html" . }}`

`$ hugo server --source=exampleSite --themesDir=../..`

> Start building sites … 
hugo v0.88.1-5BC54738 linux/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
Error: Error building site: render of "sitemap" failed: execute of template failed: template: _default/sitemap.xml:2:4: executing "_default/sitemap.xml" at <partial "page-meta.html" .>: error calling partial: "/home/********/Hugo/mysite/themes/hugo-theme-relearn/layouts/partials/page-meta.html:8:50": execute of template failed: template: partials/page-meta.html:8:50: executing "relearn-structure" at <.node.RelPermalink>: error calling RelPermalink: runtime error: invalid memory address or nil pointer dereference
Built in 33 ms

I also modified meta.html to `{{- partial "page-meta.html" . }}` , tried again, same error. I noticed there were a number of modifications in config.toml , but they all seemed multi-language focused and I don't use that. There was one new setting

`disableSeoHiddenPages = true`

and I added that in.

**Comment by jehoshua7** [comment]
As the config.toml from the theme was different, I commented out where I use my config.toml

`# Copy configuration
#cp ~/Hugo/Backup/config/config.toml ~/Hugo/mysite/themes/hugo-theme-relearn/exampleSite/config.toml`

and then re-installed everything from a bash file, then

`hugo server --source=exampleSite --themesDir=../..`

and **NO** errors, and it works fine from the localhost, and looks fine. So, I just need to use the config.toml as supplied by the theme, make changes, then copy it to the 'backup' side of things.

I'd assume this issue is now closed.  :+1:

**Comment by jehoshua7** [comment]
Closed now, thanks

**Comment by jehoshua7** [comment]
I found the error returned when I removed the other language settings from config.toml

`[Languages.en-pir]
    title = "Documentat'n fer Cap'n Hugo Relearrrn Theme"
    weight = 1
    languageName = "Arrr! Pirrrates"
    landingPageURL = "/en-pir"
    landingPageName = "<i class='fas fa-home'></i> Arrr! Home"

  [[Languages.en-pir.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
    identifier = "ds"
    url = "https://github.com/McShelby/hugo-theme-relearn"
    weight = 10

  [[Languages.en-pir.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-camera'></i> Showcases"
    url = "showcase"
    weight = 11

  [[Languages.en-pir.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bookmark'></i> Cap'n Hugo Documentat'n"
    identifier = "hugodoc"
    url = "https://gohugo.io/"
    weight = 20

  [[Languages.en-pir.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bullhorn'></i> Crrredits"
    url = "/credits"
    weight = 30`

Why I wanted to do that was because I don't want a multi-language site. I have `disableLanguageSwitchingButton = true` so that the button is disabled. Yet when I deployed there is a /en path and a /en-pir path , plus the sitemap.xml is no longer in the root path but in /en/sitemap.xml   :(

**Comment by jehoshua7** [comment]
I rolled back to 2.2 - https://github.com/McShelby/hugo-theme-relearn/archive/refs/tags/2.2.0.zip

**Comment by McShelby** [comment]
I'll take a look into that. I seems something is wrong when combining different config options.

Could you post your `config.toml` that resulted in an error?

**Comment by McShelby** [comment]
I am still not sure if this is a hugo or theme issue. Still investigating.

You may have success with the latest version of the theme if you disable the `en-pir` language in your `config.toml` like

````toml
disableLanguages = [ "en-pir" ]
````

**Comment by McShelby** [comment]
The Hugo documentation explicitly mentions to disable unused languages with the `disableLanguages`. So it seems, this is the only defined method to remove languages partly and otherwise you are in "undefined behavior" land.

The other way that works is to remove the language from `config.toml` *and* the filesystem.

If you think this should work, you could file an issue in the Hugo project and link here.

**Comment by jehoshua7** [comment]
> You may have success with the latest version of the theme if you disable the en-pir language in your config.toml like
>
> disableLanguages = [ "en-pir" ]

I added that and **no error** with the latest theme. However on a deploy, it still has the other problems, namely ..

> Yet when I deployed there is a /en path and a /en-pir path , plus the sitemap.xml is no longer in the root path but in /en/sitemap.xml :(

Even when I changed `landingPageURL = "/en"` to `landingPageURL = "/"`, the deploy still created the (multi-language) path structure. I may have come across this with another theme that was multi-language, and may search on Hugo discourse to see if it was resolved. So, it seems it may be a Hugo issue rather than a theme issue. I tried uploading the config.toml here, but GitHub won't allow it, so it is at https://pastebin.com/f5vxL8E2

**Comment by McShelby** [comment]
Multilang-Configuration ist mostly a Hugo thing. The documentation about this feature is quite good and exhaustive.

**Comment by jehoshua7** [comment]
> Multilang-Configuration ist mostly a Hugo thing. The documentation about this feature is quite good and exhaustive.

I'll assume you meant "**is**" . I tested another theme yesterday, a multi-language theme, and it only took 2 configuration settings to make it single language. So it is obvious it can be controlled by the theme, via the config settings. Of course not all themes are alike.  :)

**Comment by McShelby** [comment]
Although this is a Hugo issue (or I haven't understood the algorithm here) caused by weird sublanguage handling (of `en-pir`), we can avoid this by just setting an completly madeup language of `pir`
