### ISSUE TITLE
Click Folder labeled as "Render=never" to expand without having to click the arrow. 

### ISSUE THREAD

**Issue by DavidVargasxyz** [McShelby/hugo-theme-relearn#909]
Hello!

I currently have some subfolder index pages with a render=never flag in the yaml headers. This is so I do not show empty index pages. I would like to show the folder structure on my side bar without having an index page for each one. This works, the only problem is that you have to click specifically on the arrow in order to get the folder to expand. Is there a way to make it so that if you click anywhere on the folder (arrow and/or word) then the folder will expand? 

Thanks!

**Comment by McShelby** [comment]
Hi David! That's currently not possible. The only thing you could do is to set `alwaysopen=true` on your headless bundle to have it initially expanded.
