### ISSUE TITLE
highlight: remove additional newlines from code if copied from cursor selection

### ISSUE THREAD

**Issue by sedyh** [McShelby/hugo-theme-relearn#925]
Hello, thanks for the theme.

I would like to know how to configure the theme so that the code copied in parts is pasted without additional newlines.

Here is the code block:
```go
root := widget.NewContainer(
    widget.ContainerOpts.Layout(widget.NewRowLayout(
        widget.RowLayoutOpts.Direction(
            widget.DirectionHorizontal,
        ),
    )),
)
```

Here is the selection:
![image](https://github.com/user-attachments/assets/221f344a-b9c5-48ae-97c9-3e668054e7f6)

Here is paste result:
![image](https://github.com/user-attachments/assets/c4076706-b005-433e-b5a8-391babd45231)

**Comment by McShelby** [comment]
I can not replicate this. Please post a link to your site or repo.

**Comment by sedyh** [comment]
Yeah, sure.

Here is repo:
https://github.com/sedyh/eui

Here is published site on github-pages:
https://sedyh.github.io/eui/layouts/anchor/index.html#padding

**Comment by sedyh** [comment]
I've retested it and it happens on Firefox, but not on Chrome.

**Comment by McShelby** [comment]
Hm, your page works fine for me with the latest Firefox (131.0.2) on Windows 11.

Whats your OS and Firefox versions?

**Comment by McShelby** [comment]
I've just checked clipboard.js and there seem to be some patch releases.

Could you copy over [this file](https://github.com/zenorocha/clipboard.js/blob/master/dist/clipboard.min.js) to `static/js/clipboard.min.js`, regenerate your page and check?

**Comment by sedyh** [comment]
Hello, I'm back :)

> Hm, your page works fine for me with the latest Firefox (131.0.2) on Windows 11.
> Whats your OS and Firefox versions?

My Firefox is 130.0.1 (64-bit) and OS is Linux Mint 21.3 Cinnamon.

> Btw: I like your color styles! Look great.

Ehehe, thanks.

> Could you copy over [this file](https://github.com/zenorocha/clipboard.js/blob/master/dist/clipboard.min.js) to static/js/clipboard.min.js, regenerate your page and check?

It seems it doesn't help.

![image](https://github.com/user-attachments/assets/84794589-5e0b-4734-afc6-f68cbd3d8ba2)

![Screenshot from 2024-10-11 12-58-15](https://github.com/user-attachments/assets/b0ecc571-e8e0-4389-b92e-02608329faca)

![image](https://github.com/user-attachments/assets/9a137a22-965f-4e69-a13e-5de131994d96)

**Comment by McShelby** [comment]
@sedyh Thanks for reporting. I can now recreate the issue. Fix will come soon.

**Comment by McShelby** [comment]
This bug is fixed. Sometimes I feel like being back in browser wars in 2005.

**Comment by sedyh** [comment]
Hmm. Are permissions are correct?
`Error: error copying static files: open /home/sedyh/Documents/go/eui/public/js/theme.js: permission denied
Is that`

**Comment by McShelby** [comment]
Don't know what you are trying to do. Must be something with your deploy workflow. The theme doesn't do anything with permissions.

**Comment by sedyh** [comment]
Its the hugo serve output after I updated the theme with `hugo mod get -u`.
That was the file you just updated, so I guessed it could be something with the theme.

**Comment by McShelby** [comment]
Hm, just a wild guess: Could have something to do with this from your `hugo.toml`

````
  [[module.mounts]]
    source = 'static'
    target = 'assets'
````

I am not quite sure if it's a good idea to map the whole `static` folder over `assets`. In a new setup I would store my files in the `assets` folder in the first place, so there is no need to map.

Otherwise I'ld not map to `assets` but to a sub directory.

**Comment by sedyh** [comment]
> In a new setup I would store my files in the assets folder in the first place, so there is no need to map.
So its just better for me to move all my images and examples to assets?

**Comment by McShelby** [comment]
I would do that.
