### ISSUE TITLE
theme: page icon alignment

### ISSUE THREAD

**Issue by sedyh** [McShelby/hugo-theme-relearn#930]
Hello. I would like to be able to set icons for a page, as far as I can see they don't align if set on pages rather than chapters:
![image](https://github.com/user-attachments/assets/6c27de3e-7753-4ed8-91f8-75141d4fd949)

If you try to align them using margin, the navigation will not respond to it.
```
menuPre = '<i style="margin: 0px 2px 0px 2px" class="fa-solid fa-sm fa-window-maximize"></i> '
```
![image](https://github.com/user-attachments/assets/d68b6050-aeed-4831-9eb7-9cf0b70dbef0)

Making `text-align: center` for `<i>` and its `parent` wrapper doesn't work here either.

**Comment by McShelby** [comment]
Use Font Awesome's `fas` class for each icon:

````
<i class="fa-fw fas fa-home"></i> 
````

**Comment by McShelby** [comment]
Corrected code from my previous reply

**Comment by sedyh** [comment]
With `fa-fw`:
![image](https://github.com/user-attachments/assets/2e2c71c9-1446-4441-b7fd-fa24d4b9075e)

**Comment by McShelby** [comment]
They only align on their menu level. `fa-fw` works great. See the `exampleSite` of the theme.

**Comment by sedyh** [comment]
I mean its not about the content level. This is about the mark that gets on the name.

**Comment by McShelby** [comment]
I don't have plans to change the checkmark styling soon, as it is complicated to do right with all permutations.

The best advise for now:

- use a shorter title - [also `linkTitle` may be something, you're interested](https://mcshelby.github.io/hugo-theme-relearn/authoring/frontmatter/navigationmenu/index.html#custom-title-for-menu-entries)
- remove the checkmarks -> [see](https://mcshelby.github.io/hugo-theme-relearn/configuration/sidebar/headerfooter/index.html#history)
