### ISSUE TITLE
support: using expand in shortcode

### ISSUE THREAD

**Issue by sedyh** [McShelby/hugo-theme-relearn#931]
Hi, I don't think this is related to the theme, but rather a question about hugo, but could you help me a little? I'm sorry if this is very offtopic.

I would like to combine several include and expand in one shortcode. As far as I know, they can't be nested, but I can't figure out how to pass the content for expand from a variable to a shortcode.

The goal is to duplicate the name of the resource to every part:
```
{{< example src="lay_gri_str_all" >}}
```
To get:
```
{{< code src="assets/examples/lay_gri_str_all.txt" lang="go" id="this">}}
![all](examples/lay_gri_str_all.png)
{{% expand title="Full example" %}}
{{< code src="assets/examples/lay_gri_str_all.txt" lang="go" id="root">}}
{{% /expand %}}
```
Which will be rendered to:
![image](https://github.com/user-attachments/assets/c5ed9fba-fddf-488b-82f7-9515fb007cfa)

As far as I see expand shortcode uses partial which accepts .Inner, I'm not sure how to pass all the content I have to there without taking raw html from the partial.

**Comment by McShelby** [comment]
There is more than one way to achieve this. I would go the route, the theme already takes:

A shortcode can not be called from inside another shortcode (there are exceptions, but it's complicated).

Because of that, what the theme does, in every case, it calls a partial with the same name, forwarding all the parameter.

With this architecture, you can "call your shortcode" even from inside other partials by calling the partial instead.

If you do this for your `code` shortcode, `example` becomes trivial.

````
{{ $src := .Get "src" }}
{{ partial `shortcodes/code.html' (dict "page" . "src" $src "lang" "go" "id" "this" }}
{{ partial `shortcodes/image.html' (dict "page" . "title" "all" "url" $src }}
{{ $content := partial `shortcodes/code.html' (dict "page" . "src" $src "lang" "go" "id" "root" }}
{{ partial `shortcodes/expand.html' (dict "page" .  title "Full example" "content" $content }}
````

Warning: code not tested. You may have to sprinkle some `| safeHTML` to it.

**Comment by sedyh** [comment]
Do I understand correctly that my shortcodes and theme shortcodes will be located in the same path? I guess I dont need to define all the dict.

Not sure if I got it right:
```
execute of template failed at <.Get>: Get is not a method but has arguments
```

/layouts/shortcodes/snippet.html
```
{{ $src := .Get "src" }}
{{ partial "partials/cod.html" (dict "page" . "src" $src "lang" "go" "id" "this") }}
{{ partial "shortcodes/image.html" (dict "page" . "title" "all" "url" $src) }}
{{ $content := partial "shortcodes/cod.html" (dict "page" . "src" $src "lang" "go" "id" "root") }}
{{ partial "shortcodes/expand.html" (dict "page" .  title "Full example" "content" $content) }}
```

/layouts/partials/cod.html
```
{{ $file := .Get "src" }}
{{ $id := .Get "id" }}
{{ $lang := .Get "lang" }}
{{ $content := readFile $file }}


<!-- captures the text between start and end tag -->
{{ $blockPattern := printf `(?s)^.*?\n?(\s*)// START %s\s*\n(.*?)\n\s*// END %s\s*\n` $id $id }}
<!-- captures all start and end tags -->
{{ $tagPattern := printf `(^|\n)\s*// (START|END)\s+\w+` }}


<!-- find a matching block (in fact this finds all with same $id but only uses the first one ) -->
{{ with findRESubmatch $blockPattern $content }}
<!-- always an array, so get the first match -->
{{ with index . 0 }}
<!-- now the . is the array of matches
         IDX 0 : full text
         IDX 1 : whitespace indent before START tag
         IDX 2 : the code without START and END tag lines
        -->

<!-- create a pattern for the indentation to be removed -->
{{ $indentRemovePattern := printf `(?s)(^|\n)%s` (index . 1) }}
<!-- remove all nested tags -->
{{ $snippet := replaceRE $tagPattern "" (index . 2) }}
<!-- remove indentation -->
{{ $snippet = replaceRE $indentRemovePattern "$1" $snippet }}
<!-- highlight (trim just for safety) -->
{{ highlight (trim $snippet " \t\n" ) $lang "" }}
{{ end }}

{{ else }}
<p>No snippet found for id "{{ $id }}"</p>
{{ end }}
```

**Comment by sedyh** [comment]
I've managed to fix some of the errors:

/layout/shortcodes/cod.html
```
{{ $src := .Get "src" }}
{{ $txt := (print $src ".txt") }}
{{ $png := (print $src ".png") }}

{{ partial "partials/cod.html" (dict "page" . "src" $txt "lang" "go" "id" "this") }}
{{ partial "partials/img.html" (dict "page" . "src" $png "alt" "all") }}
{{ $content := partial "partials/cod.html" (dict "page" . "src" $src "lang" "go" "id" "root") }}
{{ partial "partials/expand.html" (dict "page" .  "title" "Full example" "content" $content) }}
```

/layout/partials/image.html
```
<img alt="{{ .alt }}" src="{{ .src }}" >
```

But idk how to:
- Pull expand partial from you lib cause it have some dependencies like makeRandomMd5.
- Make <img src=""> work, its just can't find the image when inside the partial.

**Comment by McShelby** [comment]
>Do I understand correctly that my shortcodes and theme shortcodes will be located in the same path? I guess I dont need to define all the dict. Do I also need a little partial for image?

Get familiar with the [union file system](https://mcshelby.github.io/hugo-theme-relearn/configuration/sitemanagement/structure/index.html). This is also the reason why you shouldn't write your own `/layout/partials/image.html`. The theme already contains one.

**Comment by McShelby** [comment]
I've got the feeling you should return to the basics before going further: [partials](https://gohugo.io/templates/partial/) and [templating](https://gohugo.io/templates/introduction/#context)

Note: I haven't seen it stated in the above docs, but you can only give **one** parameter to a partial, that's the reason, why multiple parameter are wrapped in a `dict`.
