### ISSUE TITLE
Regarding the issue of slow build speed after enabling the collapsibleMenu = true option

### ISSUE THREAD

**Issue by tyshcreater** [McShelby/hugo-theme-relearn#933]
Sorry, this issue shouldn't be an issue with hugo-theme-relearn. I noticed the prompt in the docs about enabling the collapsibleMenu = true option to build slowly, I actually tested it as well, and it was very slow indeed.

I don't understand if this issue is the cause of hugo, or what the problem is, I don't understand the frontend.

Because my site's directory structure is year, month, and day, and there are a lot of documents under the day, and it is rapidly increasing, the current build speed is no longer acceptable.

Please help me and tell me how I can fix this or replace hugo? Or anything else? Thank you

**Comment by McShelby** [comment]
In Relearn versions older than 7.0.0, the theme was always slow.

If you upgrade to 7.0.0 or newer, the theme is a lot faster, even with all features enabled.

If this is still to slow, you can set `collapsibleMenu=false`. This will dramatically decrease build time.

To learn how to debug your site, take a look in the Hugo docs or the official forum.
