### ISSUE TITLE
Custom svg icons in menuPre

### ISSUE THREAD

**Issue by sedyh** [McShelby/hugo-theme-relearn#935]
Hello. I love using this theme for my projects.
What classes do I need to use to make the theme start highlighting my icons the same way as font awesome?
What I will get if I just paste svg into menuPre right away:
```
+++
title = "Button"
menuPre = '<svg>...</svg>'
weight = 1
+++
```
![image](https://github.com/user-attachments/assets/5febd8c1-dbb5-4f8a-b9d8-ba79bd250895)

I think this might also be useful for others because font awesome is very limited for some cases.
Apologies if this is a very newbie question.

**Comment by McShelby** [comment]
Font Awesome is - as you might already guessed - a font. This makes coloring (if mono-colored) as simple as coloring any other text in CSS. With SVGs you are on your own. You have to solve this general HTML/CSS issue before adding it into your installation

**Comment by sedyh** [comment]
Yes, but the question is, is there some class name like “selected” attached to the text color, so that I can hook onto it and also color my icon?

**Comment by McShelby** [comment]
You can add further CSS (to configure your icon font) in `custom-header.html` -> https://mcshelby.github.io/hugo-theme-relearn/configuration/customization/dependencies/index.html#adding-javascript-or-stylesheets-to-all-pages

**Comment by sedyh** [comment]
Thanks for the info. Sorry for often interrupt.
Does selected state have some class, or its just applying text color directly and the only way to hook onto it is to load different icon font via custom headers?

**Comment by McShelby** [comment]
Take a look in the generated HTML. Various states are flagged:

![grafik](https://github.com/user-attachments/assets/17b1914e-ad7b-4324-8a53-99c4a4641f9c)
