### ISSUE TITLE
Specific text for social preview

### ISSUE THREAD

**Issue by sedyh** [McShelby/hugo-theme-relearn#936]
Hello, is there a way to specify what exactly to display in the social preview text? Sometimes it captures too much context, like code from spoilers. Ideally, I would like to display only a piece of the description.

I guess there can be some property controls `property="og:description"` and `itemprop="description"`?

![image](https://github.com/user-attachments/assets/10dd3c23-fc22-457c-be52-4169503c7b10)

![image](https://github.com/user-attachments/assets/73123f66-3e78-4569-b2c1-59e0a7ff6a1e)

**Comment by McShelby** [comment]
The theme selects the description, and if not set, it [summary](https://gohugo.io/content-management/summaries/)

**Comment by sedyh** [comment]
Oh, so there are a lot of ways to separate the content from description. Thanks, I guess it can be closed then.
