### ISSUE TITLE
search: wrong searchindex URL with multilang per server config

### ISSUE THREAD

**Issue by christophcemper** [McShelby/hugo-theme-relearn#940]
Great job with the theme, thanks!

We needed to remove the artifical prefixing of the language code to make this work in search.html
to even use the default `_relearn_searchindex.js` from the assets folder of the theme

BaseURL is `https://abc.aiprm.com/AIPRM-XYZ/`
Site is multilingual
However the static files are only deployed 1 time, to `https://abc.aiprm.com/AIPRM-XYZ/_relearn_searchindex.js
`
The special case that someone deploys the same static files to language-prefixed folders cannot be default.

Also it was constructed wrong, as it ended up in `https://abc.aiprm.com/en/_relearn_searchindex.js`
which doesn't even sit in the same home folder/vserver on the http
and the same for all other languages.

In a 2nd line of code we had the relLangURL, which again implies the special case being default - assets in language folders and enforces the current language prefixed

here's the diff and changed file attached, not sure how to commit/add directly to repo

diff --git a/layouts/partials/search.html b/layouts/partials/search.html
index 3c5acda17c..9b1c143f48 100644
--- a/layouts/partials/search.html
+++ b/layouts/partials/search.html
@@ -11,14 +11,14 @@
           {{- warnf "UNSUPPORTED usage of 'searchpage' output format found, remove it from your config; see https://mcshelby.github.io/hugo-theme-relearn/introduction/releasenotes/7/#7-0-0" }}
         {{- end }}
         {{- if not .Site.Params.disableSearchIndex }}
-          {{- $url := path.Join .Site.LanguagePrefix (trim (or .Site.Params.searchIndexURL "searchindex.js") "/") }}
+          {{- $url := path.Join (trim (or .Site.Params.searchIndexURL "searchindex.js") "/") }}
           {{- if .IsHome }}
             {{- $templateres := resources.Get "_relearn_searchindex.js" }}
             {{- $resultres := $templateres | resources.ExecuteAsTemplate $url .Site.Home }}
             {{- /* the following code causes Hugo to generate our file - although it is in comments */}}
           {{- end }}
         <script>
-          window.index_js_url={{ (printf "%s%s" $url $assetBusting) | relLangURL }};
+          window.index_js_url={{ (printf "%s%s" $url $assetBusting) | relURL }};
         </script>
           {{- if not .Site.Params.disableSearchPage }}
             {{- with .Site.GetPage "_relearn_searchpage" }}

[search.html.zip](https://github.com/user-attachments/files/17478964/search.html.zip)

If there's a use case where people have separate static asset folders, then that would be a separate mode to implement imho,
but the default theme should work out-of-the-box imho.

Hope this helps.

**Comment by christophcemper** [comment]
Ok found the PR feature :)

**Comment by McShelby** [comment]
Thanks for the detailed bug report. Just for completeness, can you please post your `hugo.toml`. This helps in recreating a failing test before starting to fix and break for other configurations.

**Comment by McShelby** [comment]
I can not replicate this with my configuration. Please provide your `hugo.toml` or even better, a link to your repo.

Nevertheless, I have a vague idea why this may go wrong with your setup.

**Comment by christophcemper** [comment]
Thanks, just saw your q for feedback and fix, didn't get to this sooner.
