### ISSUE TITLE
Have you seen anyone use Giscus on relearn before? 

### ISSUE THREAD

**Issue by tdavetech** [McShelby/hugo-theme-relearn#946]
I have Gicus comments kind of working, But I want the comments at the bottom of the page only instead of sort of hovering over the page the whole time like this 
![image](https://github.com/user-attachments/assets/4c4584f1-6dc7-405a-b191-c5d0fbc9531b)

**Comment by McShelby** [comment]
I don't use any commenting system but would assume, that it couldn't be to hard if you are fluent in CSS.
