### ISSUE TITLE
How do I add images to text correctly?

### ISSUE THREAD

**Issue by krotesk** [McShelby/hugo-theme-relearn#958]
I have the images in png format.
I put them in the content directory, in the pics directory in the content directory - didn't work. Then I copied to static also in the pics directory and without it in the root. They are not displayed!
![Снимок экрана от 2024-12-04 11-57-56](https://github.com/user-attachments/assets/747c2747-8c17-4ea2-8759-7294498bc36c)
![Снимок экрана от 2024-12-04 11-57-41](https://github.com/user-attachments/assets/760b0324-3620-42fc-976c-149fbe5d22a2)

**Comment by McShelby** [comment]
This is a Hugo question. You need a [page bundle](https://gohugo.io/content-management/page-bundles/)
