### ISSUE TITLE
Breadcrums disappear on mobile

### ISSUE THREAD

**Issue by es20490446e** [McShelby/hugo-theme-relearn#962]
I'm making this website: https://zenned.gitlab.io

When I zoom in, or visit the site on a phone, the breadcrumbs disappear. Even when there is still plenty of room for them.

Is there any way to prevent this? 🤔

Do the breadcrumbs make this decision relative to available page width?

**Comment by McShelby** [comment]
On smaller screens the breadcrumbs are hidden by intent. This is not configurable.
