### ISSUE TITLE
docs: fix broken link: web fonts with CSS

### ISSUE THREAD

**Issue by es20490446e** [McShelby/hugo-theme-relearn#963]
At: https://mcshelby.github.io/hugo-theme-relearn/shortcodes/icon/index.html

**Comment by McShelby** [comment]
The joy of degrading links over time: https://docs.fontawesome.com/web/style/styling

**Comment by McShelby** [comment]
Thanks for reporting.

**Comment by es20490446e** [comment]
👌😉

**Comment by McShelby** [comment]
Unrecognised broken links are bad. Let's do something about that #964
