### ISSUE TITLE
notice: links aren't clickable

### ISSUE THREAD

**Issue by colans** [McShelby/hugo-theme-relearn#968]
Here's an example:

![image](https://github.com/user-attachments/assets/7328ba4a-9853-44d0-9122-525e8fa773ff)

It *looks* like a link, but when you hover over it, you get nothing.  And when you click on it, nothing happens.

In other news, thanks for this theme; it's great!

**Comment by daniellemaxwell** [comment]
@colans I've been experiencing the same issue with the `notice` shortcode and was about to post an issue as well.

**Comment by colans** [comment]
@daniellemaxwell Thanks for confirming!  Once we nail down how widespread this is, we can generalize the title some more.  Suggestions welcome.

**Comment by colans** [comment]
Yup, adding a `+` after the brackets helps, but then we're left with an unwanted down arrow (so thanks for tagging as a bug and looking into this).

**Comment by McShelby** [comment]
Found it. I'll make a release in two minutes.

**Comment by McShelby** [comment]
Release 7.2.1 with the bug fix is online. Thanks and sorry for the inconvenience

**Comment by colans** [comment]
Thanks for fixing so quickly!
