### ISSUE TITLE
docs: example to show separate logo file on subpages

### ISSUE THREAD

**Issue by textractor** [McShelby/hugo-theme-relearn#969]
I overrode the partial as documented [here](https://mcshelby.github.io/hugo-theme-relearn/configuration/branding/logo/index.html#change-the-logo). I just copied the existing partial in the Relearn doc site to my `layouts/partials/` and substituted an image tag for the svg:

```
 1 <a id="R-logo" href="{{ partial "permalink.gotmpl" (dict "to" .Site.Home) }}">
 2 <img src="octobuddy_purple_fade.png" alt="MyDecisive Octobuddy logo">
 3 {{ .Site.Params.linkTitle | default .Site.Title }}
 4           </a>
```

It shows up nicely on the home page, but is a broken link on all of the others. How do I get it to show up on all of the other pages?

**Comment by textractor** [comment]
Apologies if this should have gone in discussions, I just noticed that.

**Comment by McShelby** [comment]
Hi, the documentation lacks an example for this. Try this

````
<a id="R-logo" href="{{ partial "permalink.gotmpl" (dict "to" .Site.Home) }}">
<img src="{{"octobuddy_purple_fade.png" | relURL}}" alt="MyDecisive Octobuddy logo">
{{ .Site.Params.linkTitle | default .Site.Title }}
</a>
````

**Comment by textractor** [comment]
Perfect, makes sense and works. Thank you!

**Comment by McShelby** [comment]
I'll add documentation for this.

**Comment by textractor** [comment]
Unfortunately that fix worked locally, but on push to GitHub the rendered site there shows logos as broken now, even on the home page.

**Comment by textractor** [comment]
Looks like in GitHub pages it renders like this, with the repo prepended to path:

```
<a id="R-logo" href="/mdai-docs-v2/index.html">
<img src="/mdai-docs-v2/octobuddy_purple_fade.png" alt="MyDecisive Octobuddy logo">
</a>
```

Locally I get this:

```
<a id="R-logo" href="/index.html">
<img src="/octobuddy_purple_fade.png" alt="MyDecisive Octobuddy logo">
 
          </a>
```

I don't understand why the path difference, and maybe that's beyond the scope of the theme. Or is there a way to code this in the theme so that it works right on GitHub?

**Comment by McShelby** [comment]
Both is correct behavior for the code I've provided under the assumption that the image belongs to your Hugo project and resides in your `static` directory.
