### ISSUE TITLE
docs: example for cascading sidebar menu reusing existing menus

### ISSUE THREAD

**Issue by Anagastes** [McShelby/hugo-theme-relearn#970]
Hi, I currently have the problem of having two separate areas using the cascading function.

https://mcshelby.github.io/hugo-theme-relearn/configuration/sidebar/menus/index.html#redefining-sidebar-menus-for-certain-pages

However, the “more” area in the sidemenu then disappears. 

![grafik](https://github.com/user-attachments/assets/ac334fa4-6544-44d7-b47a-84bd3d780713)

It could also be that I am really too stupid to understand the system. 

Is there a way to cascade the “more” area?

**Comment by McShelby** [comment]
Please post a link to your project sources. This is the quickest way to help you.

Without seeing your pages frontmatter: If you overwrite the `sidebarmenus` config in your front matter, you have to redefine everything. So if if `more` is missing, add an additional entry to your front matter:

````
    [[cascade.params.sidebarmenus]]
      identifier = 'shortcuts'
      type = 'menu'
````

**Comment by Anagastes** [comment]
> Please post a link to your project sources. This is the quickest way to help you.
> 
> Without seeing your pages frontmatter: If you overwrite the `sidebarmenus` config in your front matter, this resets the whole sidebar menu configuration. You have to redefine everything. So if if `more` is missing, add an additional entry to your front matter:
> 
> ```
>     [[cascade.params.sidebarmenus]]
>       identifier = 'shortcuts'
>       type = 'menu'
> ```
> 
> I'll add this to the docs.

Your right. Now it works. Perfect! :D 

And yeah, should be in your doc's. Now I understand this better! :)

```
+++
title = 'Blog'
weight = 100
[_build]
  render = 'never'
[[cascade]]
  [cascade.params]
    [[cascade.params.sidebarmenus]]
      identifier = 'blog'
      pageRef = '/blog'
      type = 'page'
    [[cascade.params.sidebarmenus]]
      identifier = 'shortcuts'
      type = 'menu'
+++
```
